### PR TITLE
fix failing column and map test

### PR DESCRIPTION
**Pull request by dpatil-magento**
## Description

Fixes failing cypress column test

## Related Issue

Closes https://jira.corp.magento.com/browse/PWA-2616

## Verification Steps

1. Run cypress build on this pr and verify both tests pass.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by pedrochiossi — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
blackout does not work always and have open bugs at the moment so cant trust this approach for now.
https://github.com/jaredpalmer/cypress-image-snapshot/issues/199
https://github.com/cypress-io/cypress/issues/5842

**Comment by mikhaelbois** [comment]
We are still testing the Google Maps iframe content.
As soon as Google will change something on their side, the test will start failing again.
Since blacking out is not an option, maybe we should intercept the Google API call so we avoid loading it in the page?

```
// Prevent default Google API from loading
cy.intercept('https://maps.googleapis.com/maps/api/js?*', {});
```

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by mikhaelbois** [comment]
run cypress

**Review by jeremycharron — APPROVED** [review]
Code looks good to me. 👍

**Comment by mikhaelbois** [comment]
run all tests

**Pull request merged**
