### PR TITLE
AC-2498-Images lacking meaningful alternative text. (Account - Order …

### PR DESCRIPTION
**Pull request by glo82145**
…History)

## Description

Reproduction Steps
Sign In > select "Order History" from account dropdown - [NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(3)]

1. With JAWS operating, use the down arrow key to read through a collapsed preview of an order with multiple products.

Actual Behavior
In the Order History list, when an order accordion is closed, the product images do not provide meaningful alternative text - each image listed has alt text of "Main". The information conveyed by these images - i.e. a quick view of products included in the order - is not provided to screen reader users.

Note that there are two  elements for each product image (for eager and lazy loading); although the eager image is visually hidden, it is still available to assistive technology. As a result, the same alt text for each product is announced twice.

Expected Behavior
Images that convey information must provide descriptive textual alternatives. In this case, the alt text for each image should be brief but identifying image about the product, likely the product name.

Ensure that content intended to be hidden from all users, such as the eager image once the lazy image loads, is also hidden from assistive technology.

## Related Issue

Closes [#AC-2498.](https://jira.corp.adobe.com/browse/AC-2498)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3946: AC-2498-Images lacking meaningful alternative text. (Account - Order …

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — CHANGES_REQUESTED** [review]
Thanks @glo82145 - Would you take a look and resolve the failing unit test please?

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Approved

**Pull request merged**
