### PR TITLE
Improve Gallery/AddToCartButton.js

### PR DESCRIPTION
**Pull request by 0m3r**
## Description
0) Replace mergeClasses to useStyle
1) AddToCartIcon and OutOfStockIcon did't work properly 

```jsx
const AddToCartIcon = (
    <Icon
        classes={{ icon: defaultClasses.icon }} 
        src={ShoppingBag}
        attrs={{ width: 16 }}
    />
);
```
defaultClasses.icon is always hidden and parent component can't change it

## Related Issue

PWA-1392
https://github.com/magento/pwa-studio/commit/1977f38305ff6c0e2b23a9da7beb0b2f69758bed

## Verification Steps

0.
1) open packages/venia-ui/lib/components/Gallery/addToCartButton.js
2) at line 35 was use mergeClasses in 12.1 need to use useStyle
```jsx
const classes = mergeClasses(defaultClasses, props.classes);
```

1.
1) open packages/venia-ui/lib/components/Gallery/addToCartButton.js
2) AddToCartIcon and OutOfStockIcon  use defaultClasses variable instead of classes

 

### Resolved issues:
1. [x] resolves magento/pwa-studio#3607: Improve Gallery/AddToCartButton.js

### CODE REVIEW

**Review by TheSusort — APPROVED** [review]

**Comment by 0m3r** [comment]
Guys (maintainers @michael0123 @bdenham) please add label version:patch 

> A version label is required. A maintainer must add one.

**Comment by supernova-at** [comment]
@magento create issue from PR

**Review by pedrochiossi — APPROVED** [review]
Looks good @0m3r

**Comment by 0m3r** [comment]
@pedrochiossi, please set the version lab
Знімок екрану з 2021-12-13 10-26-59
el

**Comment by 0m3r** [comment]
@magento add to contributors team

**Comment by 0m3r** [comment]
@magento add to contributors team

**Pull request merged**
