### PR TITLE
[PB] Carousel appearance for Product content type

### PR DESCRIPTION
**Pull request by omiroshnichenko**
## Description
Add support of carousel appearance in Products component

## Related Issue
[https://jira.corp.magento.com/browse/PB-175](https://jira.corp.magento.com/browse/PB-175)

## Verification Steps
1. Check that each property for each content type appearance renders correctly on PWA Venia storefront in desktop and mobile.
2. Compare Venia PWA rendering of content type with Luma to ensure the experience is the same or better for each property of each appearance in desktop and mobile.
3. Check each supported browser and on mobile that is supported according to PWA documentation.
4. Acceptable performance has been validated

Notice: Do not merge until ticket will be in status `Acceptance - Done`

### CODE REVIEW

**Comment by zetlen** [comment]
Hey @omiroshnichenko, this looks good! However, I have to ask any time I see a static import of a large third-party component like `react-slick`: have you validated that this doesn't dramatically change the bundle size? You can check visually by running `yarn run stats:venia` and comparing your results between the branches.

**Comment by omiroshnichenko** [comment]
Hi @zetlen. `react-slick` has been added to `Slider` component in the scope of https://github.com/magento/pwa-studio/pull/1870

**Comment by zetlen** [comment]
I know the library is necessary! I'm just wondering whether changing its import site is changing the generated bundles in any significant way.

**Comment by omiroshnichenko** [comment]
develop:
Gzipped: 363.53KB
Parsed: 1.34 MB
Stat: 2.88 MB

PB-175:
Gzipped: 365.89 KB
Parsed: 1.35 MB
Stat: 2.9 MB

**Comment by zetlen** [comment]
OK, no problem. As long as it responds fast and loads `react-slick` asynchronously with respect to the CMSPage.

**Pull request merged**
