### PR TITLE
PWA-2463: Header - Logo dimensions overlap with main content

### PR DESCRIPTION
**Pull request by michaelyu0123**
## Description

Logo link overlaps content outside the main navigation.

Acceptance Criteria

Logo dimensions fits inside the bounds of the Header and is not clickable outside of it.

## Related Issue

Closes #PWA-2463

#### Test scenario(s) for direct fix/feature
Test Plan

Verify clicking on venia logo being on Search , Category, Product, Cart, Checkout gets you back to Home page.
Verify on Chrome, FF, Safari and mobile device
Update Cypress Anchor link test to include this step

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by pedrochiossi — DISMISSED** [review]
All good. ✅

**Comment by ericeoeur** [comment]
Most cypress integration tests have failed due to snapshot mismatching: 

integrationTests/customerService/customerService.spec.js
integrationTests/pageBuilder/banner.spec.js
integrationTests/pageBuilder/block.spec.js
integrationTests/pageBuilder/divider.spec.js
integrationTests/pageBuilder/dynamicBlock.spec.js
integrationTests/pageBuilder/image.spec.js
integrationTests/pageBuilder/map.spec.js
integrationTests/pageBuilder/products.spec.js
integrationTests/pageBuilder/row.spec.js
integrationTests/pageBuilder/slider.spec.js
integrationTests/pageBuilder/smokeTest.spec.js
integrationTests/pageBuilder/video.spec.js

**Comment by michaelyu0123** [comment]
> Most cypress integration tests have failed due to snapshot mismatching:
> 
> integrationTests/customerService/customerService.spec.js integrationTests/pageBuilder/banner.spec.js integrationTests/pageBuilder/block.spec.js integrationTests/pageBuilder/divider.spec.js integrationTests/pageBuilder/dynamicBlock.spec.js integrationTests/pageBuilder/image.spec.js integrationTests/pageBuilder/map.spec.js integrationTests/pageBuilder/products.spec.js integrationTests/pageBuilder/row.spec.js integrationTests/pageBuilder/slider.spec.js integrationTests/pageBuilder/smokeTest.spec.js integrationTests/pageBuilder/video.spec.js

@ericeoeur the integration tests have been updated. Currently the build has been disabled for the time being so please run it locally against https://pr-3659.pwa-venia.com/

**Review by ericeoeur — APPROVED** [review]
LGTM. QA has passed and will be merging soon. Thanks!

**Comment by ericeoeur** [comment]
@michaelyu0123 After updating the branch with the latest release from develop, `prettier` is failing on the following file: `venia-integration-tests/src/fields/header/index.js`. Please review when able, thanks!

**Comment by michaelyu0123** [comment]
> @michaelyu0123 After updating the branch with the latest release from develop, `prettier` is failing on the following file: `venia-integration-tests/src/fields/header/index.js`. Please review when able, thanks!

@ericeoeur prettier ran.

**Review by ericeoeur — APPROVED** [review]
LGTM

**Pull request merged**
