### PR TITLE
Fix for ` product_url_suffix` cloud be return es `null` if admin don't want to use a suffix

### LINKED ISSUE #3669: [bug]: product_url_suffix cloud be return as null from backend
**Describe the bug**

product_url_suffix cloud be returned as null from backend see https://docs.magento.com/user-guide/catalog/catalog-urls.html#html-suffix

**To reproduce**

1. Go to backend under Store Config -> Catalog -> Search  Engine 
2. Make Product URL Suffix empty 
2. Click on save clean cache 
3. Go to Product listing Page 
4.  You will see the  following error 

```
The prop `storeConfig.product_url_suffix` is marked as required in `GalleryItem`, but its value is `null`.
    at GalleryItem (@magento/venia-ui/lib/components/Gallery/item.js:370:7)
```

**Expected behaviour**
- No error happens 

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by larsroettig**
## Description
Fix for ` product_url_suffix` cloud be return as `null` if admin don't want to use a suffix

## Related Issue

Closes #3669

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by jeremycharron** [comment]
@larsroettig Missing issue number 😉 .
But fix looks good!

**Comment by larsroettig** [comment]
> @larsroettig Missing issue number wink . But fix looks good!

#3669 created with more details

**Review by jeremycharron — APPROVED** [review]
Approved.
Checks should pass on next build with version label added.

**Comment by dpatil-magento** [comment]
run cypress

**Comment by ericeoeur** [comment]
✅ QA has passed for this ticket. Once lighthouse tests have passed, will merge. Thanks!

**Comment by ericeoeur** [comment]
run lighthouse-desktop
run lighthouse-mobile

**Comment by ericeoeur** [comment]
run lighthouse-desktop

**Comment by ericeoeur** [comment]
run lighthouse-mobile

**Pull request merged**
