### PR TITLE
PWA-2801: Reduce docker build context size

### PR DESCRIPTION
**Pull request by OneCricketeer**
## Description

Reduces the context sent to the Docker daemon upon builds. 

Example, on related builds

```
+ docker build ...
Sending build context to Docker daemon  385.9MB
```

After (this build)

```
+ docker build ...
Sending build context to Docker daemon  12.79MB
```

Closes JIRA-[PWA-2801](https://jira.corp.magento.com/browse/PWA-2801).

## Acceptance

Docker builds continue to work (necessary files are copied in from the context) and we are able to deploy a running container. 

#### Test scenario(s) for direct fix/feature

Docker build and deploys are successful. 

## Checklist

-   I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by OneCricketeer** [comment]
run all tests

**Comment by OneCricketeer** [comment]
run scaffold-pwa

**Review by haal9000 — APPROVED** [review]

**Comment by haal9000** [comment]
LGTM

**Review by sharkySharks — APPROVED** [review]

**Comment by sharkySharks** [comment]
run lighthouse-desktop

**Review by sharkySharks — APPROVED** [review]

**Pull request merged**
