### PR TITLE
Pwa 3065::When the button "sign in" is pressed by the keyboard, nothing happens.

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Pre-Conditions:

Have Magento 2.4.6alpha2 EE setup with [Venia configured](https://wiki.corp.adobe.com/display/ACRQ/PWA+Studio+Set+Up+in+Local).
Make sure Venia has at least one customer login account to login into the Venia front end.
Make sure Screen reader installed and enabled.
Steps to Reproduce:

Open Venia front end in any browser 
Navigate by using tab button sign in button > press enter to expand 
Fill the details to sign in and press key ENTER from being on sign in button
 

Expected result: Sign in button should respond with its functionality in the UI when the ENTER key is pressed.

Actual result: Sign in button is not working with the keyboard when the ENTER key is pressed

## Related Issue

Closes #[PWA-3065.](https://jira.corp.adobe.com/browse/PWA-3065)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Review by RaghavendraTirumalasetti — APPROVED** [review]

**Comment by glo82145** [comment]
run cypress

**Comment by glo82145** [comment]
run lighthouse-mobile

**Pull request merged**
