### PR TITLE
[PWA-2479] Hide create whishlist button when maximum number of wishlists reached

### PR DESCRIPTION
**Pull request by jeremycharron**
## Description

Hide the "create a list" button when reaching maximum number of wishlists
Was only occuring in the "Favorite lists" section. Catalog and product pages were already covered. 

**Multiple wishlists must be enabled in the backend**
https://docs.magento.com/user-guide/configuration/customers/wishlist.html

Also fixed warning in console about formError wrong value type

## Related Issue

Closes PWA-2479

### Verification Stakeholders

Project maintainers

#### Test scenario(s) for direct fix/feature

1. In Favorite Lists section of user account, verify that "Create a list" button is hidden when maximum number of wishlists is reached

#### Test scenario(s) for any existing impacted features/areas

1. Verify single wishlist for commerce edition
2. Verify single wishlist for Community edition
3. Verify Multiple wishlist for 2 and 5 wishlist as config and make sure Venia UI respects the backend configs.
4. Verify in Chrome, FF, Safari and Mobile device
5. Update Multiple wishlist mock data cypress test to include this fix test coverage
6. Verify that there is no error/warning in console about FormError wrong type value

#### Test scenario(s) for any Magento Backend Supported Configurations

N/A

#### Is Browser/Device testing needed?

I don't think it's required, but nice to have. 

#### Any ad-hoc/edge case scenarios that need to be considered?

No

## Breaking Changes (if any)

No breaking change

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by pedrochiossi — APPROVED** [review]
Looks good @jeremycharron 👍🏻

**Comment by mikhaelbois** [comment]
@jeremycharron 
Following Cypress test is failing.
`src/tests/integrationTests/wishList/verifyMultipleWishlistFeatures.spec.js`
Getting the following error on Wishlist Page.
```
Warning: Failed prop type: Invalid prop `errors[0]` of type `Boolean` supplied to `FormError`, expected instance of `Error`.
    at FormError (webpack-internal:///../venia-ui/lib/components/FormError/formError.js:27:14)
    at WishlistEditFavoritesListDialog (webpack-internal:///../venia-ui/lib/components/WishlistPage/wishlistEditFavoritesListDialog.js:33:5)
```
Visual bug when Wishlist name is too long.
image
Apart from that, multiple wishlist feature on EE works as intended.

**Comment by jeremycharron** [comment]
@mikhaelbois Cypress test has been fixed. 
I also updated the test to check that "create list" button is hidden when maximum amount of wishlist is reached. Please review added code.

I created https://jira.corp.magento.com/browse/PWA-2554 for the visual bug. While testing I found multiple areas that would benefits from some improvements.

**Comment by jeremycharron** [comment]
@mikhaelbois 
Following warning/error that was occuring in console has been fixed : 
```
Warning: Failed prop type: Invalid prop `errors[0]` of type `Boolean` supplied to `FormError`, expected instance of `Error`.
    at FormError (webpack-internal:///../venia-ui/lib/components/FormError/formError.js:27:14)
    at WishlistEditFavoritesListDialog (webpack-internal:///../venia-ui/lib/components/WishlistPage/wishlistEditFavoritesListDialog.js:33:5)
```

**Comment by mikhaelbois** [comment]
QA ✅

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run pr-test

**Pull request merged**
