### PR TITLE
Update index.md - spell correction

### PR DESCRIPTION
**Pull request by alwinpaul**
## Description

TODO: Spelling correction for Introduction To React.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2470.pwa-venia.com : LH Performance Expected 0.85 Actual 0.55, LH Best Practices Expected 1 Actual 0.92
https://pr-2470.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.36, LH Best Practices Expected 1 Actual 0.92
https://pr-2470.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.5, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92

**Comment by tjwiebell** [comment]
Hi @alwinpaul 🙂  thank you for the contribution. This looks ready to merge, but we need you to sign the Adobe CLA, if you could please let me know once that has been completed.

**Comment by alwinpaul** [comment]
Hi @tjwiebell Thank you for the revert. I have signed the Adobe CLA.

**Comment by macdonst** [comment]
@tjwiebell I think the reason the check is failing is when @alwinpaul signed the CLA he left the `@` symbol in the text field for github username. 

@alwinpaul can you re-sign the agreement with `alwinpaul` for your github username and close/open this PR?

**Pull request closed without merging**
