### PR TITLE
PWA-2824: [bug]: Mega menu collapses when trying to select sub-catego…

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Resolved megamenu closing.
- Resolution provided by https://github.com/JustinConabreeAbsolunet in https://github.com/magento/pwa-studio/issues/3812

## Description

When trying to click on a sub category (ex Bottoms > Pants & Shorts) the menu collapses. This is due to the PageLoadingIndicator positioning of relative taking precedent over the positioning absolute. And thus fixed the related CSS.

## Related Issue

Closes #PWA-2824 and https://github.com/magento/pwa-studio/issues/3812

## Verification Steps

1. Hover over first level category. Menu will open
2. Try to select second level category

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
run all tests

**Review by anthoula — APPROVED** [review]

**Review by anthoula — APPROVED** [review]

**Comment by michaelyu0123** [comment]
run lighthouse

**Comment by michaelyu0123** [comment]
run lighthouse-desktop

**Comment by michaelyu0123** [comment]
run lighthouse-mobile

**Pull request merged**
