### PR TITLE
AC-3522::Product search result with items count is not being read by screen reader

### PR DESCRIPTION
**Pull request by glo82145**
## Description
product search result with items count is not being read by screen reader

Pre Conditions:

Have Venia setup working with Magento 2.4.5-alpha2 in the local.
Have sample data available in the instance
Have Google chrome screen reader extension enabled and working.
Steps to reproduce:

Keeping extension enabled, open the venia front end in the chrome browser.
Tab the focus to search button in the home page.
Press return key from the keyboard and input with the text that results with items found. (ex: carina)
Expected: Screen reader should announce the total items found in the searched result.

Actual: Randomly announcing the text from left side filters options sometimes or sort items dropdown, as such.

## Related Issue

Closes https://jira.corp.magento.com/projects/AC/issues/AC-3522

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3920: AC-3522::Product search result with items count is not being read by screen reader

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run pr-deploy

**Comment by anthoula** [comment]
@adobe create issue from PR

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by jcalcaben — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Review by dpatil-magento — APPROVED** [review]

**Pull request merged**
