### PR TITLE
PWA-3049::[PWA] Internal Page Builder links with query part

### PR DESCRIPTION
**Pull request by glo82145**
## Description

ISSUE: 

GET params (query part of the link) are missed in URL after clicked on the link

STEPS TO REPLICATE:

Install the latest Magento 2 ee
Install the latest PWA studio
Admin: Open the home page in the Page Builder editor and add HTML code with the link:
<a href="/some-cat.html?teeeest=123">adewfewf</a>  

Frontend: Open the home page in PWA venia
Click on the link

EXPECTED RESULTS:

Page with GET param opened

ACTUAL RESULTS:{}

GET params are missed

## Related Issue

Closes [#PWA-3049](https://jira.corp.adobe.com/browse/PWA-3049)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo82145** [comment]
run cypress

**Review by RaghavendraTirumalasetti — DISMISSED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run pr-test

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Review by RaghavendraTirumalasetti — APPROVED** [review]

**Pull request merged**
