### PR TITLE
PWA-3087::PWA shows 404 when having store code in URL

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Prerequisites:
Adobe Commerce 2.4.5-p1
PWA Studio

Steps to reproduce:
Set "USE_STORE_CODE_IN_URL" to 'true' in the PWA Studio's .env
Set Stores > Configuration > General > Web > URL Options > Add Store Code to Urls = Yes
Create a test CMS page
Add a link to the above CMS page using the page builder HTML element
<a href="{{store url =''}}test">My Test Page 1</a>
It is a requirement to have the full URL (including the store code) for SEO purposes.

Open the home page in the PWA storefront and click on the test link
Please refer to the screen recording for more details.
 Screen recording
https://shared-assets.adobe.com/link/e9e489f4-9518-4c00-6c52-08b512c254c5

 Actual result:
404 error

 Expected result:
The page should load

## Related Issue

Closes https://jira.corp.adobe.com/browse/PWA-3087

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run cypress

**Comment by glo82145** [comment]
run cypress

**Comment by glo82145** [comment]
run cypress

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-desktop

**Pull request merged**
