### PR TITLE
AC-2492::Missing visual text label for buttons

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Reproduction Steps
select "Blouses & Shirts" > select "Susanna Draped Tank" - [NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(3)]

1. Press Tab to move through the content.

Actual Behavior
There are no visual text labels for "Fashion Color" buttons.

When no visual labels (text or image labels) and/or instructions are provided for input, users with visual or cognitive disabilities may not know what a field is for.

Expected Behavior
Provide text labels that are always visible to indicate the purpose of each button.

## Related Issue

Closes [#AC-2492.](https://jira.corp.adobe.com/browse/AC-2492)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3958: AC-2492::Missing visual text label for buttons

### CODE REVIEW

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by jcalcaben — CHANGES_REQUESTED** [review]
Please update the tests to use the new `attributeLabel` values so that the snapshots don't say things like `undefined's  option red`

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
