### PR TITLE
AC-2488::'Has Video' checkboxes do not provide descriptive labels. (S…

### PR DESCRIPTION
**Pull request by glo82145**
…earch Results)

## Description
Reproduction Steps
search "short" - [NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(3)]

1. Press Tab to move through the content.
2. When keyboard focus is on "Filter" button, press Enter or Space to activate it.
3. Press Tab through "Filter" menu and once focus is on "Has Video" press Enter.

Actual Behavior
"Has Video" checkboxes do not provide descriptive labels. The labels for these checkboxes are "0" and "1".

When checkbox labels are not descriptive, screen reader users and users with cognitive disabilities will not be able to discern the specific purpose of each checkbox.

Expected Behavior
Ensure that the labels are descriptive.

## Related Issue

Closes https://jira.corp.adobe.com/browse/AC-2488

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3947: AC-2488::'Has Video' checkboxes do not provide descriptive labels. (S…

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress @e2e

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
@glo82145 I'm confused on what this fix is about. Its breaking a better experience already on https://develop.pwa-venia.com/ . When focus is on say `No`  the existing` aria-label="Apply filter "Has Video:No"."` is now `aria-label="Apply filter "Has Video:"."` which does not give any additional info , instead its removing useful text as well. please check.

**Comment by glo82145** [comment]
> @glo82145 I'm confused on what this fix is about. Its breaking a better experience already on https://develop.pwa-venia.com/ . When focus is on say `No` the existing` aria-label="Apply filter "Has Video:No"."` is now `aria-label="Apply filter "Has Video:"."` which does not give any additional info , instead its removing useful text as well. please check.

@dpatil-magento Earlier on develop site, it is announcing two 'No' or 'Yes' on focus on 'has video' but now when I check it is working as expected on develop so if you suggest we can remove these changes as its working fine without it.

**Comment by anthoula** [comment]
As this change removes voiceover description for Has Video on Mac, we are closing this ticket. The voiceover announces as expected on develop.pwa-magento.com for the Has Video filter.

**Pull request closed without merging**
