### PR TITLE
PWA-2415: Configurable images are not shown in Edit Cart Item menu

### PR DESCRIPTION
**Pull request by rwalter215**
## Description

The edit form in the Cart page displays the parent product's image for configurable products, and also the imagery doesn't change on toggle.

To reproduce:

Go to the [Venia Home page](https://venia.magento.com/)
Add a configurable product to the cart.
Go to the cart page.
Edit the item.
You could see that the configurable product's image is of the parent product's image and doesn't change on toggle.

Expected behavior

The edit form in the Cart page should display the the correctly configured images when the options are changed on toggle.

Resolution
- Added store config query to useProductForm
- refactored productDetail, in the editModal, to show configured cart item image when set

## Related Issue

Closes PWA-2415.

## Verification Steps

Test plan detailed in: https://jira.corp.magento.com/browse/PWA-2415
#### Test scenario(s) for direct fix/feature

Test Plan

Set product image in backend - Store> Configuration >Sales > Checkout > Shopping Cart > Configurable Product Image to use product variation thumbnail for DEfault and French store view

Add configurable product (Non-default image) Verify product image thumbnail is shown in cart
Add configurable product (default image) Verify product image thumbnail is shown in cart (It might be parent image itself in this case)
Verify above on Default and French store View
Add simple product to cart to make sure it still works

Set product image in backend - Store> Configuration >Sales > Checkout > Shopping Cart > Configurable Product Image to use product variation thumbnail for French store and have Parent product image for Default store

Add configurable product (Non-default image) Verify parent image thumbnail is shown in cart on default store. Now switch to French store and verify Product image thumbnail is shown
Test Coverage
Add unit tests
Add cypress integration mock data test. Add non-default product on default store and verify parent thumbnail and now switch to French store > Load mock response configs and verify Product image is shown

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
@rwalter215 please resolve packages/peregrine/lib/talons/CartPage/ProductListing/EditModal/__tests__/useProductForm.spec.js unit test failure.

**Review by michaelyu0123 — CHANGES_REQUESTED** [review]
@rwalter215 please resolve packages/peregrine/lib/talons/CartPage/ProductListing/EditModal/tests/useProductForm.spec.js unit test failure.

**Review by michaelyu0123 — APPROVED** [review]
LGTM

**Comment by mikhaelbois** [comment]
run cypress

**Comment by mikhaelbois** [comment]
run cypress

**Comment by mikhaelbois** [comment]
@rwalter215 
QA ✅ 
Cypress tests that are failing already have a follow-up task.
Found a new unrelated bug and created a task for that as well.

**Pull request merged**
