### PR TITLE
Sync main

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Syncing main branch with develop branch

## Related Issue

Closes [#PWA-3099.](https://jira.corp.adobe.com/browse/PWA-3099)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by RaghavendraTirumalasetti — APPROVED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Pull request merged**
