### PR TITLE
Update "Update App import statements" instructions

### PR DESCRIPTION
**Pull request by mpchadwick**
the MiniCart import now also needs to be replaced

## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

### Verification Steps

1. Go to the FOO page.
2. Verify the BAR shows up.
3. Make sure BAZ does a thing.

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]
Still kind of Hacktoberfest Spam but is doc improvement

**Review by jcalcaben — APPROVED** [review]

**Review by larsroettig — APPROVED** [review]
Still kind of Hacktoberfest Spam but is doc improvement

**Comment by tjwiebell** [comment]
@mpchadwick - please sign the Adobe CLA when you get a chance, and we'll process this PR.

**Comment by mpchadwick** [comment]
@tjwiebell done

**Pull request merged**
