### PR TITLE
WIP: Refactoring Braintree

### PR DESCRIPTION
**Pull request by larsroettig**
## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

### Verification Steps

1. Go to the FOO page.
2. Verify the BAR shows up.
3. Make sure BAZ does a thing.

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by fooman** [comment]
Hey Lars, I know this is still all WIP but I wonder if the following architectural considerations should be done now. The current braintree implementation is very rigid as to how the checkout flow works. (ie shipping first). Would be great to get your views on how:

a.) the braintree payment method implementation could be achieved with less code
b.) to move some of the generic logic for checkout flow to peregrine/venia
c.) with a longer term goal to be able to easily support virtual checkouts (no shipping step), or checkouts with no review step, checkouts with additional steps (age verification), etc.

**Comment by larsroettig** [comment]
@fooman this pull request is mostly to discover gaps for missing targets. In this pull request I will clean up the credit payment to have a good example. How a service providers can implement a nice payment. Why do you think it is the wrong time todo it?

**Comment by sirugh** [comment]
@larsroettig do we still need this PR?

**Comment by larsroettig** [comment]
Yes I need this branch but will open new PR when #3103 is merged

**Pull request closed without merging**
