### PR TITLE
PWA-3216::upgarding node 14 to 18

### PR DESCRIPTION
**Pull request by glo82145**
## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by fooman** [comment]
this pr re-introduces package-lock.json again - please see https://github.com/magento/pwa-studio/issues/4203
I would suggest adding this to your .gitignore file

**Comment by glo82145** [comment]
run pr-test

**Comment by glo82145** [comment]
run pr-test

**Comment by glo82145** [comment]
run pr-test

**Pull request closed without merging**
