### PR TITLE
[fix]: Allow for region field path customization depending on form mutation requirements

### PR DESCRIPTION
**Pull request by sirugh**
## Description

The `createCustomerAddress` mutation requires different input for `region` depending on the `country`. If a country has `available_regions`, we should send the `region_id`. If it doesn't, we can send the raw text such as "Scotland".

To determine what to send, customize the field path depending on the form requirements.

An alternative approach was [here](https://github.com/magento/pwa-studio/pull/2658). Which required the customer form have handling for the form values to properly format the data.

## Related Issue

Closes [PWA-874](https://jira.corp.magento.com/browse/PWA-874).

### Verification Steps

 
**Auth Form Initial Entry**
1. Go to Venia storefront and create an new account or Sign in to account which does not have address.
2. Add product to cart and go to checkout page.
3. Enter shipping address for United Kngdom.
4. Click on Save button.

**Auth Form Edit**
1. Still signed in, edit the address you just submitted.
2. The entered region should still exist and you should be able to change it to another raw text input, like "England".
3. Save.

**Auth Form Add Additional w/ State**
1. Still signed in, add a new address, this time with United States.
2. You should be able to select a state, like "Texas".
3. Save and reopen. It should show "Texas"

**Auth Form Add Additional w/o State**
1. Still signed in, add a new address, this time with United Kingdom.
2. You should be able to enter a state like "Scotland"
3. Save and reopen. It should show "Scotland".

**Billing Address new entry**
1. As guest or auth, billing form should allow for custom entry (uncheck use shipping address as billing address).

**Billing Address new entry**
1. As guest or auth, billing form should allow for existing shipping address.
2. To verify this, with US/Texas as Shipping Address, add CC details (keeping the same as shipping box checked) and click "Review Order". It should work.
3. Then, refresh the page, and select UK/Scotland as shipping address, add CC details, (keeping the same as shipping box checked) and click "Review Order". It should work.

**Guest Address Add**
1. As a guest user on a new cart, add your shipping address w/ UK/Scotland. It should work.
2. Edit the address. See that Scotland is displayed in State field.
3. As a guest user on a new cart, add your shipping address w/ US/Texas. It should work.
4. Edit the address. See that Texas is displayed in State field.
 
**Estimate Shipping**
1. As guest, estimate shipping w/ US/Texas/78757 - it should work.
1. As guest, estimate shipping w/ UK/Scotland/78757 - it should work.

I tried to cover all the cases :D

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by fooman** [comment]
Any chance region/state can be made optional as part of this PR? Regions aren't widely used in New Zealand for example.

image

**Comment by sirugh** [comment]
>Any chance region/state can be made optional as part of this PR? Regions aren't widely used in New Zealand for example.

Is this a backend requirement that we can surface easily? Right now if you have "United States" selected and you try to submit without a region you'll get an error response. I wasn't sure what would happen to United Kingdom or New Zealand where there might not be any region codes/responses from the `getRegions` query.

Perhaps we can require region be submitted if `available_regions` contains values? What do you think?

**Comment by fooman** [comment]
not 100% sure how GraphQl integrates/surfaces these settings
image

but your suggestion of making it required when there are regions available would already improve this a lot.

**Comment by sirugh** [comment]
@fooman I opened https://github.com/magento/pwa-studio/issues/2666 to follow up. Addressing your concern may be more difficult than just checking whether there are regions configured as I believe some countries have regions but do not require them.

**Comment by dpatil-magento** [comment]
1. Guest/Auth User > Enter any address (US/UK) and have Billing same as shipping selected and click review order button >> Error - `Variable "$state" of required type "String!" was not provided.` in Billing (payment) accordion.

image


2. Login as Auth user (john.doe@example.com) >  Go to checkout > Edit Address > Again Edit Default address > Change country from USA to UK! OR even create a fresh account and try changing country on checkout page.
Error - Error toast appears. 

<a href="https://gyazo.com/26d0de5b976f415a96ce55739234371d">Image from Gyazo</a>

**Comment by dpatil-magento** [comment]
@sirugh Please check below observation -

3.  Billing Edit overlay (Place order screen) > Try edit billing address from USA to UK >> Region field showing pre-populated state value, which is not correct.   OR If your try to change from UK to USA then first state in list is being populated and on hitting Save button > It throws error.

US to UK
<a href="https://gyazo.com/3b8c56959d128d550c201bd149508634">Image from Gyazo</a>


UK to US
<a href="https://gyazo.com/754985021c8919fafbaf2aab5de6ddd7">Image from Gyazo</a>

**Comment by sirugh** [comment]
@dpatil-magento 

> Billing Edit overlay (Place order screen) > Try edit billing address from USA to UK >> Region field showing pre-populated state value, which is not correct.

Pretty sure this currently occurs on develop.pwa-venia.com. It is because when editing the address we provide `initialValues` which can include a region if previously entered. I do not think this is a bug.

> If your try to change from UK to USA then first state in list is being populated and on hitting Save button > It throws error.

This also occurs on develop. Can you create a bug ticket for these if you think they are worth opening tickets for?

**Review by tjwiebell — APPROVED** [review]

**Pull request merged**
