### PR TITLE
Merge main back to develop

### PR DESCRIPTION
**Pull request by dpatil-magento**
# ❗ DO NOT SQUASH MERGE THIS PR ❗ 

## Description
Merge 12.2 main back to develop

## Related Issue

Closes #ISSUE_NUMBER.

#### Test scenario(s) for direct fix/feature

1. Run cypress smoke test
2. Verify changes from `main` are in develop. 

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by sharkySharks** [comment]
run pr-deploy

**Review by itsyanik — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
Removed label as individual prs have the needed labels. If we add to this going to cause confusion when identify next release version bumps.

**Review by tjwiebell — DISMISSED** [review]
Shouldn't need the explicit `/index`, but not a blocker to approval.

**Comment by dpatil-magento** [comment]
QA Approved.

**Review by supernova-at — APPROVED** [review]

**Pull request merged**
