### PR TITLE
[feature]: Provide a way to access top/intermediate level categories through left nav

### LINKED ISSUE #2276: [feature]: Provide a way to access top/intermediate level categories through left nav
**Is your feature request related to a problem? Please describe.**
We can't go on the first level category when clicking on left navigation but we can go when we will click on home page categories

**Describe the solution you'd like**
Left side navigation first-level categories should redirect to a category

I have created Issue in https://github.com/magento/pwa-studio/issues/2274 but @sirugh suggestion please create feature request so I have created a feature request

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by huykon**
## Description
This PR will resolve problem could not click to parent category in left navigation

## Related Issue

Closes #2276.

### Verification Steps

1. Click to hamburger button near by left logo.
2. You will see the left menu, then click to **Bottoms** item.
3. Make sure **All Bottoms** appear on the top of list submenu.

## Screenshots / Screen Captures (if appropriate)
Screen Shot 2020-08-08 at 3 01 05 PM

## Checklist

- [x] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2615.pwa-venia.com : LH Performance Expected 0.85 Actual 0.34, LH Accessibility Expected 1 Actual 0.97, LH Best Practices Expected 1 Actual 0.93, WPT Cache Expected 90 Actual 39.333333333333
https://pr-2615.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.93
https://pr-2615.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.42, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.93, WPT Cache Expected 65 Actual 50

**Comment by tjwiebell** [comment]
@huykon It looks like you based your work on the branch from your first PR. Could you please create a new branch off mainline `develop` and cherry-pick the commit for this PR scope only?

**Comment by huykon** [comment]
@tjwiebell  I known that problem with my PR. But I developed my first PR into develop without create new branch so now I don't know how to get magento:develop code

**Comment by tjwiebell** [comment]
> @tjwiebell I known that problem with my PR. But I developed my first PR into develop without create new branch so now I don't know how to get magento:develop code

This is a common setup when working with your own fork; I'm going to assume your remote is named `origin`, but you can confirm by running `git remote -v`.

```
git remote add upstream https://github.com/magento/pwa-studio.git
git fetch upstream
git checkout -b <descriptive-branch-name> upstream/develop

# cherry pick and push
git cherry-pick d961fe9
git push -u origin <descriptive-branch-name>
```

**Comment by tjwiebell** [comment]
Closing in favor of #2616.

**Pull request closed without merging**
