### PR TITLE
run dev server on docker env

### LINKED ISSUE #1504: [bug]: Built in Docker container doesn't start a working server
**Describe the bug**
When a docker container is started from the provided script it doesn't start a healthy working website. After a successful build, the webserver instead of loading Venia returns Invalid Host header

**To Reproduce**
1. Go to `pwa-studio` root
2. Execute `bash docker/run-docker`
3. Wait for the image to build and for the dev server to start
4. Visit https://pwa-docker.localhost in browser. Instead of PWA, Invalid Host Header is shown

**Expected behavior**
I would expect Venia homepage to load.

**Additional context**
When the dev server is loaded it displays the following message:
```
PWADevServer ready at http://0.0.0.0:8080/
GraphQL Playground ready at http://0.0.0.0:8080/graphiql 
```
I would expect here the domain specified as a DEV_SERVER_HOST to show, but I might be wrong on this.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Ubuntu 18
 - Browser [e.g. Chrome, Safari]: Firefox
 - Browser Version [e.g. 22]: 68
 - Magento Version: MAGENTO_BACKEND_URL=https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/
 - PWA Studio Version: 3.0
 - NPM version `npm -v`: supplied from container
 - Node Version `node -v`: supplied from container

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

### PR DESCRIPTION
**Pull request by dpatil-magento**
## Description
docker dev-server is not working.

## Related Issue

Closes #1504 

## Verification Steps

Clone fresh repo and checkout `depatil/fix-docker-issue`
1. `bash docker/run-docker` should be successful and venia should be accessible at https://pwa-docker.localhost
2. `yarn watch:venia`  should be successful and venia should be accessible at https://magento-venia-concept-frnbw.local.pwadev:8745
3.  `yarn watch:all`  should be successful and venia should be accessible at https://magento-venia-concept-frnbw.local.pwadev:8745
4. `yarn stage:venia` should be successful and venia should be accessible at https://magento-venia-concept-frnbw.local.pwadev:9745/

### CODE REVIEW

**Comment by dpatil-magento** [comment]
@zetlen  I enabled `CUSTOM_ORIGIN_ENABLED=1` but Venia home page does not load. Same can be reproduced on local env also by passing `--https` falg `yarn watch:venia --https` .  With `CUSTOM_ORIGIN_ENABLED=0` get `Invalid Host Header `.  
Anything to do with changes in `webpack.config.js` ?   Same stuff works fine on `master` branch.

**Comment by dpatil-magento** [comment]
`Invalid host header` is gone after adding `disableHostCheck: true` to `PWADevServer.js`  But now started getting `ERR_CONNECTION_REFUSED`   ... WIP

**Comment by dpatil-magento** [comment]
Storefront loads now but says "insecure"....  WIP.

image

**Comment by cherdman** [comment]
On hold pending @zetlen 's review

**Comment by dpatil-magento** [comment]
@zetlen Looks much cleaner and passes all verification steps too.  I'm being namesake author now so cant approve my own PR. You can approve on my behalf and merge it.

**Pull request merged**
