### PR TITLE
[Fix bug]: Fix redirect error for sub-categories

### LINKED ISSUE #2860: [bug]: It gets stuck at loading when trying to open a sub-category that has been redirected
**Describe the bug**
It gets stuck at loading when trying to open a subcategory that has been redirected.
In the source code, it used history.replace() function but missing the "/" for params.

**To reproduce**
1. Login to admin panel
2. Go to "Marketing / SEO & Search / URL Rewrites"
3. Add an URL rewrite for a subcategory (use 301 or 302 redirect)
4. Go to front-page and clear the browser cache
5. Navigate to the subcategory
6. See error

**Expected behavior**
It should redirect to rewritten URL.

**Screenshots**
image

image

**Possible solutions**
Append "/" to the head of params will fix the error.

**Device information**
 - Device [PC]:
 - OS [Ubuntu 20.04, Windows 10]:
 - Browser [Chrome]:
 - Browser Version [86]:

**Packages this bug is in regards to**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by truongnx-dtn**
## Description
It gets stuck at loading when trying to open a subcategory that has been redirected.
In the source code, it used history.replace() function but missing the "/" for params.

### Possible solutions
Append "/" to the head of params will fix the error.

## Related Issue
Closes #2860.

### Verification Steps
1. Login to admin panel
2. Go to "Marketing / SEO & Search / URL Rewrites"
3. Add an URL rewrite for a subcategory (use 301 or 302 redirect)
4. Go to front-page and clear the browser cache
5. Navigate to the subcategory
6. Make sure the page does not stuck at loading screen.

## Screenshots / Screen Captures (if appropriate)
image

image

## Checklist
* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#2950: [Fix bug]: Fix redirect error for sub-categories

### CODE REVIEW

**Comment by truongnx-dtn** [comment]
closes #2860

**Comment by truongnx-dtn** [comment]
@magento run all tests

**Comment by truongnx-dtn** [comment]
@magento add version: Minor label

**Comment by truongnx-dtn** [comment]
@magento run all tests

**Comment by truongnx-dtn** [comment]
Could somebody help me? I don't have permission to add a version label.

**Comment by sirugh** [comment]
@magento create issue from PR

**Comment by tjwiebell** [comment]
@truongnx-dtn - We're getting around to processing this PR, which from first glance is straight forward and ready for QA. A couple things first:
1. Could you please sign the Adobe CLA?
2. Can you please rebase or merge in mainline and resolve these conflicts? Given our delay in processing is the reason these popped up, happy to do that for you, just let me know if you'd prefer we take that over.

**Comment by tjwiebell** [comment]
We're blocked from proceeding due to the CLA requirement. With no response, we will close the PR and leave the issue open for anyone who wants resolve and step through our contribution workflow requirements.

**Pull request closed without merging**
