### PR TITLE
Logo misses required alt property for image

### PR DESCRIPTION
**Pull request by jissereitsma**
In my installation, the Image component requires the `alt` property, but the `Logo` component does not render one.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3937: Logo misses required alt property for image

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by jissereitsma** [comment]
@dpatil-magento I've been sloppy in replies, but thanks for pursuing this issue and merging! :)

**Pull request merged**
