### PR TITLE
PWA#3051 Update to latest @adobe/magento-storefront-event-collector

### PR DESCRIPTION
**Pull request by RaghavendraTirumalasetti**
## Description

Once the newest package is released for `@adobe/magento-storefront-event-collector` we will need to update our dependencies.

## Related Issue

Closes #https://jira.corp.adobe.com/browse/PWA-3051

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by aniham — APPROVED** [review]

**Review by glo82145 — APPROVED** [review]

**Review by glo82145 — APPROVED** [review]

**Comment by glo42707** [comment]
run cypress

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
ru lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-desktop

**Pull request merged**
