### PR TITLE
fix block test

### PR DESCRIPTION
**Pull request by dpatil-magento**
## Description

Fix failing block and uncomment video background test.

## Related Issue

Closes https://jira.corp.magento.com/browse/PWA-2670

## Verification Steps

`run cypress` build should be green

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run cypress

**Comment by sharkySharks** [comment]
run lighthouse-desktop

**Comment by sharkySharks** [comment]
run lighthouse-mobile

**Comment by sharkySharks** [comment]
run lighthouse-desktop

**Comment by sharkySharks** [comment]
run lighthouse-mobile

**Comment by sharkySharks** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
Passed builds -  https://us-east-1.console.aws.amazon.com/codesuite/codebuild/913454440186/projects/pwa-cypress-tests/build/pwa-cypress-tests%3A4038544a-efb5-4a93-beeb-055d80b41632/?region=us-east-1
https://us-east-1.console.aws.amazon.com/codesuite/codebuild/913454440186/projects/pwa-cypress-tests/build/pwa-cypress-tests%3A0a591cb1-8134-488b-ab40-2d189e8895de/?region=us-east-1

**Comment by dpatil-magento** [comment]
run cypress

**Review by ericeoeur — APPROVED** [review]
LGTM. QA passed.

**Pull request merged**
