### PR TITLE
Update webpack to WebpackTools

### PR DESCRIPTION
**Pull request by nagarajsuperbotics**
## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

#### Test scenario(s) for direct fix/feature
Example
-   Verify user is able to apply filters on category page
-   Verify user is able to apply filters on search page

#### Test scenario(s) for any existing impacted features/areas
Example
-   Verify user is able to sort data after applying filters on category page
-   Verify user is able to sort data after applying filters on search page

#### Test scenario(s) for any Magento Backend Supported Configurations
Example
- Update default Sort value in backend and repeat above scenarios

#### Is Browser/Device testing needed?
Example
- Yes, browser testing is needed as X UI component may be impacted on <browser>
- Yes, device testing is needed as X UI component may be impacted on <mobile|desktop|etc>

#### Any ad-hoc/edge case scenarios that need to be considered?
Example
- Apply all filters to get 0 results and then remove filters to see respective products 

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3302: Update webpack to WebpackTools

### CODE REVIEW

**Comment by supernova-at** [comment]
@magento create issue

**Comment by supernova-at** [comment]
Hi @nagarajsuperbotics , to expedite the review of this PR could you please fill out the PR template for us?

Thanks!

**Comment by larsroettig** [comment]
:heavy_check_mark: LGTM is only docs a very valid point we only export `WebpackTools`

**Comment by tjwiebell** [comment]
@nagarajsuperbotics - when you get a chance, could you please sign the Adobe CLA linked in the list of checks?

**Comment by tjwiebell** [comment]
@nagarajsuperbotics - last call for CLA, we're unable to merge and accredit your submission without the CLA signed. This PR will be auto-closed at 9AM CDT tomorrow if we do not hear back. Thanks.

**Pull request closed without merging**
