### PR TITLE
PWA-2094: Track product impressions and clicks

### PR DESCRIPTION
**Pull request by michaelyu0123**
## Description

Overview
As a merchant, I want to be able to track product impressions and product clicks on my store.

## Related Issue

Closes #PWA-2094

## Verification Steps

Preconditions:
Framework with a example extension created

Acceptance Criteria:
1. Product impression event is tracked when a user views a product tile (category listing page, search results page, PageBuilder content) and clicks a product tile
the following attributes collected with ProductImpessionEvent:
	1.SKU
	2.name
	3.priceTotal
	4.discountAmount
	5.currencyCode
	6.selectedOptions ( attribute, value)
2.Product impressions and views are tracked without a performance degradation 
3.User scrolling the page is 60 fps 
4.Example extension subscribes to the events and has events available for processing 

#### Test scenario(s) for direct fix/feature

Test Plan
Home Page:
1.Navigate to the home page
2.Scroll down to Page Builder "Top Sellers" product widgets at the bottom of the page
3.Open browser console and verify that the sample extension logged the product impression event for each visible product (with its contextual data)
4.Click on one of these products to navigate to the product detail page
5.Open browser console and verify that the sample extension logged the product click event for that product (with its contextual data)

Category / Product Listing Page:
1.Navigate to a category / product listing page
2.Open browser console and verify that the sample extension logged the product impression event for each visible product (with its contextual data)
3.Scroll down or paginate so that new products become visible
4.Open browser console and verify that the sample extension logged the product impression event for each newly visible product (with its contextual data)
5.Click on one of these products to navigate to the product detail page (check for simple and configurable products)
6.Open browser console and verify that the sample extension logged the product click event for that product (with its contextual data)

Search Page:
1.Start typing in the search box in the header until you get some product suggestions
2.Open browser console and verify that the sample extension logged the product impression event for each product suggestion (with its contextual data)
3.Execute the search and wait to be redirected to the search results page
4.Open browser console and verify that the sample extension logged the product impression event for each product visible on the search results page (with its contextual data)
5.Click on one of these products to navigate to the product detail page
6.Open browser console and verify that the sample extension logged the product click event for that product (with its contextual data)

Test Coverage:
Add cypress integration test with mock data

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by haal9000** [comment]
run scaffold-pwa

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run all tests

**Comment by eug123** [comment]
@michaelyu0123
Looks good to me, the only minor thing is `beacon` naming for integration test, maybe it is better to use something like `eventing` or `events`.

Thank you

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
> @michaelyu0123 Looks good to me, the only minor thing is `beacon` naming for integration test, maybe it is better to use something like `eventing` or `events`.
> 
> Thank you

beacon has been renamed to 'eventing'

**Review by eug123 — APPROVED** [review]

**Comment by dpatil-magento** [comment]
@michaelyu0123 Please take a look on following observations - 
1. `name` attribute is not collected but its mentioned in AC.

image

2. AC says products should be tracked only once on page level but when I remove filter same products trackaed again. May be because URL changes?

<a href="https://gyazo.com/259f1b66a1ae93d39644d416d67856c9">Image from Gyazo</a>

3. After search for string user is on search results page. Now if user clicks on page 2 using pagination icon then >> Search suggestion products impression tracked again.

<a href="https://gyazo.com/315395ceeb0971193696ba05d8061627">Image from Gyazo</a>

4. On mobile view >> 3 products are tracked instead of visible 2. 

<a href="https://gyazo.com/dbb625fd27bdc26adb8125685bff4bba">Image from Gyazo</a>

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
@dpatil-magento resolved aforementioned observations.
1. name attribute has been added.
2.You are right, it will dispatch again since it is technically a new query. However I added condition to not dispatch if a product is already dispatched and after the new query it didn't re-render the product (on cases you such as the one you displayed).
3. I added a setTimeout of 500ms so if the product didn't intersect for at least 500ms it won't dispatch.
4. Updated the threshold so it should dispatch correctly.
5. Same as 3.

**Comment by michaelyu0123** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Approved.

**Review by dpatil-magento — APPROVED** [review]

**Pull request merged**
