### PR TITLE
Fix missing projectConfig in create-custom-origin

### LINKED ISSUE #2898: [bug]: yarn buildpack create-custom-origin . errors
**Describe the bug**
`yarn buildpack create-custom-origin .`  produces error 

```
➜  pwa-frontend git:(main) yarn buildpack create-custom-origin .
yarn run v1.22.10
$ buildpack create-custom-origin .
  ⓧ  projectConfig.section is not a function
  ⓧ  Error: projectConfig.section is not a function
error Command failed with exit code 1.
```

**To reproduce**
1. latest develop
2. run scaffold command
3. remove @magento/venia-sample-backends package
4. run  `yarn buildpack create-custom-origin . `

**Expected behavior**
custom origin created

**Screenshots**
see #2897

**Additional context**

**Possible solutions**
see #2897

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

### PR DESCRIPTION
**Pull request by fooman**
## Description

#2853 made loading the environment async. Needs an await for `yarn buildpack create-custom-origin .`

## Related Issue

Closes #2898

### Verification Stakeholders
@revanth0212 
### Verification Steps

1. latest develop
2. run scaffold command
3. remove @magento/venia-sample-backends package
4. run  `yarn buildpack create-custom-origin . `

## Screenshots / Screen Captures (if appropriate)

image

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by sirugh** [comment]
@fooman nice catch. Mind updating the references in the doc [here](https://github.com/magento/pwa-studio/blob/develop/pwa-devdocs/src/pwa-buildpack/reference/buildpack-cli/load-env/index.md) and [here](https://github.com/magento/pwa-studio/blob/develop/pwa-devdocs/src/pwa-buildpack/configuration-management/index.md)?

**Comment by fooman** [comment]
@sirugh okay have updated the examples too

**Review by sirugh — APPROVED** [review]
Thanks!

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
