### PR TITLE
#2804 :- Add "maskable icon" to Venia for Google Lighthouse [PWA]

### PR DESCRIPTION
**Pull request by konarshankar07**
## Description

This PR will add the maskable icon

## Related Issue

Closes https://github.com/magento/pwa-studio/issues/2804

### Verification Steps

1. On an Android device, go to develop.pwa-venia.com on chrome and in the top right menu select "add to home page".
2. Now go to [this PR](pr-2818.pwa-venia.com) and do the same.
3. Compare the icons on the home page, they should look identical.
4. Run lighthouse against this PR, it should not have the "maskable icon" warning.

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by sirugh — APPROVED** [review]
Thanks! This adds a maskable icon to the icons array, as required by the [lighthouse docs](https://web.dev/maskable-icon-audit/?utm_source=lighthouse&utm_medium=devtools).

Could you clarify why we needed the specific 278x278 size? @larsroettig maybe you know since you uploaded the asset on the issue :)

**Comment by sirugh** [comment]
I've been trying to produce a 512x512 image for us to use here but the maskable.app editor and what chrome displays seem to not be aligned... frustrating :P



[Image from Gyazo](https://gyazo.com/f81f2e43d34eeed9ff1ddbf9f6a1dcd1)

**Comment by dpatil-magento** [comment]
Left one is `develop` and right one is this pr, looks better. 

image

**Comment by dpatil-magento** [comment]
QA Approved

**Review by supernova-at — APPROVED** [review]

**Pull request merged**
