### PR TITLE
PWA-1555: cypress test to verify row

### PR DESCRIPTION
**Pull request by pankhurigoel**
## Description

To verify that the Page Builder Row content type renders correctly on Venia for each content type property.

## Related Issue

Closes [PWA-1555](https://jira.corp.magento.com/browse/PWA-1555): Verify Row

## Verification Steps

- Go to venia-integration-test dir
- Run yarn install
- Run yarn test
- Run row.spec.js from cypress ui
- Cypress row.spec.js should pass

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]
LGTM

**Comment by mikhaelbois** [comment]
Snapshots were generated with a width of 1200px instead of the configured 1440px.
They should be created again with the right width.
Capture d’écran, le 2021-08-10 à 10 39 32

Also, having screen captures of video elements makes them hard to be validated.
Most of the time, Cypress will say they are different since the visual is different every time we run a test.
image
image

Maybe using a video with a fixed visual could help?

**Comment by mikhaelbois** [comment]
Also, you can create the snapshots in the right format by running the test in headless.
First remove the snapshots and run the following:
`yarn test:headless --spec src/tests/integrationTests/pageBuilder/row.spec.js`

**Comment by mikhaelbois** [comment]
Initial code updated by myself and in need of a revised review.

**Review by michaelyu0123 — APPROVED** [review]
LGTM

**Review by larsroettig — APPROVED** [review]
LGTM

**Pull request merged**
