### PR TITLE
[PWA-2174] Dynamic Blocks GraphQL returns non-qualified blocks

### LINKED ISSUE #3418: [bug]: Dynamic Blocks GraphQL returns non-qualified blocks
**Describe the bug**

2.4.3 Introduced a new GraphQL query for Dynamic Blocks (https://devdocs.magento.com/guides/v2.4/graphql/queries/dynamic-blocks.html) which should return matching configured Dynamic Blocks for a customer. Dynamic blocks can be configured in several ways for eligibility including:

- Customer Segment (guest, registered or other configured attributes)
- Related Promotions (Cart Price Rule or Catalog Price Rule)

When a dynamic block is configured to match a specific cart price rule in Luma it is not returned in the /banner/ ajax call if the cart does not match the price rule qualifying logic. The GraphQL implementation returns these dynamic blocks regardless of qualified carts meaning incorrect banners could be shown to customers.

**To reproduce**

1. Create new Cart Price Rule (eg: Free Shipping > $50, such as the default sample data rule)
1. Create a new Dynamic Block matching all segments, specify matching Cart Price Rule
1. Load Luma instance and inspect /banner/ response, dynamic block is not returned
1. Execute GraphQL query, dynamic block is returned

Below responses show dynamic block with content "YOU QUALIFY FOR FREE SHIPPING".

**Luma /banner/ response:**
{{{"data":{"items":{"salesrule":<],"catalogrule":[],"fixed":{"1":{"content":"[style]#html-body [data-pb-style=HGFQ01F]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"HGFQ01F\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Test 1[\/h2][\/div][\/div]","types":["content"],"id":"1"},"4":{"content":"[style]#html-body [data-pb-style=S1HHDNR]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"S1HHDNR\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Welcome, sign up to win big![\/h2][\/div][\/div]","types":["content"],"id":"4"},"5":{"content":"[style]#html-body [data-pb-style=L4AIVX7]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"L4AIVX7\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Win big this month[\/h2][\/div][\/div]","types":["header"],"id":"5"}}},"store_id":"1"}}}}

**GraphQL Response**
{{{
    "data": {
        "dynamicBlocks": {
            "items": [
                {
                    "uid": "MQ==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=HGFQ01F]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"HGFQ01F\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Test 1[/h2][/div][/div]"
                    }
                },
                {
                    "uid": "Mg==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=G0W9HMJ]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"G0W9HMJ\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]YOU QUALIFY FOR FREE SHIPPING!@[/h2][/div][/div]"
                    }
                },
                {
                    "uid": "NA==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=S1HHDNR]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"S1HHDNR\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Welcome, sign up to win big![/h2][/div][/div]"
                    }
                },
                {
                    "uid": "NQ==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=L4AIVX7]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"L4AIVX7\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Win big this month[/h2][/div][/div]"
                    }
                }
            ],
            "page_info": {
                "page_size": 20,
                "current_page": 1,
                "total_pages": 1
            },
            "total_count": 4
        }
    }
}}}

**Example GraphQL query:**
{{{
  dynamicBlocks(
    input: { type: SPECIFIED, locations: [CONTENT, HEADER>}
  ) {
    items {
        uid,
        content {
            html
        }
    },
    page_info {
        page_size,
        current_page,
        total_pages
    }
    total_count
  }
}}}

**Expected behavior**

Only qualified dynamic blocks should be returned to GraphQL queries.

**Screenshots**

Screenshot 2021-09-16 104727

Screenshot 2021-09-16 105617

Screenshot 2021-09-16 105642

**Please let us know what packages this bug is in regards to:**

-   < ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

**Test Plan**  Assuming we are dealing only with Graphql and not Luma.
* Have pre-condition setup and verify graphql response is correct.
* If Venia starts supporting dynamic blocks then test this on Venia UI as well.

### PR DESCRIPTION
**Pull request by mikhaelbois**
## Description

Refetch Dynamic Blocks when specific Cart conditions are updated.
Show relevant Dynamic Blocks matching Catalog Price Rules if Product UID is provided.
This PR requires the backend work from https://github.com/magento-commerce/magento2-pwa-commerce/pull/3.

## Related Issue

Closes #3418.

#### Test scenario(s) for direct fix/feature

Install PWA Commerce meta package with PR https://github.com/magento-commerce/magento2-pwa-commerce/pull/3.
1. Create new Cart Rule
2. Link Dynamic Block to rule
3. Add Dynamic Block to Category description via Page Build component
4. On frontend the Dynamic Block should only be shown when Cart Rule applies

Make sure to test possible Cart conditions:
- Subtotal (Excl. Tax)
- Subtotal (Incl. Tax)
- Subtotal
- Total Items Quantity
- Total Weight
- Payment Method
- Shipping Method
- Shipping Postcode
- Shipping Region
- Shipping State/Province
- Shipping Country

Test Catalog Price Rules on Simple Product Page.
1. Create new Catalog Price Rule
2. Link Dynamic Block to rule
3. Add Dynamic Block to a **Simple Product** description via Page Build component
4. On frontend the Dynamic Block should only be shown when Catalog Price Rule applies

#### Any ad-hoc/edge case scenarios that need to be considered?

- Test Cart conditions update on page where Dynamic Block is present
- Test Cart conditions update on page where Dynamic Block is not present

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by michaelyu0123 — DISMISSED** [review]

**Comment by mikhaelbois** [comment]
@ericeoeur 
 - Field cart_id is not defined by type DynamicBlocksFilterInput.
 - Field product_uid is not defined by type DynamicBlocksFilterInput.

I did have to fix something but without the code from my backend PR, this will continue to fail.
I suggest your validate the queries on a project connected to a backend with https://github.com/magento-commerce/magento2-pwa-commerce/pull/3.

**Comment by dpatil-magento** [comment]
run cypress

**Comment by ericeoeur** [comment]
run cypress

**Comment by ericeoeur** [comment]
@mikhaelbois , most of the QA passed for this ticket minus the following scenarios:

**CART CONDITIONS** 

- [ ] Weight - A 20lb cart rule was created: for a total cart containing 20lbs or more, include a discount and a dynamic block. While the total products did exceed 20lbs and the discount was available at checkout, the dynamic block did not appear. 
- [ ] Payment Method - Dynamic block appears when the user selects "Credit Card" as their payment method. However, the discount (-$5 order in this case) was not applied, even at the end of checkout. 

**CATALOG PRICE RULES**

- [ ] Style Category - The rule "Styles containing LONG SLEEVE" was created. However, the dynamic block did not appear despite the rule being active. 

Please let me know of any further questions, thanks!

**Comment by mikhaelbois** [comment]
@ericeoeur 
- Cart Conditions - Weight issues. Luma behave weirdly too. Seems like a backend bug.
Created https://jira.corp.magento.com/browse/PWA-2597 to follow-up.
- Cart Conditions - Payment Method - Might be a GraphQl issue. On Luma, the rule is only applied in the checkout.
Created https://jira.corp.magento.com/browse/PWA-2598 to follow-up.
- Catalog Conditions - Following our discussion, do you mind trying again using a Dynamic Block linked to a Simple Product?

**Comment by ericeoeur** [comment]
@mikhaelbois 

Thanks for making the two tickets for the weight and payment method issues. The simple product tests have been re-done and they are all passing QA ✅

**Review by michaelyu0123 — APPROVED** [review]

**Pull request merged**
