### PR TITLE
PWA-2783: Track Search Requests

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Added search event dispatch
- Added test for change

## Description

Overview

As a merchant, I want to be able to track search requests closely to monitor users behavior.

Preconditions
Framework with a example extension created
Acceptance Criteria
1. SearchRequestSent event is tracked every time user initiates a product search with the attributes that can be mapped to the following schema

refinements: (attribute: string; value: string; isRange: boolean )
sort (attribute: string; order: string )
query: string;
2. Example extension subscribes to the events and has events available for processing

Example extension simply subscribes to event and logs its occurrence

## Related Issue

Closes #PWA-2783

#### Test scenario(s) for direct fix/feature

Test plan
1. Perform a product search
2. Open browser console and verify that the sample extension logged the search request event (with its contextual data)
3. Refine the search using one of the available attributes
4. Open browser console and verify that the sample extension logged the search request event with the refinement data
5. Sort the search results
6. Open browser console and verify that the sample extension logged the search request event with the sort data

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run scaffold-pwa

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Review by jcalcaben — DISMISSED** [review]

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
@michaelyu0123
Looks good to me, the only issue is that `SEARCH_REQUEST` event is firing twice when submitting

**Comment by michaelyu0123** [comment]
> @michaelyu0123 Looks good to me, the only issue is that `SEARCH_REQUEST` event is firing twice when submitting

@eug123 that is caused by the history being modified to include page as a query param which caused a re-render. I just made it so if the query lacks the page in the query param it will skip the re-render & query.

**Comment by michaelyu0123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run lighthouse-desktop

**Comment by michaelyu0123** [comment]
run lighthouse-mobile

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
QA passed

**Pull request merged**
