### PR TITLE
PWA-3227::yarn install broken after #4191

### PR DESCRIPTION
**Pull request by glo80771**
## Description

yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

To reproduce

run yarn install
Expected behavior

no error

## Related Issue

https://jira.corp.adobe.com/browse/PWA-3227.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-desktop

**Review by dpatil-magento — DISMISSED** [review]
Dummy approval to test ability to merge

**Pull request merged**
