### PR TITLE
PWA-2571: Regression fix disabled TTL support in BrowserPersistence

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Reverted ttl support for getItem

## Description

Problem
A user auth bug was fixed in v11.0.0 regression, but it appears to have removed support for an important feature for TTL support of entries. While this may have solved the bug, this utility is public API, and anyone else who was using it expecting items to expire now have large stale caches for their shoppers.

Introduced by: https://github.com/magento/pwa-studio/pull/3306/files#diff-44b7b17ad1392c88b1e3411c80f7378782e6a568d280b68a48349061293b604cL51-L54

Acceptance Criteria
TTL is restored as supported in BrowserPersistence
No regressions related to the user auth bug this intended to fix

## Related Issue

Closes #PWA-2571

## Verification Steps

Test Execution
Verify https://github.com/magento/pwa-studio/pull/3306. still works
Verify TTL support works as expected. Browser stale cache should expire.
Verify above 2 scenarios in all supported browsers and devices.
Verify apollo does not store any sensitive data after user session logout
Verify above scenario in both DEfault. and French store
Cypress Test coverage -
Changes should be covered in unit test level. No cypress unless unit test does not support this kind of scenario to test.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run scaffold-pwa

**Comment by michaelyu0123** [comment]
run cypress

**Review by anthoula — DISMISSED** [review]

**Comment by tjwiebell** [comment]
run cypress

**Comment by tjwiebell** [comment]
run lighthouse-desktop

**Comment by tjwiebell** [comment]
❓ Verify https://github.com/magento/pwa-studio/pull/3306. still works
✅ Verify TTL support works as expected. Browser stale cache should expire.
✅ Verify above 2 scenarios in all supported browsers and devices.
❌ Verify apollo does not store any sensitive data after user session logout
✅ Verify above scenario in both DEfault. and French store

@michaelyu0123 Found one scenario where sensitive data is kept around, so some of this original bug may have resurfaced. Simulated a shopper returning to the site with an expired auth token in local storage (edit the ttl), `customer` data still there. Problem does not exist when letting the timer remove the token, so race condition likely.

Screen Shot 2022-03-10 at 1 29 21 PM

**Comment by michaelyu0123** [comment]
@tjwiebell  yes you are correct, it is mainly due to the reducer fetching the initial state call which also attempts to get the signin_token which removed the signin_token before user components useEffect has a chance to fetch it which in turn caused it to not run a async logout event that flushes customer information. I have modified the initial state fetching to just call the get item on signin_token with none ttl checking method to let the user component get a chance to handle it properly. Perhaps need a separate workflow for the login ttl in the future since it has to be handled differently.

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run lighthouse-mobile

**Comment by tjwiebell** [comment]
run lighthouse-desktop

**Comment by tjwiebell** [comment]
run lighthouse-mobile

**Comment by tjwiebell** [comment]
✅  QA Passed

Ready to merge after review of [0c7fd5c](https://github.com/magento/pwa-studio/pull/3729/commits/0c7fd5ccfe6112bc4d521e393566e411133be7f7).

**Review by tjwiebell — APPROVED** [review]

**Comment by tjwiebell** [comment]
run lighthouse-mobile

**Comment by tjwiebell** [comment]
`lighthouse-mobile` scores are within range of develop.pwa-venia.com, @dpatil-magento will merge.

**Pull request merged**
