### PR TITLE
[PWA-3034] lighthouse mobile home page accessibility scored reduced to 98

### PR DESCRIPTION
**Pull request by anthoula**
## Description

- Add aria label to carousel gallery item links, so Lighthouse Accessibility reaches 100
- fix console warning for tabIndex

## Related Issue

Closes [PWA-3034](https://jira.corp.adobe.com/browse/PWA-3034).
Closes [PWA-2995](https://jira.corp.adobe.com/browse/PWA-2995).

### Verification Stakeholders

@dpatil-magento 

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run cypress

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
QA Approved

**Review by jcalcaben — APPROVED** [review]

**Pull request merged**
