### PR TITLE
Remove all pwastudio.io documentation links

### PR DESCRIPTION
**Pull request by bdenham**
## Description

Replaced all links to `pwastudio.io` with the appropriate link+anchor in `developer.adobe.com/commerce/pwa-studio`.

## Related Issue

Jira issue [PWA-3011](https://jira.corp.adobe.com/browse/PWA-3011). 

Olena contacted Anthoula and I to update the old `pwastudio.io` link on the [peregrine npm registry page](https://www.npmjs.com/package/@magento/peregrine) as reported. I found more references on [other npm registry pages](https://www.npmjs.com/package/@magento/pwa-buildpack) and throughout the source-code documentation. So it was time to purge these old links permanently.

## Staged preview

[STAGED PREVIEW](https://developer-stage.adobe.com/commerce/pwa-studio) — for spot checks on removal of old pwastudio.io links. 

## Blockers / Contingencies

Someone with access to the `@magento` org account on the npm registry site needs to change the descriptions on the site to match the updates this PR makes to the README.md files of these packages:
- @magento/peregrine: https://www.npmjs.com/package/@magento/peregrine
- @magento/pwa-buildpack: https://www.npmjs.com/package/@magento/pwa-buildpack
- @magento/venia-concept: https://www.npmjs.com/package/@magento/venia-concept
- @magento/babel-preset-peregrine: https://www.npmjs.com/package/@magento/babel-preset-peregrine

OR — If we plan to update those packages for this release, make sure this PR is merged first so the descriptions on the npm pages will auto-update based on the README.md files of each package. 

Closes #PWA-3011.

## Acceptance
- @jcalcaben 
- @tkacheva 
- @anthoula 

### Verification Stakeholders

- @tkacheva 
- @anthoula 

## Verification Steps

Make sure the documentation links on the following npm registry pages resolve to the PWA Studio docs:
- @magento/peregrine: https://www.npmjs.com/package/@magento/peregrine
- @magento/pwa-buildpack: https://www.npmjs.com/package/@magento/pwa-buildpack
- @magento/venia-concept: https://www.npmjs.com/package/@magento/venia-concept
- @magento/babel-preset-peregrine: https://www.npmjs.com/package/@magento/babel-preset-peregrine

IMG_6916

### CODE REVIEW

**Comment by bdenham** [comment]
The staged preview API Reference topics should no longer have any old pwastudio.io links. You can spot check the various topics here: http://developer-stage.adobe.com/commerce/pwa-studio/api/buildpack

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run pr-test

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
