### PR TITLE
PWA-2390: Newsletter form displays two errors

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Updated newsletter.js to clear error on submit button click
- Added test coverage

## Description

As a user, I would like to see one clear error message indicating what is wrong

### Steps to Reproduce
Submit form with an invalid email address (missing `@`)
Empty email field and try to submit again
### Expected
 One error message is displayed at a time
### Actual
 Two error messages are displayed at a time
### Test Plan
Follow the reproduction steps above and verify that only one error message is shown at a time.

## Related Issue

Closes PWA-2390

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
The error test is handled by integration test instead. So coverall build is fine.

**Review by jcalcaben — COMMENTED** [review]
Code looks good, but I notice the error message switches from top to bottom. Should we get approval from UX?

**Review by jcalcaben — APPROVED** [review]

**Comment by dpatil-magento** [comment]
@michaelyu0123  

> The error test is handled by integration test instead. So coverall build is fine.

Thanks for adding cypress but unlike core, we dont add UI test case for error flows unless its P0/P1 ticket. It would be nice if you can just convert this test to check positive flow. Just enter a valid email and check for success message.  
PS - This feature was added by community to actual success case cypress test is missing.

**Comment by dpatil-magento** [comment]
@michaelyu0123  

> The error test is handled by integration test instead. So coverall build is fine.

Thanks for adding cypress but unlike core, we dont add UI test case for error flows unless its P0/P1 ticket. It would be nice if you can just convert this test to check positive flow. Just enter a valid email and check for success message.  
PS - This feature was added by community to actual success case cypress test is missing.

**Comment by dpatil-magento** [comment]
> The error test is handled by integration test instead. So coverall build is fine.
> 
> Thanks for adding cypress but unlike core, we dont add UI test case for error flows unless its P0/P1 ticket. It would be nice if you can just convert this test to check positive flow. Just enter a valid email and check for success message.
> PS - This feature was added by community so actual success case cypress test is missing.

Positive case is already covered `packages/peregrine/lib/talons/Newsletter/__tests__/useNewsletter.spec.js` so given we need to interact with text field and button/link once, we are going ahead with current cypress test.

**Comment by dpatil-magento** [comment]
Cypress test pass  locally `All specs passed!                        38:44       76       76`

**Comment by dpatil-magento** [comment]
QA Approved

**Pull request merged**
