### PR TITLE
#1913: standardize GQL files with 4-space indentation

### LINKED ISSUE #1913: [bug]: standardize GQL spacing
**Describe the bug**
In `.graphql` files some use 2-space not 4-space indentation.

**Expected behavior**
All GQL files use 4-space indentation.

**Screenshots**

**Additional context**
The Prettier config doesn't seem to apply to this file type.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by brendanfalkowski**
## Description

- Use 4-space indentation for all `.graphql` files.
- Add `.graphql` files to Prettier coverage.

## Related Issue
Closes #1913.

### Notes

I added modified `package.json` in both these repo packages to include GQL in Prettier:

- {root}/package.json
- {root}/packages/venia-concept/package.json

### Verification Steps

1. Build should pass.

## Checklist

* I have updated the documentation accordingly, if necessary.
* I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by sirugh** [comment]
Is there a `prettier` equivalent to graphql files? If there's a rule for this maybe we can set it as part of this changeset. If not, NBD, this is fine :)

**Comment by brendanfalkowski** [comment]
PWA Studio uses Prettier ~1.16, and this announcement says GQL is supported since 1.5:
https://blog.apollographql.com/graphql-just-got-a-whole-lot-prettier-7701d4675f42

I tested adding `.graphql` files to the NPM scripts for Prettier, but this hits some issues in `packages/upward-spec` that didn't look like legit issues. It also didn't enforce the 4-space rule from PWA Studio's Prettier config, so I didn't bother testing it further.

See my comment here with a screenshot of the warnings it found: https://github.com/magento/pwa-studio/issues/1913#issuecomment-544011448

**Comment by sirugh** [comment]
> It also didn't enforce the 4-space rule from PWA Studio's Prettier config, so I didn't bother testing it further.

I think you should give it a shot! [The playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBHArnATgTwAQDmcMAgujABYRYAUAJAIblVYCSAJkngHLoC2AI2wBCAJR5gAHSh5ZeJpWo0AlpzyNm1DuKky5+gGbKsAZxjcGfONP23bAGwZmLVm3bwDlEN7IC+0-ygQABoQCAAHGC8oE2RQBiwsCAB3AAUEhFiUBgA3CFUQkAEsBjAAa2IAZXDS5SgCZBgsTFCKGD57AHUKZXgTGrA4Ssze5RzenGRwE1jQupNsGFSSgj4GZAMGewXQgCsTAA8AIRLyqss4ABk6uA2tnZB9g8q6gns4AEV0CHg77bhQjVTNgpgQSuEKKh7IVwlg6jBOqpKMgABwABkBSQWnXBU1hcAWWByt1CGB+cGWESyICcAFooHA4OwmYUsHAMMYKSs1n8Hgs+MpGs0ASATK93l9ybyRTAGAJEexkUgAEyhJoMZT2V4AYQgfB5KCg0BJIHQCwAKnKspt-r5fEA) looks to auto-indent for us if we set `--tab-width` to `2`. Also, I think the issues in the graphql files are legitimate. The `getAuthor` and `getArticle` queries are enclosed in brackets, which is incorrect syntax. The `articles-and-authors-schema` is missing a type for an argument. Maybe `prettier` wasn't able to get to the auto-fix part of running since it encountered errors.

**Comment by brendanfalkowski** [comment]
D'oh, guess I didn't look close enough. The console output looked normal at first glance but I didn't see those extra curly brackets. Does seem to be working. Getting that branch updated now.

**Comment by brendanfalkowski** [comment]
@sirugh — Fixed those up, so GQL files should be all covered + standardized by Prettier now.

**Pull request merged**
