### PR TITLE
Backmerge/8.0

### PR DESCRIPTION
**Pull request by sirugh**
# ❗ DO NOT SQUASH MERGE THIS PR ❗ 

## Description

Backmerged `release/8.0` into `develop`. Only merge conflicts were three files (added change to en_us.json too)

## Related Issue

Closes [PWA-964](https://jira.corp.magento.com/browse/PWA-964).

### Verification Steps

1. Double check that conflicts were resolved.

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by revanth0212 — APPROVED** [review]
Perfect. Looks nice 👍

**Comment by supernova-at** [comment]
I don't see `useAccountMenuItems` in the change list.

**Comment by sirugh** [comment]
> I don't see useAccountMenuItems in the change list.

Did not accept release changes. Was commented out.

**Review by jimbo — APPROVED** [review]

**Comment by dpatil-magento** [comment]
@sirugh I think we should not be merging `package.json` version changes. referring to https://github.com/magento/pwa-studio/pull/2538

Rest all looks good.

cc @tjwiebell

**Comment by tjwiebell** [comment]
> @sirugh I think we should not be merging `package.json` version changes. referring to #2538
> 
> Rest all looks good.
> 
> cc @tjwiebell

Discussed with @sirugh about our preference not to merge pre-release version bumps into develop, which isn't grounded any known issues. No need to block this PR, and we can discuss further if that needs to be enforced in the future. Merge it @dpatil-magento 👍

**Pull request merged**
