### PR TITLE
AC-6477-There's no message to inform the user the page refreshed its …

### PR DESCRIPTION
**Pull request by glo82145**
…content by clicking/pressing one of the buttons.

## Description

There's no message to inform the user the page refreshed its content by clicking/pressing one of the buttons.

## Related Issue

Closes https://jira.corp.adobe.com/browse/AC-6477

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3992: AC-6477-There's no message to inform the user the page refreshed its …

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — CHANGES_REQUESTED** [review]
Hi @glo82145 - Thanks for looking at this. Would you run `yarn prettier` so that the linter check will pass for this PR? Thank you

**Comment by glo82145** [comment]
> Hi @glo82145 - Thanks for looking at this. Would you run `yarn prettier` so that the linter check will pass for this PR? Thank you

@anthoula Its done

**Comment by anthoula** [comment]
run cypress

**Comment by anthoula** [comment]
run lighthouse desktop

**Comment by anthoula** [comment]
run lighthouse mobile

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved, cypress failure unrelated.

**Pull request merged**
