### PR TITLE
[PWA-984] - Migrate CheckoutPage graphql operations to peregrine

### PR DESCRIPTION
**Pull request by pedrochiossi**
### Changes
This PR moves all `.gql` files that are in CheckoutPage components to their corresponding talons in `@magento/peregrine`. 

## Related Issue

Closes PWA-984

## Verification Steps

- Checkout page .gql.js files are moved to Peregrine and no longer reside in Venia
- The Checkout page functions as expected
- Signing in on the Checkout page merges carts correctly
#### Test scenario(s) for direct fix/feature

1. Verify that you can checkout successfully as a guest user
2. Verify that you can checkout successfully as an authorized user
3. Verify that you can come to the checkout page as a guest user, "sign in for express checkout", and that your carts are merged correctly and you can check out successfully

## Checklist

- [x]   I have added tests to cover my changes, if necessary.
- [x]  I have added translations for new strings, if necessary.
- [x] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by pankhurigoel — APPROVED** [review]
Looks good to me

**Review by pankhurigoel — APPROVED** [review]
Looks good. Thanks.

**Review by supernova-at — APPROVED** [review]

**Comment by revanth0212** [comment]
Functionality ❓ 
MFTF ❓ 
Cypress ✅

**Comment by mikhaelbois** [comment]
MFTF tests ✅

**Pull request merged**
