### PR TITLE
PWA-3155::Magento2 Backend URL

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Describe the bug

Self reporting that 7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud data-source URL is experiencing downtime.

Public Github search for all usages - https://github.com/search?q=%227rqtwti-mfwmkrjfqvbjk%22++NOT+is%3Aarchived+NOT+is%3Afork&type=code

To reproduce

Go to https://develop.pwa-venia.com/ , (or any of the instances in the currently opened PRs)
Home page might fail to load initially, or click on any product dropdown (e.g. Tops & Bottoms > Blouses & Skirts)
See 404 error page.
Browser DevTools - {{ {"status":502,"message":"No route known for master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud","additional_error":""}
}}

Expected behavior

The products page load. No 404 pages for main content. No 502 graphql failures.

## Related Issue

Closes https://jira.corp.adobe.com/browse/PWA-3155

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo42707** [comment]
run lighthouse-mobile

**Comment by glo42707** [comment]
hey @glo82145 

as if now backend URL issue got fixed as part of this PR  https://github.com/magento/pwa-studio/pull/4123


and above content relatedt issues we will be tracking on https://jira.corp.adobe.com/browse/PWA-3081 hence once pwa-3081 fixed then all isues of content related to new backend URL will be fixed. as can see attached on https://github.com/magento/pwa-studio/pull/4123#issuecomment-1559462142

**Review by RaghavendraTirumalasetti — APPROVED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-desktop

**Pull request merged**
