### PR TITLE
[PWA-2554] Long wishlist name breaks layout

### PR DESCRIPTION
**Pull request by jasonrpoteet**
## Description

Fixed overflow of text for custom wishlist name

## Related Issue

Closes PWA-2554

### Verification Stakeholders

Project Maintainers

## Verification Steps

Wishlist should account for custom names that are too long for the viewable UI.

#### Test scenario(s) for direct fix/feature

1. Log into Venia
2. Navigate to "Favorite List"
3. Add a custom  favorite list name that is super long
4. Notice that the name should now truncate when it reaches the end of the line, but will have a hover over with the full name

#### Test scenario(s) for any Magento Backend Supported Configurations

N/A

1. Verify that new and existing Jest tests pass
1. Verify that Cypress test passes

#### Is Browser/Device testing needed?

Yes

#### Any ad-hoc/edge case scenarios that need to be considered?

No

## Breaking Changes (if any)

No breaking changes

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run all tests

**Comment by dpatil-magento** [comment]
run all tests

**Comment by dpatil-magento** [comment]
run cypress

**Comment by jasonrpoteet** [comment]
closing this PR and going to reopen a new one to get rid of the clutter from the failed build

**Pull request closed without merging**
