### PR TITLE
tab order and focus trap for menu

### LINKED ISSUE #1470: My Account section tab order
Review and tweak keyboard tab order for the Venia 'My Account' section

### PR DESCRIPTION
**Pull request by dani97**
## Description

Accessibilty fixes for menu and my account

## Related Issue

Closes #1470 .

### Verification Stakeholders

@soumya-ashok 
### Verification Steps

1. Open menu check tab order and focus trap on nav bar
2. When Sign In button or view account button is clicked, focus should be trapped in new windoe
3. When `esc` key is pressed, the nav bar should close

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by schensley** [comment]
@dani97 For the most part this behaves very well and as expected, however there is a bit of a 'snag' when in the Account sign in panel, where I am unable to tab to the "Sign in" button. Instead I get stuck on the "Forgot Password?" link.
Screen Recording 2020-10-27 at 11 51 30 AM

**Comment by dani97** [comment]
> @dani97 For the most part this behaves very well and as expected, however there is a bit of a 'snag' when in the Account sign in panel, where I am unable to tab to the "Sign in" button. Instead I get stuck on the "Forgot Password?" link.
> 
> Screen Recording 2020-10-27 at 11 51 30 AM

Will look into this @schensley

**Comment by dani97** [comment]
seems focus is getting trapped into view password button

**Comment by supernova-at** [comment]
Hey @dani97 , anything I can do to help here? I can still reproduce getting stuck on the "forgot password" button.

Thanks!

**Comment by dani97** [comment]
@supernova-at Im blocked with other work. Will soon come back.

**Comment by sirugh** [comment]
Closing - tracked internally by PWA-1278. Have referenced this PR/issue to ensure credit is given if we build on this work. Thanks!

**Pull request closed without merging**
