### PR TITLE
AC-2788::Form fields have visual labels that are not programmatically…

### PR DESCRIPTION
**Pull request by glo71317**
## Description
Form fields have visual labels that are not programmatically associated with their inputs (pattern: Form field(s) lack accessible name)

**Reproduction Steps**
Locations (representative sample):

Global Header
- Checkout - Confirmation / Create an Account
Sign In
Account - Order History
1. With JAWS operating, press Tab to move through the fields identified.

**Actual Behavior**
There are form fields with visible labels that are not programmatically associated with the input; these inputs have no accessible name.

**Examples include:**

**Module 01a - Global Header:**
Search (visible text beneath the search input "Search for a product" is not a <label> element and is not programmatically associated with the input)

**Module 06c - Checkout - Confirmation / Create an Account**
(Note - the following form fields refer to "Quick Checkout When You Return")
Visible <label> elements lack for attributes to associate them with their inputs, including:
First Name
Last Name
Email
Password

**Module 07 - Sign In:**
Visible <label> elements lack for attributes to associate them with their inputs, including:
Email
Password

**Expected Behavior**
Ensure all controls provide a descriptive accessible name. Ensure visible <label> elements are correctly associated with their inputs using the for attribute.

## Related Issue
Closes https://jira.corp.magento.com/browse/AC-2788.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3837: AC-2788::Form fields have visual labels that are not programmatically…

### CODE REVIEW

**Comment by glo71317** [comment]
run all tests

**Review by anthoula — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
run pr-deploy

**Comment by dpatil-magento** [comment]
run cypress

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
QA Approved, cypress failures not related.

**Pull request merged**
