### PR TITLE
PWA-209: Track Page Views

### PR DESCRIPTION
**Pull request by eug123**
## Description

Added events in order to track page views.

**Acceptance Criteria**

- Page View event is tracked when a user lands on a page upon entering the site and when a user navigates to a new page.
- Page View event contains pagetype:
  - page
  - PLP
  - PDP
  - cart
  - checkout
  - order confirmation
- For each pageType collect specific to this page type attributes
- Example extension subscribes to the events and has events available for processing
- Example extension simply subscribes to event and logs its occurrence

## Related Issue

Closes #[PWA-2097](https://jira.corp.magento.com/browse/PWA-2097).

## Verification Steps

1. Load Venia homepage
2. Open browser console and verify that the sample extension logged the event (with its contextual data)
3. Navigate to a different page
4. Open browser console and verify that the sample extension logged the event (with its contextual data)
5. Go offline
6. Navigate back to the homepage
7. Open browser console and verify that the sample extension logged the event (with its contextual data)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run cypress tests

**Comment by fnhipster** [comment]
run all tests

**Comment by dpatil-magento** [comment]
@eug123   Registered user > My account pages like Order History, Account information ..etc are not being tracked. Please check.

**Comment by eug123** [comment]
@dpatil-magento,
These pages are not supposed to be tracked, there is [a different story](https://github.com/magento/pwa-studio/pull/3855) for user account events though.

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved

**Pull request merged**
