### PR TITLE
Update Plugin for JSX Snippet Parser

### LINKED ISSUE #3097: [bug]: Babel JSX Plugin Dependency Mismatch
**Describe the bug**

Babel plugin for parsing JSX has the incorrect dependency. 

**To reproduce**

1. Create a new PWA Studio project using the scaffolding tool `yarn create @magento/pwa`
2. Use latest tag (10.x)
3. Once installed, remove the storybook directory, and uninstall `@storybook/react`
4. Run `yarn build` or `yarn watch`, see build failures. 

To see dependency `yarn why babel-plugin-syntax-jsx`

**Expected behavior**

The correct Babel JSX Plugin is used to parse JSX. 

**Error Message**

`Error: Provided JSX fragment does not parse as a valid JSX Element: <Switch />: Error: Cannot find module 'babel-plugin-syntax-jsx'`

**Possible solutions**

Update dependency in `JSXSnippetParser.js`

**Debug Report**

```
  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 9.0.0
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.1.0
    @magento/eslint-config @ 1.5.2
    @magento/pagebuilder @ 5.0.0
    @magento/peregrine @ 10.0.0
    @magento/upward-security-headers @ 1.0.3
    @magento/venia-adobe-data-layer @ 1.0.0
    @magento/venia-ui @ 7.0.0

  ℹ  Inspecting Magento Backend
    Using sample backend: https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
    Node Version: v12.18.2
    NPM Version: 6.14.5
```

**Please complete the following device information:**

- Recreated on Node 12.8.2 / 14.16.0 & yarn 1.22.5

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by evan-burrell**
## Description

Update `JSXSnippetParser` to use `@babel/plugin-syntax-jsx` rather than `babel-plugin-syntax-jsx` from Storybook dependency tree. 

## Related Issue

Closes #3097.

### Specification
`pwa-buildpack`

### Verification Steps

1. Create a scaffolded project
2. Remove storybook directory and uninstall `@storybook/react`
3. Run `yarn build` or `yarn watch`
4. Build completes without errors

### CODE REVIEW

**Comment by larsroettig** [comment]
@evan-burrell nice catch

**Review by larsroettig — APPROVED** [review]
:heavy_check_mark:  Review and tested local

**Comment by dpatil-magento** [comment]
@evan-burrell I get below error during yarn build - 
Steps - 
1. Checkout this branch.
2. Create scaffolded project 
3. In scaffolded project removed .storybook dir from `src` dir
4. Removed `@storybook/react` from package.json
5. Deleted node_modules
6. Did yarn install
7. Run `yarn build`

```
ERROR in ./node_modules/@magento/venia-ui/lib/components/Routes/routes.js
Module build failed (from ./node_modules/@magento/pwa-buildpack/lib/WebpackTools/loaders/buildbus-babel-loader.js):
Error: Provided JSX fragment does not parse as a valid JSX Element: <Switch />: Error: Cannot find module 'babel-plugin-syntax-jsx' from '/pwa-studio-backup/scaffoldtest'
- Did you mean "@babel/syntax-jsx"?
    at JSXSnippetParser.parseElement (/pwa-studio-backup/scaffoldtest/node_modules/@magento/pwa-buildpack/lib/WebpackTools/targetables/BabelModifyJSXPlugin/JSXSnippetParser.js:52:19)
    at new Operation (/pwa-studio-backup/scaffoldtest/node_modules/@magento/pwa-buildpack/lib/WebpackTools/targetables/BabelModifyJSXPlugin/Operation.js:38:40)
    at new PrependOperation (/pwa-studio-backup/scaffoldtest/node_modules/@magento/pwa-buildpack/lib/WebpackTools/targetables/BabelModifyJSXPlugin/operations/prepend.js:2:5)
    at Function.fromRequest (/pwa-studio-backup/scaffoldtest/node_modules/@magento/pwa-buildpack/lib/WebpackTools/targetables/BabelModifyJSXPlugin/Operation.js:138:20)
```

**Comment by evan-burrell** [comment]
@dpatil-magento Thanks for taking a look at it. Those look like the steps to reproduce the errors, when the scaffolded project is created and you remove and re-install `node_modules` is that using the updated version of buildpack or the current version?

**Comment by dpatil-magento** [comment]
@evan-burrell My bad, missed to run `yarn cache clean`  so it was using stale cache.  Now I can see `yarn build` `yarn watch` are working.  But `yarn start`  or `yarn build:report`  still fail. should I expect these also to work?
Steps - 
same as previous , after `yarn build`, run `yarn start`
yarn run v1.22.10
$ buildpack serve .
/bin/sh: buildpack: command not found
error Command failed with exit code 127.

**Comment by evan-burrell** [comment]
Interesting, I believe those should work as expected. Those commands work in the scaffolding I have locally. 

Steps to recreate
- Create scaffolded project
- In scaffolded project removed .storybook dir from src dir
- Removed @storybook/react from package.json
- Delete node_modules
- yarn install
- In `@magento/pwa-buildpack/lib/WebpackTools/targetables/BabelModifyJSXPlugin/JSXSnippetParser.js` modify per the PR. 
- npx patch-package @magento/pwa-buildpack
- Run `yarn build`, `yarn watch`, `yarn start`, `yarn build:report`

**Comment by supernova-at** [comment]
**From PWA Studio project root:**
1. Checkout this branch
2. Create scaffolded project: `DEBUG_PROJECT_CREATION=1 pwa-studio/packages/create-pwa/bin/create-pwa`

**In scaffolded project:**
1. Remove `.storybook` dir from `src` dir
2. Remove `@storybook/react` from `package.json`
3. Delete `node_modules`
4. `yarn cache:clean`

✅  `yarn install`
✅  `yarn build`
✅  `yarn watch`
🚫  `yarn start`
🚫  `yarn build:report`

These both fail with a cryptic `TypeError: Cannot read property 'expected' of undefined`.
After some digging, I found something more useful:

```
$ yarn start

Unknown arguments: serve, .
```

```
$ yarn build:report

Unknown arguments: generate-build-report
```

So it seems like `buildpack` doesn't know what these commands are, and indeed if I run `buildpack --help`, `serve` and `generate-build-report` are not listed as a valid commands:

```
$ buildpack --help
buildpack <command>

Commands:
  buildpack create-custom-origin            Get or create a secure, unique
  <directory>                               hostname/port combination and a
                                            trusted SSL certificate for local
                                            development, which enables all PWA
                                            features.
  buildpack create-env-file <directory>     Generate a .env file in the provided
                                            directory to store project
                                            configuration as environment
                                            variables
  buildpack load-env <directory>            Load and validate the current
                                            environment, including .env file if
                                            present, to ensure all required
                                            configuration is in place.
```

I tried running `buildpack create-custom-origin .` as a test and it worked fine.

**Comment by supernova-at** [comment]
I tried using `patch-package` as per the steps in https://github.com/magento/pwa-studio/pull/3098#issuecomment-816502183, but got

```
$ npx patch-package @magento/pwa-buildpack

npx: installed 50 in 4.411s
patch-package 6.4.7
• Creating temporary folder
Ambigious lockfile entries for @magento/pwa-buildpack. Using version 9.0.0
• Installing @magento/pwa-buildpack@9.0.0 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package '@magento/pwa-buildpack'
⁉️  There don't appear to be any changes.
```

First time using `patch-package`, not sure if I did something incorrectly @evan-burrell .

**Comment by evan-burrell** [comment]
@supernova-at 

Thanks for taking a look at it, after running `yarn cache clean` and then running yarn install it looks like `buildpack` isn't synced into `node_modules` bin directory in [https://github.com/magento/pwa-studio/pull/3098#issuecomment-816194608](Previous comment) by @dpatil-magento so I'm getting `/bin/sh: buildpack: command not found` as well now. Not entirely sure how this could be related to the dependency change. When I did `patch-package` it would have been from the generic `yarn create @magento/pwa` not from scaffolding inside of PWA Studio. I'm guessing inside of the scaffolding that diff is the same as it includes the changes in the PR.

**Comment by supernova-at** [comment]
I just tried everything from the `develop` branch and ran into the same error(s). 

@dpatil-magento I'm pretty confident this PR is not introducing these errors.

**Comment by dpatil-magento** [comment]
Thanks @supernova-at .

**Review by supernova-at — APPROVED** [review]

**Pull request merged**
