### PR TITLE
Bug#checkbox clickable label working

### LINKED ISSUE #3994: [bug]: Clicking the Filters text label doesn't actually select the filter
**Describe the bug**
On a mobile device or desktop, when clicking on the text of a specific filter, it doesn't select the filter. For it to work properly, you have to specifically press on the **checkbox**.

**To reproduce**

1. Go to http://develop.pwa-venia.com/default/venia-tops.html?page=1
2. Expand any filter group
3. Click on the **text label** (not the checkbox itself) to apply a filter
5. Witness the problem: the filter doesn't get selected (it used to)

**Expected behavior**

When pressing or clicking on the text label beside the filter checkbox, the filter should be applied exactly as if I have explicitly clicked on the filter checkbox. The full line should be responsive to the selection (not only the checkbox part)

**Screenshots**

Screen Shot 2022-10-28 at 12 40 41 PM

**Please complete the following device information:**

-   Device: Mac M1 and iPhone11 Pro
-   Browser: Chrome (desktop), Safari (mobile)
-   Browser Version: Chrome desktop 106.0.5249.119 (Official Build) (arm64) / Safari mobile iOS 16.0.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by Sahilsks**
## Description

Clicking the Filters text label now select and unselect the filters.

## Related Issue

closes #3994

## Screenshots / Screen Captures (if appropriate)

https://user-images.githubusercontent.com/86670457/219595567-c22c3cea-30fe-4c2d-a0fa-029bafe1fafc.mov

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by Sahilsks** [comment]
@magento run all tests

**Comment by Sahilsks** [comment]
https://github.com/magento run all tests

**Comment by Sahilsks** [comment]
@magento run all tests

**Comment by Sahilsks** [comment]
@magento run all tests

**Comment by Sahilsks** [comment]
@magento run all tests

**Comment by Sahilsks** [comment]
@magento run all tests

**Comment by glo82145** [comment]
Closing this PR as associated issue is closed.

**Pull request closed without merging**
