### PR TITLE
PWA-2950: Braintree payment throws console error

### PR DESCRIPTION
**Pull request by anthoula**
## Description

- Update `braintree-web-drop-in` package

## Related Issue

Closes [PWA-2950](https://jira.corp.magento.com/browse/PWA-2950).
Closes [PWA-2880](https://jira.corp.magento.com/browse/PWA-2880).

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Review by jcalcaben — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Review by jcalcaben — APPROVED** [review]

**Pull request merged**
