### PR TITLE
[PWA-2672] Product prices is informed by the outdated field

### PR DESCRIPTION
**Pull request by tjwiebell**
## Description

Several places throughout the app that still query for a deprecated price field that does not reflect discounted pricing in Shared Catalogs

Actual Behavior:

when product price is adjusted with a sales promotion (special price, % discount on catalog etc) it's not reflected on the storefront 
Original product price is displayed, not a discounted one
Expected behavior:

Discounted price is displayed in the catalog (not the original one)
No price discount indication on the storefront (part of [PWA-1117](https://jira.corp.magento.com/browse/PWA-1117))

## Related Issue

* Closes [[PWA-2672](https://jira.corp.magento.com/browse/PWA-2672)] Product prices is informed by the outdated field

#### Test scenario(s) for direct fix/feature

Test Plan
Wiki - https://docs.magento.com/user-guide/catalog/product-price-special.html
Precondition setup -

Create a simple product A and configurable product A with special price.
Create a simple product B and configurable product B with special price only for logged in customer group only.
Setup a catalog price rule as mentioned in wiki for particular date range across storefront
Execute -

Go to Venia store front and verify products show proper prices as per pre-conditions on -
search results
Search suggestion
Category page
Product details page
Mini cart
Cart page
Edit product card on cart page
Checkout
Order confirmation
Order history
Wishlist
Verify on store view 1 and 2 both.
Add special price product to cart and try applying coupon code, gift cards and place order.
Precondition setup -

Setup a catalog price rule as mentioned in wiki for particular date range across storefront but only for selected products.
Execute -

Go to Venia store front and verify products show proper prices as per pre-conditions and all pages mentioned in above scenario as applicable
Cypress Test coverage
NO ui change so expecting all changes to be covered in unit and/or api functional test. If at all needed there is discount summary cypress integration test which can be updated.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by tjwiebell** [comment]
run cypress

**Comment by tjwiebell** [comment]
run cypress

**Review by michaelyu0123 — DISMISSED** [review]

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
@tjwiebell Please check [this](https://github.com/magento/pwa-studio/blob/1977d3515fff605cdaadf30e8f01e92a4a482397/venia-integration-tests/src/tests/integrationTests/multiStore/storeSwitching.spec.js#L805) failing cypess test. Its throwing error toast. Same works on `develop` (checked locally).  
NOTE - Other failing cypress test reported above is not related to this pr, you can ignore that one.

**Comment by tjwiebell** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run cypress @ci

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved.

**Review by dpatil-magento — APPROVED** [review]

**Pull request merged**
