### PR TITLE
[feature]: Add to Cart support for Virtual products

### LINKED ISSUE #2768: [feature]: Add to Cart support for Virtual products
**Add to Cart support for Virtual products**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by shikhamis11**
## Description

Add to Cart support for Virtual products

## Related Issue

Closes #2768

### Verification Steps
go to virtual product product page and add to cart 

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by shikhamis11** [comment]
#dmcdindia2020

**Comment by larsroettig** [comment]
Hi  @shikhamis11, 
thank you  for Pull Request from my point of view you should test cases  for:
 
- packages/peregrine/lib/talons/ProductFullDetail/__tests__/useProductFullDetail.spec.js 
- packages/venia-ui/lib/components/ProductFullDetail/__tests__/productFullDetail.spec.js

**Review by larsroettig — CHANGES_REQUESTED** [review]
Hi @shikhamis11,
thank you for Pull Request from my point of view you should test cases for:

- packages/peregrine/lib/talons/ProductFullDetail/tests/useProductFullDetail.spec.js
- packages/venia-ui/lib/components/ProductFullDetail/tests/productFullDetail.spec.js

Without test, you reduce coverage from 79.9% to 79.52. 

@tjwiebell would do you think ?

kind regars, 

Lars

**Comment by revanth0212** [comment]
Thanks for the contribution @shikhamis11. Nice work. Please do update the tests to cover the new feature.

**Comment by fooman** [comment]
@revanth0212 do you mind checking what the team's plans around adopting the single mutation for adding products to the cart are that lands in 2.4.1 - see https://github.com/magento/magento2/pull/27914 as to avoid building something that may get superseded very soon.

**Comment by sirugh** [comment]
@fooman Thank you for bringing this up! As the issue, #2768 was opened recently we haven't yet had a chance to analyze it internally or to provide feedback on the issue. As you have identified, it may be possible for us to migrate to the new mutation, `AddProductsToCart` rather than implement type-specific mutations and logic.

I do think we should try to implement the new mutation, but I also see value in this pull request as it will support Magento < 2.4.0.

I have opened https://jira.corp.magento.com/browse/PWA-1016 internally for tracking the use/implementation of the generic mutation.

**Comment by fooman** [comment]
@sirugh isn't the support matrix PWA-Studio 8.0.0 supports 2.4.0 - 2.4.1, while this PR would only make it into 9.0.0 which would then be 2.4.1-2.4.2?

**Comment by sirugh** [comment]
Yes, but as far as I know they aren't removing the old mutations yet.

**Comment by dpatil-magento** [comment]
@shikhamis11 Can you please take care of failed test and merge conflict?

**Comment by tjwiebell** [comment]
@shikhamis11 - I've resolved those conflicts, but I'm unfortunately being asked to stall this PR until critical path scenarios for virtual product are completed. @dpatil-magento pointed out during QA that add to cart works as expected, but it does prevent customers from checking out, and there probably isn't support for accessing products. We aren't certain what required flows are needed, so we would hate to ask you take on the completion of that work, but we're happy to continue collaborating on this feature if you're interested.

We appreciate the contribution and will use it as the starting point for the Virtual Product epic we have coming up that will fill in the rest of the gaps around checkout and product delivery. I realize this was a contribution day submission, and will see what I can do about crediting you for the PR, even though it will be closed.

Thank you again for the submission. We're making an effort to better supply features and bugs the team is prepared to accept and provide support around implementation. This can be found on the [Community Backlog](https://github.com/magento/architecture/pull/442/files) project under the Prioritized column 🙂

**Pull request closed without merging**
