### PR TITLE
MAGREQ-8593: Removed reference to old GH org

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Description

Related to #4146 

References to the `magento-devdocs` org must be replaced with the correct Adobe-owned org (`commerce-docs`).

## Related Issue

MAGREQ-8593
VULN-25329

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@glo42707 & @glo82145, will you please help me get this merged? I think it's the last update we need to resolve the issues reported in the ticket.

**Review by glo42707 — APPROVED** [review]
approved

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by jeff-matthews** [comment]
@glo82145, the Danger_CI_Checks test is failing with the following message:

> A version label is required. A maintainer must add one.

Can you please fix this error and merge?

**Pull request merged**
