### PR TITLE
AC-6678::The button is not usable by keyboard

### PR DESCRIPTION
**Pull request by glo82145**
## Description

<div class="table-wrap">

Environment | https://venia.magento.com/
-- | --
Testing Method | Observation
Resolution | Desktop
Page | Checkout
Location/Component | Place Order button
Issue description | The button is not usable by keyboard
Additional Note
Criteria Name | 2.1.1 Keyboard
Level | A
Impact | Blocker
Category | Visual, Motor, Cognitive
Responsibility | Developer
Fix (YES/NO) | Y
Fix Date |  

</div>
## Related Issue

Closes [#AC-6678.](https://jira.corp.adobe.com/browse/AC-6678)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3996: AC-6678::The button is not usable by keyboard

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run pr-test

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
