### PR TITLE
PWA-1951: Pagebuilder image content-type: mobile image is visible on desktop

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Updated logic to correctly pass desktop and mobile image src data in the config aggregator
- Added css class to hide mobile only image
- Updated test coverage

## Description

PWA pagebuilder image component should support mobile image only setting

*Steps to Reproduce*
 # Create cms page and add image content-type
 # Set only mobile image for the for content-type
 # Visit cms page on Venia

*Expected*
 (/) Image is not visible on the desktop, but visible on mobile screen width only
*Actual*
 (x) Image is visible on both desktop and mobile screen widths

 *Test Plan*
 * Verify mobile image is not visible in desktop on Venia CMS page
 * Verify mobile image is visible on mobile on Venia CMS page
 * Verify this use case is covered with an automated test

## Related Issue

Closes #[PWA-1951](https://jira.corp.magento.com/browse/PWA-1951)
#### Test scenario(s) for direct fix/feature

 *Test Plan*
 * Verify mobile image is not visible in desktop on Venia CMS page
 * Verify mobile image is visible on mobile on Venia CMS page
 * Verify this use case is covered with an automated test

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by mikhaelbois — APPROVED** [review]
LGTM ✅

**Comment by mikhaelbois** [comment]
New conflict to resolve.

**Review by mikhaelbois — APPROVED** [review]

**Comment by mikhaelbois** [comment]
Seems like a test needs to be updated.
`packages/pagebuilder/lib/ContentTypes/Image/__tests__/image.spec.js`

**Review by mikhaelbois — DISMISSED** [review]

**Comment by eug123** [comment]
@michaelyu0123 
Verification steps passed - everything looks good, 
but [image cypress test](https://github.com/magento/pwa-studio/blob/develop/venia-integration-tests/src/tests/integrationTests/pageBuilder/image.spec.js) fails.
Please update the test, maybe it make sense to add [mobile viewport context](https://github.com/magento/pwa-studio/blob/c8bc2a2a852c8ac02de0cba7c1a2313d8cdc9c1a/venia-integration-tests/src/tests/integrationTests/pageBuilder/products.spec.js#L159) for image test as well?

**Comment by michaelyu0123** [comment]
> @michaelyu0123 Verification steps passed - everything looks good, but [image cypress test](https://github.com/magento/pwa-studio/blob/develop/venia-integration-tests/src/tests/integrationTests/pageBuilder/image.spec.js) fails. Please update the test, maybe it make sense to add [mobile viewport context](https://github.com/magento/pwa-studio/blob/c8bc2a2a852c8ac02de0cba7c1a2313d8cdc9c1a/venia-integration-tests/src/tests/integrationTests/pageBuilder/products.spec.js#L159) for image test as well?

I have updated the test to include mobile and updated desktop screenshot.

**Review by eug123 — APPROVED** [review]

**Comment by eug123** [comment]
All tests passed. Thank you!

**Pull request merged**
