### PR TITLE
Make Apollo links customizable

### PR DESCRIPTION
**Pull request by jimbo**
## Description

Allow Apollo links to be customized by a `configureLinks` prop to `Adapter` / `useAdapter`. Also, while we're at it, extract the links into their own modules.

This can either follow #3757 or we can combine them here.

### New component/talon signature

```jsx
function configureLinks(linksMap) {
  // receive a map
  // return either a map or array, with modifications
  return Array.from(linksMap.values())
}

const tree = (
  <Adapter
    apiBase="https://example.com/graphql"
    configureLinks={configureLinks}
    store={store}
    styles={styles}
  />
)
```

### New package structure

```
peregrine
|- lib
  |- Apollo
    |- links
      |- authLink.js
      |- errorLink.js
      |- gqlCacheLink.js
      |- index.js
      |- mutationQueueLink.js
      |- retryLink.js
      |- storeLink.js
```

## Related Issue

CIF-2826

### Verification Stakeholders

- @dpatil-magento 
- @tjwiebell 
- @Buuhuu 

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3847: Make Apollo links customizable

### CODE REVIEW

**Review by tjwiebell — APPROVED** [review]
Nice abstraction and introduction of extension points that maintain backward compatibility 👍

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by tjwiebell — APPROVED** [review]
Looks good 👍  will get a second set of eyes from team and hopefully get this to QA today.

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
Did regression on Apollo cache storage and error triggers. QA approved.

**Pull request merged**
