### PR TITLE
[feature]: Update manifest with new Venia theme/background color

### LINKED ISSUE #2802: [feature]: Update manifest with new Venia theme/background color
**Is your feature request related to a problem? Please describe.**
Manifest needs to be updated to reflect the new Venia brand/design refresh. This is currently orange and not blue.

**Describe the solution you'd like**
Replacement of theme_color and review of others in manifest so that it appears correctly in app. Color should be HEX #1F39FF / RGB: 31 57 255. 

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by huykon**
## Description

Replacement of theme_color and review of others in manifest so that it appears correctly in app. Currently, color should be HEX #1F39FF 

## Related Issue

Closes #2802.

### Verification Steps

1. Access to site.
2. Click install app on browser (with desktop) or Add to home screen (with mobile version)
3. Check the background theme color as issue reported.

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by larsroettig — APPROVED** [review]

**Review by sirugh — APPROVED** [review]

**Comment by schensley** [comment]
Hi @huykon I checked this via Browserstack emulator it appears the 'old' Brand color (O
Screen Shot 2020-10-27 at 11 36 10 AM
range) is still showing up. See screen shot. Please take another look a the solution. Thanks.

**Comment by sirugh** [comment]
I'm realizing that the move to maskable icons, as in #2804/#2818 will cause the "theme color" to show up around the square maskable icon in this view. As such, we should reconsider whether we want "blue" to be the theme color. IMO white would look best.

Screenshot_20201027-113724

**Comment by schensley** [comment]
@sirugh Oh. Well that's something that we should address as well. I tried the emulator again for A2H and things looked pretty good. Didn't see any Brand blue actually, things were mostly 'white'.

**Comment by sirugh** [comment]
> @sirugh Oh. Well that's something that we should address as well.

Definitely, I'll create a ticket.

> I tried the emulator again for A2H and things looked pretty good. Didn't see any Brand blue actually, things were mostly 'white'.

From what I could tell in my own testing the theme/color modified in this PR is only used as a thin bar at the top of the screen when installing/opening the app and as a background for the icon if the one used is too small and filler is needed. Very small use case it seems.

**Comment by schensley** [comment]
Since I could see any issues with the A2H experience with regards to Brand color, other than as noted above (which will be handled in another ticket), I am approving this PR from a UX perspective.

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
