### PR TITLE
fix: scaffold storybook

### PR DESCRIPTION
**Pull request by sirugh**
## Description

The scaffolded app storybook failed to run as we did not update the venia-concept storybook files with the fixes applied in these PRs:

https://github.com/magento/pwa-studio/pull/2705
https://github.com/magento/pwa-studio/pull/2609

## Related Issue

Closes [PWA-920](https://jira.corp.magento.com/browse/PWA-920).

### Verification Steps

1. `yarn` and `yarn storybook:venia` to make sure venia-ui storybook works.
2. `DEBUG_PROJECT_CREATION=true packages/pwa-buildpack/bin/buildpack create-project scaffold-test-1 --template "venia-concept" --name "scaffold-test-1" --author "test123 <tester@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn"`
3. `cd scaffold-test-1`
4. `yarn run storybook` and make sure the scaffold storybook works.

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by supernova-at — APPROVED** [review]

**Comment by supernova-at** [comment]
Hmm, while verifying I get

```
ERROR in ./src/.storybook/config.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/aterrano/code/pwa-studio/scaffold-test-1/src/.storybook/config.js: Cannot find module 'react-hot-loader/babel' from '/Users/aterrano/code/pwa-studio/scaffold-test-1'
```

**Comment by sirugh** [comment]
@supernova-at I'm not able to repro the error you got - both venia-ui storybook and scaffolded storybook run without error for me.

**Comment by supernova-at** [comment]
Fixed! I needed to do a `yarn clean:all && yarn cache clean` beforehand 👍

**Comment by yogesh-seepossible** [comment]
> Fixed! I needed to do a `yarn clean:all && yarn cache clean` beforehand 👍

For Me `yarn clean && yarn cache clean` worked

**Pull request merged**
