### PR TITLE
Limit CSS Modules to *.module.css files

### PR DESCRIPTION
**Pull request by jimbo**
## Description

It's difficult to add new loaders and import custom CSS files when our webpack configuration blindly applies `modules: true` to all CSS files. The existing exception for `node_modules` is insufficient; a filename pattern would help. The `*.module.css` pattern is standard (see [NextJS docs](https://nextjs.org/docs/basic-features/built-in-css-support#adding-component-level-css)).

- Update webpack config to only set `modules: true` for `*.module.css` files (plus opt-ins)
- Rename all CSS files that expect `modules: true`
- Update references to old filenames, including imports

## Related Issue

PWA-2117

### Verification Stakeholders

- @jcalcaben
- @tjwiebell 

## Verification Steps

- Ensure the app builds with no errors or warnings
- Ensure Tailwind generated classnames are not transformed by CSS Modules
- Ensure there are no visual regressions (nothing changed)

## Breaking Changes (if any)

Hundreds of CSS files have been renamed and their components updated to point to the new filenames, so everything here requires a major version.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by larsroettig — DISMISSED** [review]
Pls take a look at why global styling breaks and the tests look like something

**Review by jcalcaben — CHANGES_REQUESTED** [review]
Just need to resolve the conflict and update from develop and then I can ✅

**Review by jcalcaben — APPROVED** [review]

**Comment by mikhaelbois** [comment]
@jimbo 
✅ Ensure the app builds with no errors or warnings
✅ Ensure Tailwind generated classnames are not transformed by CSS Modules
❌ Ensure there are no visual regressions (nothing changed)
With the new code from develop, some CSS files are not prefixed as intended.
I used the following regex to find them.
`^((?!module).)*\.css`
- ForgotPasswordPage (including their tests)
- SignInPage (including their tests)

Once those are updated, this can close.

**Comment by jimbo** [comment]
> ...
> Once those are updated, this can close.

@mikhaelbois Nice catch. Not sure how my regex missed those, but I've updated them. 1fcc7141d50722b1ecd6fad68a70543b3a3f7a57

**Review by jcalcaben — APPROVED** [review]

**Comment by mikhaelbois** [comment]
The update of the CSS files will impact all MFTF and Cypress tests.
Previous class name: `component-root-hash`
New class name: `component-module-root-hash`

**Comment by mikhaelbois** [comment]
@jimbo 
✅ QA
Cypress and MFTF tests are now running as intended.
The ones failing are the ones we are aware of.

**Pull request merged**
