### PR TITLE
BUG#-3064 When the button cancel beside create account is pressed by …

### PR DESCRIPTION
**Pull request by RaghavendraTirumalasetti**
…the keyboard, nothing happens

## Description

Pre-Conditions:

Have Magento 2.4.6alpha2 EE setup with [Venia configured](https://wiki.corp.adobe.com/display/ACRQ/PWA+Studio+Set+Up+in+Local).
Make sure Venia has at least one customer login account to login into the Venia front end.
Make sure Screen reader installed and enabled.
Steps to Reproduce:

Open Venia front end in any browser 
Navigate by using tab button sign in button > press enter to expand 
Navigate to create account button > without filling details > tab to cancel button and press enter to cancel.
 

Expected result:  Cancel button should respond with the cancel functionality in UI when the ENTER key is pressed

Actual result: Cancel button is not working with the keyboard, when the ENTER key is pressed

## Related Issue

Closes #https://jira.corp.adobe.com/browse/PWA-3064.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by glo82145 — APPROVED** [review]

**Review by glo82145 — DISMISSED** [review]

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run lighthouse-mobile

**Comment by glo42707** [comment]
run cypress

**Review by glo82145 — APPROVED** [review]

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run lighthouse-mobile

**Pull request merged**
