### PR TITLE
BUG#AC-2485 No visual indication of focus on buttons. (pattern: Butto…

### PR DESCRIPTION
**Pull request by RaghavendraTirumalasetti**
…ns lack indication of focus)

## Description

Reproduction Steps
Locations (representative sample):

Landing Page
Search Results
Product Detail Page
Shopping Bag
1. Press Tab to move through the content.

Actual Behavior
There is no visual indication of keyboard focus of buttons when using TAB or SHIFT+TAB to navigate through controls of the page. For the following buttons:

Module 02 - Landing Page:
"Dot" icon buttons for homepage carousel
"Slider" buttons for "Top Sellers" carousel

Module 03 - Search Results Page:
Page selection buttons (which includes - First, Previous, Page #, Next, Last)

Module 04 - Product Detail Page:
QTY "-" and "+" buttons
Page controls on resize (200%) - "<", ">", and page dots

Module 05b - Shopping Bag:
QTY "-" and "+" buttons
Options "dots" button

Visual keyboard-only users can become disoriented when focus is not indicated.

Expected Behavior
Ensure that when actionable elements receive focus, that it appears on screen and that a visible focus indicator is present.

## Related Issue

Closes https://jira.corp.adobe.com/browse/AC-2485

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3999: BUG#AC-2485 No visual indication of focus on buttons. (pattern: Butto…

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by jcalcaben — CHANGES_REQUESTED** [review]
@RaghavendraTirumalasetti  please resolve merge conflicts

**Review by jcalcaben — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
