### PR TITLE
PWA-1441 [feature]: Switching stores results in error page if slug changes between stores

### PR DESCRIPTION
**Pull request by eug123**
## Description

When switching store views (frequently languages), if the URL slug isn't the same for the new store view, it will cause a 404. This after plugin will check what the URL is supposed to be for the current store view, based on the old URL, and return a redirect if found.

Related PR for PWA extension https://github.com/magento-commerce/magento2-pwa/pull/10

## Related Issue

Closes #[PWA-1441](https://jira.corp.magento.com/browse/PWA-1441).

## Verification Steps

1. Configure 3 store views: English, French, Spanish
2. In admin, change the URL for a category in the French and Spanish store views (do not check the "create redirect" checkbox)
3. In admin, disable other category in the Spanish store view
4. Visit the English PWA Studio store front for that category
5. Change to French store view. Should redirect to new URL
6. Change to Spanish store view. Should redirect to new URL
7. Visit the English PWA Studio store front for other category
8. Change to Spanish store view. Should redirect to homepage without errors
9. Return to English store view. Should redirect to new URL
10. Verify Bread crumbs loads with correct name.
10. Repeat steps 2-10 for a product
11. Search for products on English PWA Studio store switch to French store view. Should redirect to search result page correctly
12. Verify product, category switching when url suffix is enabled in backend.
12. Repeat verification steps with enabled/disabled store code in url
13. Run cypress tests

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by tjwiebell — CHANGES_REQUESTED** [review]
Looks good, great test re-factor 👍 tiny comment about using a different Apollo hook.

**Comment by eug123** [comment]
run cypress

**Review by tjwiebell — APPROVED** [review]

**Comment by eug123** [comment]
run cypress

**Comment by mikhaelbois** [comment]
@eug123 
Note that I merged develop on the branch locally. Would it be possible to do the same on your side?

- Visit the English PWA Studio store front for that category ✅ 
- Change to French store view. Should redirect to new URL ✅
- Change to Spanish store view. Should redirect to new URL ✅
When not disabled, url rewrite works as expected.
- Visit the English PWA Studio store front for other category ✅
- Change to Spanish store view. Should redirect to homepage without errors 🛑
Getting the following error when switching to the store that has the category disabled.
```
Cannot read properties of undefined (reading 'name')
peregrine/lib/talons/RootComponents/Category/useCategoryContent.js:95:72
```
- Verify Bread crumbs loads with correct name ✅
- Repeat steps 2-10 for a product ✅
- Search for products on English PWA Studio store switch to French store view. Should redirect to search result page correctly ✅
- Verify product, category switching when url suffix is enabled in backend ⚠️
Getting the following error on a Category Page that does not have a url suffix.
```
Failed prop type: The prop storeConfig.product_url_suffix is marked as required in GalleryItem, but its value is null.
```
- Repeat verification steps with enabled/disabled store code in url ⚠️ 
There's a weird edge case. Please see the attached video file for more info or contact me directly.

1. USE_STORE_CODE_IN_URL=false
2. Start from the Home Page
3. Switch to the FR Store
4. Paste in the url an url that should work only in another Store
5. See that the url is rewriting to fit your current store, but that the url parameters blinks
6. After the page loads, click on the Logo
7. The page will not show the Home Page and reload the same page
8. Click again and you should be redirected to the Home Page

https://user-images.githubusercontent.com/1170507/154554187-134bd0a9-984e-4b14-9d31-969a5e100ce5.mp4

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Review by jasonrpoteet — APPROVED** [review]
The code updates are good with me, and the functionality hahs been tested on a cloud instance and is working as expected now.

**Comment by jasonrpoteet** [comment]
run all tests

**Comment by eug123** [comment]
run all tests

**Comment by eug123** [comment]
run lighthouse-desktop

**Comment by eug123** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run cypress

**Pull request merged**
