### PR TITLE
Changed Pagebuilder components location

### PR DESCRIPTION
**Pull request by Rykh**
## Description

Update documentation according to the changes in the project

## Related Issue

Closes #ISSUE_NUMBER.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3297: Changed Pagebuilder components location

### CODE REVIEW

**Comment by jcalcaben** [comment]
@bdenham can you take a look and verify these changes?

**Comment by bdenham** [comment]
> @bdenham can you take a look and verify these changes?

Yep. Will do.

**Comment by bdenham** [comment]
@Rykh So where is this CustomQuote introduced? Sorry, I'm not able to look at the whole doc set at the moment.

But why don't we call it CustomQuote instead? Sounds more natural that way. 

I'll look at this in greater depth soonish. Thanks.

**Comment by supernova-at** [comment]
@magento create issue from PR

**Review by jcalcaben — CHANGES_REQUESTED** [review]
What's the reason for changing `ExampleQuote` to `QuoteCustom`? 

This topic is part of a series of tutorials that reference the `ExampleQuote` type. If you change the name of this type here, you should change it in all the other tutorial topics under the `custom-components` directory.

**Comment by jcalcaben** [comment]
Closing this PR due to inactivity. @bdenham We still need to update the Pagebuilder docs according to the changes in the project. See PWA-1874.

**Pull request closed without merging**
