### PR TITLE
PWA-2971: [bug]: Gallery item Add To Cart configurable product redire…

### LINKED ISSUE #3854: [bug]: Gallery item Add To Cart configurable product redirect URL doesn't match tile URL
**Describe the bug**

When clicking the add to cart button on a configurable product gallery item (the PLP for instance) the URL you're redirected to doesn't match the URL used on the product tile. 

**To reproduce**

1. Go to https://venia.magento.com/venia-bottoms/venia-pants.html?page=1
2. Click on the Add To Cart button for Gloria Palazzo Pants
3. Will be redirected to https://venia.magento.com/venia-bottoms/gloria-palazzo-pants.html

**Expected behavior**

Should be redirected to https://venia.magento.com/gloria-palazzo-pants.html, like click the image would do

**Possible solutions**
- Support product options in listings

OR
- Render a Redirect component instead of using `history.push` and prefix URL with a `/` so it uses the base URL instead of being relative

OR
- Use a Link for the button when it's a configurable product

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by anthoula**
…ct URL doesn't match tile URL

- prefix url suffix with slash to fix redirect
- update test expectation

## Description

Prefix URL with a `/` so it uses the base URL instead of being relative

## Related Issue

Closes #3854.

### Verification Stakeholders

@dpatil-magento 

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by anthoula** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
