### PR TITLE
PWA-3052::Page Builder column-line content type is not supported, thi…

### LINKED ISSUE #3949: [bug]: Page Builder column-line content type is not supported, this content will not be rendered.
**Describe the bug**

Ever since we upgraded to Magento 2.4.5 our Pagebuilder content that uses a column has stopped working. We tested this on a clean Pwa Studio install with a Magento 2.4.5 backend attached to it.

**To reproduce**

1. install a fresh pwa studio environment
2. attach it to a magento 2.4.5 backend
3. use a column in pagebuilder on your homepage (or any other page)

**Expected behavior**

I expect to see the columns and their content I added using pagebuilder in the frontend application.

**Screenshots**

Landing page backend used for my current homepage:
image

Landing page frontend used for my current homepage:
image

error in console:
image

**Possible solutions**

Extend the @magento/pagebuilder/lib/ContentTypes with the new column-line type.

**Debug Report**

**_yarn build:report output :_**
yarn run v1.22.17
$ buildpack generate-build-report
  ℹ  Generating build report for pwa-test@0.0.1. This may take a moment.

  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 11.4.0
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.1
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 7.4.1
    @magento/peregrine @ 12.5.1
    @magento/pwa-theme-venia @ 1.3.0
    @magento/upward-security-headers @ 1.0.10
    @magento/venia-ui @ 9.6.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Node Version: v16.15.0
    NPM Version: 8.5.5

✨  Done in 4.25s.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: Version 104.0.5112.101 (Official Build) (x86_64)
-   Magento Version [e.g Adobe Commerce 2.4]: Magento ver. 2.4.5

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [x] `pagebuilder`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by glo82145**
…s content will not be rendered

## Description

Add support for Page Builder column-line content type

## Related Issue

Closes #3949 .

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by anthoula — APPROVED** [review]

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run lighthouse-mobile

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
QA Approved By @juhi kumari

**Pull request merged**
