### PR TITLE
PWA-1968: [bug]: Page Builder Out of Stock messaging displaying for products that are in stock

### PR DESCRIPTION
**Pull request by mikhaelbois**
## Description

The Page Builder Products component did not query all the required properties for the `AddToCartbutton` and `WishlistGalleryButton` components.
This fix adds them and requires them too.

## Related Issue

Linked to https://jira.corp.magento.com/browse/PWA-1968.

### Verification Stakeholders

@anthoula 

#### Test scenario(s) for direct fix/feature

1. Test with a Page Builder Product Grid or Carousel
2. Test that the "Add to Cart" button works
3. If the product is out of stock, the button should be replaced accordingly
4. If the product is of type virtual, bundle, grouped or downloadable, the button should be disabled
5. Test the "Add to Wishlist" button
6. Category Product listing should not be impacted

## Checklist

- [x] I have updated the tests to cover my changes.

### CODE REVIEW

**Review by eug123 — DISMISSED** [review]
Looks good, thank you!

**Comment by mikhaelbois** [comment]
@anthoula I've updated the items fragments for the Search Page that were missing data.
Should be good now.
Regarding the Wishlist test, I tried multiple times and finally got one to work. Seems to be only a timeout issue.

**Review by eug123 — DISMISSED** [review]

**Comment by anthoula** [comment]
@mikhaelbois Another observance: Products within CMS Block are showing Out of Stock button.

Dynamic Block may be the same case.

Page-Builder-Block-Page diff

**Comment by mikhaelbois** [comment]
I went over each tests and there was only one snapshot that needed an update.
Another thing that impacts the test is the Google Map that depends on multiple things.
But now, the products listing will show the Add to Cart properly.

**Comment by anthoula** [comment]
QA Approved

**Review by anthoula — APPROVED** [review]

**Pull request merged**
