### PR TITLE
Replace backtick with single quote

### PR DESCRIPTION
**Pull request by mpchadwick**
## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

### Verification Steps

1. Go to the FOO page.
2. Verify the BAR shows up.
3. Make sure BAZ does a thing.

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by larsroettig** [comment]
Hacktoberfest Spam PR closed

**Comment by mpchadwick** [comment]
Not sure why you closed this. The backtick will break your build. I'm not trying to spam...I was following these instructions today and noticed this issue and was proactively trying to fix it...

**Comment by larsroettig** [comment]
@mpchadwick add this change to #2746 this would be okay

**Comment by mpchadwick** [comment]
OK done. I noticed them separately and created fixes immediately for each when I noticed which resulted in the separate PRs.

**Pull request closed without merging**
