### PR TITLE
[PWA-1979]: Bug - reduce yarn warnings from scaffold installation

### LINKED ISSUE #3330: [bug]: Numerous warnings during set-up
**Describe the bug**

Numerous warnings about dependencies are thrown when setting up PWA Studio

```
yarn create @magento/pwa

yarn create v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@magento/create-pwa > @magento/pwa-buildpack@9.0.0" has unmet peer dependency "@babel/core@^7.3.4".
warning "@magento/create-pwa > @magento/pwa-buildpack@9.0.0" has unmet peer dependency "babel-loader@~8.0.5".
warning "@magento/create-pwa > @magento/pwa-buildpack@9.0.0" has unmet peer dependency "css-loader@~2.1.1".
warning "@magento/create-pwa > @magento/pwa-buildpack@9.0.0" has unmet peer dependency "terser-webpack-plugin@~1.2.3".
warning "@magento/create-pwa > @magento/pwa-buildpack@9.0.0" has unmet peer dependency "workbox-webpack-plugin@~6.0.2".
warning "@magento/create-pwa > @magento/pwa-buildpack > @magento/upward-js@5.1.0" has unmet peer dependency "express@^4.16.4".
warning "@magento/create-pwa > @magento/pwa-buildpack > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has unmet peer dependency "react-refresh@>=0.8.3 <0.10.0".
warning "@magento/create-pwa > @magento/pwa-buildpack > graphql-playground-middleware-express@1.7.22" has unmet peer dependency "express@^4.16.2".
warning "@magento/create-pwa > @magento/pwa-buildpack > hastily@0.5.0" has unmet peer dependency "sharp@>=0.25.4".
warning "@magento/create-pwa > @magento/pwa-buildpack > @magento/upward-js > @apollo/client@3.1.5" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
[#################################################################################################################################] 739/73[4/4] 🔨  Building fresh packages...

success Installed "@magento/create-pwa@1.3.0" with binaries:
      - create-pwa
@magento/create-pwa v1.3.0
Creating a PWA Studio project
? Project root directory (will be created if it does not exist) pwa-studio
? Short name of the project to put in the package.json "name" field pwa-studio
? Name of the author to put in the package.json "author" field 
? Which template would you like to use to bootstrap pwa-studio? Defaults to "@magento/venia-concept". @magento/venia-concept
? Magento instance to use as a backend (will be added to `.env` file) 2.4-develop
? Braintree API token to use to communicate with your Braintree instance (will be added to `.env` file)
? NPM package management client to use yarn
? Install package dependencies with yarn after creating project Yes

Running command:

buildpack create-project pwa-studio --name "pwa-studio" --template "@magento/venia-concept" --npm-client "yarn"


  ℹ  Finding @magento/venia-concept tarball on NPM
  ℹ  Downloading and unpacking https://registry.npmjs.org/@magento/venia-concept/-/venia-concept-10.0.0.tgz
  ℹ  Unpacked @magento/venia-concept
  ℹ  Creating a new PWA project 'pwa-studio' in pwa-studio
  ℹ  Successfully wrote a fresh configuration file to /Users/wx938yv/Projects/pwa-studio/.env
yarn install v1.22.10
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning @magento/pwa-buildpack > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @magento/pwa-buildpack > @magento/upward-js > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @magento/pwa-buildpack > pertain > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @magento/pwa-buildpack > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @magento/pwa-buildpack > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @magento/pwa-buildpack > @magento/upward-js > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @magento/pwa-buildpack > copy-webpack-plugin > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @magento/pwa-buildpack > jsdom > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @magento/pwa-buildpack > @pmmmwh/react-refresh-webpack-plugin > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @magento/pwa-buildpack > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning @magento/pwa-buildpack > @magento/upward-js > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @magento/pwa-buildpack > @magento/upward-js > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @magento/venia-ui > uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @storybook/react > @storybook/core > webpack-hot-middleware > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @storybook/react > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning eslint-plugin-graphql > graphql-config > graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning graphql-cli > graphql-config > graphql-import@0.7.1: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning graphql-cli > apollo-codegen@0.20.2: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI. Switch to 'apollo' to ensure future updates and visit https://npm.im/apollo#code-generation for more information.
warning graphql-cli > graphql-cli-prepare > graphql-import@0.4.5: GraphQL Import has been deprecated and merged into GraphQL Tools, so it will no longer get updates. Use GraphQL Tools instead to stay up-to-date! Check out https://www.graphql-tools.com/docs/migration-from-import for migration and https://the-guild.dev/blog/graphql-tools-v6 for new changes.
warning graphql-cli > express-request-proxy > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning graphql-cli > creato > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning graphql-cli > apollo-codegen > apollo-codegen-core > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql > json-schema-ref-parser > z-schema > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning graphql-cli-validate-magento-pwa-queries > babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning html-webpack-plugin@3.2.0: 3.x is no longer supported
warning react-intl > intl-messageformat-parser@6.4.4: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
warning uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@magento/pwa-buildpack > hastily@0.5.0" has incorrect peer dependency "sharp@>=0.25.4".
warning " > @apollo/client@3.1.5" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
warning " > @magento/eslint-config@1.5.2" has unmet peer dependency "eslint-config-prettier@^6.0.0".
warning " > @magento/eslint-config@1.5.2" has incorrect peer dependency "eslint-plugin-react-hooks@^1.6.0".
warning " > @magento/pagebuilder@5.0.0" has incorrect peer dependency "react-tabs@~3.1.0".
warning " > react-slick@0.25.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.1 || ^16.0.0".
warning " > react-slick@0.25.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.1 || ^16.0.0".
warning " > informed@3.27.0" has incorrect peer dependency "react@^16.8.0".
warning " > informed@3.27.0" has incorrect peer dependency "react-dom@^16.8.0".
warning " > @storybook/react@6.1.21" has incorrect peer dependency "@babel/core@^7.11.5".
warning "@storybook/react > react-docgen-typescript-plugin@0.6.3" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/react > react-docgen-typescript-plugin > react-docgen-typescript@1.22.0" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/react > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "@storybook/react > @storybook/core > @storybook/ui > react-sizeme@2.6.12" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0-0 || ^16.0.0".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > babel-plugin-graphql-tag@2.0.0" has unmet peer dependency "graphql-tag@^2.10.1".
warning " > eslint-plugin-graphql@3.0.3" has incorrect peer dependency "graphql@^0.12.0 || ^0.13.0 || ^14.0.0".
warning "eslint-plugin-graphql > graphql-config@2.2.2" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "eslint-plugin-graphql > graphql-config > graphql-import@0.7.1" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "graphql-cli > graphql-cli-prepare > graphql-import@0.4.5" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-cli > graphql-cli-prepare > graphql-static-binding@0.9.3" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0".
warning "graphql-cli > tmp-graphql-config-extension-openapi > @kbrandwijk/swagger-to-graphql@2.4.3" has incorrect peer dependency "graphql@^0.12.0 || ^0.13.0".
warning " > react-intl@5.7.2" has incorrect peer dependency "react@^16.3.0".
warning "react-intl > @formatjs/intl@1.13.5" has unmet peer dependency "@types/node@14 || 16".
warning " > react-redux@7.1.3" has incorrect peer dependency "react@^16.8.3".
warning " > react-tabs@3.0.0" has incorrect peer dependency "react@^16.3.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 137.04s.
  ✔  Installed dependencies for 'pwa-studio' project
  ⚠  Created new PWA project pwa-studio. Next steps:

     - cd pwa-studio before running the below commands.

     - yarn run buildpack create-custom-origin . to generate a unique, secure custom domain for your new project. Highly
     recommended.

     - yarn run watch to start the dev server and do real-time development.

     - yarn run storybook to start Storybook dev server and view available components in your app.

     - yarn run build to build the project into optimized assets in the '/dist' directory.

     - yarn start after build to preview the app on a local staging server.

✨  Done in 193.06s.
```

**To reproduce**

1. Run `yarn create @magento/pwa`

**Expected behavior**

No warnings to be displayed. Or at least to reduce the number of warnings currently thrown.

**Possible solutions**

Improve the peer dependencies to fix most of the version warnings.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: macOS terminal

### PR DESCRIPTION
**Pull request by pedrochiossi**
## Description

There were many dependency related warnings when installing yarn packages from `yarn create @magento/pwa`. Most of them were related to outdated modules that weren't accepting react 17.0.1 as peer dependency. This PR fixes most of those warnings by upgrading packages and peer dependencies to versions that resolve those issues. Some warnings not related to dependencies were also fixed by the updates.

The upgrade on eslint-react-hooks has an additional rule that warns about exhaustive dependencies (exhaust-deps rule) see [here](https://github.com/facebook/react/issues/14920) for more info) , all warnings related to this new eslint rule were fixed in this PR.

## Related Issue

Closes #3330.

## Verification Steps

1. Run `DEBUG_PROJECT_CREATION=1 [PWA_STUDIO_DIRECTORY]/packages/create-pwa/bin/create-pwa`
2. Change template venia-concept location to point to your local package at `[PWA_STUDIO_DIRECTORY]/packages/venia-concept`
3. Proceed with default configurations
4. Wait for yarn to install your local packages
5. Observe thrown warnings. 
7. Number of yarn warnings should be reduced (compare with previous on #3330 or run `yarn create @webjump/pwa`).

#### Test scenario(s) for direct fix/feature

Verify that the number of yarn warnings were reduced after fix. 

## Screenshots / Screen Captures (if appropriate)
```
yarn install v1.22.11
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning workbox-build > @hapi/joi@16.1.8: Switch to 'npm install joi'
warning workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning workbox-build > @hapi/joi > @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
warning workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning workbox-build > @hapi/joi > @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
warning workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning @magento/pwa-buildpack > pertain > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @magento/pwa-buildpack > @pmmmwh/react-refresh-webpack-plugin > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @magento/pwa-buildpack > copy-webpack-plugin > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @magento/upward-js > hogan.js > mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning @magento/upward-js > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @magento/upward-js > http-proxy-middleware > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @storybook/react > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @storybook/react > @storybook/core > @storybook/core-server > @storybook/builder-webpack4 > webpack-hot-middleware > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[3/5] 🚚  Fetching packages...
warning Pattern ["@magento/pwa-buildpack@file:../pwa-studio/packages/pwa-buildpack/magento-pwa-buildpack-10.0.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-pwa-buildpack-10.0.0-d131fad903b663479e4d5fc9466c367c730b4aaa/node_modules/@magento/pwa-buildpack" as pattern ["@magento/pwa-buildpack@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/pwa-buildpack/magento-pwa-buildpack-10.0.0.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/upward-js@file:../pwa-studio/packages/upward-js/magento-upward-js-5.1.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-upward-js-5.1.0-099b900d5112c9013fdb2b2fe3df7020b9483898/node_modules/@magento/upward-js" as pattern ["@magento/upward-js@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/upward-js/magento-upward-js-5.1.0.tgz","@magento/upward-js@~5.1.0","@magento/upward-js@~5.1.0"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/babel-preset-peregrine@file:../pwa-studio/packages/babel-preset-peregrine/magento-babel-preset-peregrine-1.1.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-babel-preset-peregrine-1.1.0-7b42ce0f0407e4710a83cf24fa5f68f84355d726/node_modules/@magento/babel-preset-peregrine" as pattern ["@magento/babel-preset-peregrine@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/babel-preset-peregrine/magento-babel-preset-peregrine-1.1.0.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/pagebuilder@file:../pwa-studio/packages/pagebuilder/magento-pagebuilder-6.0.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-pagebuilder-6.0.0-4972de61883e6965bc83410f91b7874d56f5686d/node_modules/@magento/pagebuilder" as pattern ["@magento/pagebuilder@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/pagebuilder/magento-pagebuilder-6.0.0.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/peregrine@file:../pwa-studio/packages/peregrine/magento-peregrine-11.0.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-peregrine-11.0.0-c39c0242f69c389de9e313b7f63572c5333d56c2/node_modules/@magento/peregrine" as pattern ["@magento/peregrine@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/peregrine/magento-peregrine-11.0.0.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/upward-security-headers@file:../pwa-studio/packages/extensions/upward-security-headers/magento-upward-security-headers-1.0.4.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-upward-security-headers-1.0.4-668af6c9e71b893f8bf5367d76143fadd6e1020c/node_modules/@magento/upward-security-headers" as pattern ["@magento/upward-security-headers@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/extensions/upward-security-headers/magento-upward-security-headers-1.0.4.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/venia-ui@file:../pwa-studio/packages/venia-ui/magento-venia-ui-8.0.0.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-venia-ui-8.0.0-07d1f6491de2d6fd2d774a9cb5d799eafa9b46cc/node_modules/@magento/venia-ui" as pattern ["@magento/venia-ui@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/venia-ui/magento-venia-ui-8.0.0.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@magento/venia-sample-backends@file:../pwa-studio/packages/extensions/venia-sample-backends/magento-venia-sample-backends-0.0.4.tgz"] is trying to unpack in the same destination "/Users/pedrochiossi/Library/Caches/Yarn/v6/npm-@magento-venia-sample-backends-0.0.4-05838884bca8fe88e90a1b85a2ae90249cc7f2ad/node_modules/@magento/venia-sample-backends" as pattern ["@magento/venia-sample-backends@file:///Users/pedrochiossi/Dev/adobeRAP/pwa-studio/packages/extensions/venia-sample-backends/magento-venia-sample-backends-0.0.4.tgz"]. This could result in non-deterministic behavior, skipping.
[4/5] 🔗  Linking dependencies...
warning " > @magento/babel-preset-peregrine@1.1.0" has incorrect peer dependency "babel-plugin-dynamic-import-node@~2.2.0".
warning " > @magento/babel-preset-peregrine@1.1.0" has incorrect peer dependency "babel-plugin-dynamic-import-node@~2.2.0".
warning " > @magento/eslint-config@1.5.2" has unmet peer dependency "eslint-config-prettier@^6.0.0".
warning " > @magento/eslint-config@1.5.2" has incorrect peer dependency "eslint-plugin-react-hooks@^1.6.0".
warning "@storybook/react > @storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0" has unmet peer dependency "typescript@>= 3.x".
warning "@storybook/react > @storybook/react-docgen-typescript-plugin > react-docgen-typescript@2.1.0" has unmet peer dependency "typescript@>= 4.3.x".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/react > @storybook/addons > @storybook/router > @reach/router > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
warning Workspaces can only be enabled in private projects.
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 86.58s.
  ✔  Installed dependencies for 'scaffold' project
  ⚠  Created new PWA project scaffold. Next steps:

     - cd scaffold before running the below commands.

     - yarn run buildpack create-custom-origin . to generate a unique, secure custom domain for your new project.
     Highly recommended.

     - yarn run watch to start the dev server and do real-time development.

     - yarn run storybook to start Storybook dev server and view available components in your app.

     - yarn run build to build the project into optimized assets in the '/dist' directory.

     - yarn start after build to preview the app on a local staging server.

```

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by tjwiebell — DISMISSED** [review]
LGTM 👍  incredible work tracking down all those weird hoisting problems. Let's get this to QA before you pick up too many more conflicts.

**Comment by eug123** [comment]
* :white_check_mark: - Verify that the number of yarn warnings were reduced after fix.
**MFTF**
* :negative_squared_cross_mark: - Mini Shopping Cart does not disappear when navigating to Checkout page from Shopping cart page. Affected tests: `VeniaCartPageUKGuestCheckoutWithCC`, `CartPageGuestCheckout`
**Cypress**
* :negative_squared_cross_mark: - PageBuilder slider with empty autoplay speed is causing error (`slider.spec.js`)r:
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**Review by pankhurigoel — COMMENTED** [review]
Looks good to me

**Review by eug123 — APPROVED** [review]

**Comment by eug123** [comment]
* :white_check_mark:&nbsp;&nbsp;Verify that the number of yarn warnings were reduced after fix.
* :white_check_mark:&nbsp;&nbsp; MFTF
* :white_check_mark:&nbsp;&nbsp; Cypress

**Comment by drpayyne** [comment]
Thank you for the fix!

**Pull request merged**
