### PR TITLE
Cypress update tags

### PR DESCRIPTION
**Pull request by dpatil-magento**
## Description

Added @e2e tag to support testing only graphql changes

## Related Issue

Closes [PWA-2828
](https://jira.corp.magento.com/browse/PWA-2828)
## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Review by rwalter215 — APPROVED** [review]
Looks good, just update branch with latest from develop and the PR can move forward.

**Pull request merged**
