### PR TITLE
PWA-2528: Page builder product collection's price+currency is not updating on currency changes

### PR DESCRIPTION
**Pull request by michaelyu0123**
## Description
Original fix from: https://github.com/magento/pwa-studio/pull/3627

While changing currency from the header dropdown, prices in page builder product collections are not getting updated.

To reproduce:

1. Go to 'Veni Home page'
2. Change currency from header dropdown.
3. Scroll down to 'Top Sellers' section
4. You can see prices are not updated in chosen currency.

Expected behavior:

Prices should be displayed in user's preferred currency.

## Related Issue

Closes #PWA-2528

## Verification Steps

Test Plan -

- Verify the direct fix for Default store and French store
- Verify direct fix with store code url enabled
- Run existing cypress. suite (Localization test automated)

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
run cypress

**Review by anthoula — APPROVED** [review]

**Comment by ericeoeur** [comment]
✅ QA has passed, including cypress testing, for this ticket. Will be merging momentarily.

**Pull request merged**
