### PR TITLE
[Fix bug]: Submit Create Account form have not trimmed prefix/suffix space for all fields

### LINKED ISSUE #2748: [bug]: Submit Create Account form have not trimmed prefix/suffix space for all fields
**Describe the bug**
I am trying to create account. The unlucky i put many spaces to the prefix of fields then it still push to server without trim any space

**To reproduce**
1. Go to Create Account form
2. Fill some spaces at the prefix/suffix any field: First name, Last name, ..
3. Click Create an Account
4. Server response the customer data without trim space

**Expected behavior**
Client side should be trim all space at prefix/suffix of form's fields

**Screenshots**
download

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by huykon**
## Description

Currently, create account with situation fill customer information include prefix/suffix spaces then push to server without any space of those.

## Related Issue

Closes #2748.

### Verification Steps

1. Go to Create Account form.
2. Fill date include some spaces at the prefix/suffix any field: First name, Last name, ...
3. Click Create an Account.
4. Verify the system still create account with data filled with trimmed data.
5. Go to Edit Account Information to verify all fields user information don't have any space at prefix/suffix

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by sirugh — CHANGES_REQUESTED** [review]
With the account information page we used this approach but it allows a user to enter spaces before an input which will be trimmed on submit but not removed from the actual input value. You can repro this by submitting, on account info edit modal, a name with some spaces before hand, and then reopening the edit form.

One option to prevent this would be to use the `mask` property on the inputs, which actually trims the value as it is entered.

```
<div className={classes.firstname}>
    <Field id="firstname" label="First Name">
        <TextInput
            mask={value => value && value.trim()}
            field="firstname"
            validate={isRequired}
        />
    </Field>
</div>
```

However, this does prevent users from entering names with spaces in them, which may be an issue - for example, my mother's first name is actually two words with a space between them.

Would be interested in your thoughts :)

cc @tjwiebell @jimbo

**Comment by tjwiebell** [comment]
> However, this does prevent users from entering names with spaces in them, which may be an issue - for example, my mother's first name is actually two words with a space between them.
> 
> Would be interested in your thoughts :)
> 
> cc @tjwiebell @jimbo

@sirugh 
Based on existing usage in the app, I believe there's an additional prop `maskOnBlur` that would allow the multiple name use case, only applying the mask when the input loses focus.

**Comment by sirugh** [comment]
Beautiful! I tried it out and that definitely solves this case 👍 


```html
<div className={classes.firstname}>
    <Field id="firstname" label="First Name">
        <TextInput
            mask={value => value && value.trim()}
            maskOnBlur={true}
            field="firstname"
            validate={isRequired}
        />
    </Field>
</div>

**Comment by huykon** [comment]
Thanks @tjwiebell & @sirugh . I have just updated as yours recommend!

**Review by sirugh — APPROVED** [review]
Nice. We've opened an internal ticket to move the `mask` and `maskOnBlur` props to the TextInput component as default props but this solves the current bug, thanks!

**Comment by huykon** [comment]
> Nice. We've opened an internal ticket to move the `mask` and `maskOnBlur` props to the TextInput component as default props

I am ready to update that 👍

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
