### PR TITLE
AC-2489::Page title for search page not informative (Search Results)

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Reproduction Steps
search "short" - [NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(3)]

1. Execute a site search and observe the page title in the browser tab.

Actual Behavior
The search page does not have a descriptive title; its title is "Default Store View". When the page <title> of the document does not describe the topic or purpose of the page, users of assistive technology may have trouble finding content or orienting themselves.

Expected Behavior
Ensure that the value for the <title> element is updated as the page content changes and describes the page's purpose or topic in a concise matter (e.g. "Search Results -

## Related Issue

Closes #https://jira.corp.adobe.com/browse/AC-2489

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3940: AC-2489::Page title for search page not informative (Search Results)

### CODE REVIEW

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Approved

**Pull request merged**
