### PR TITLE
[Eventing] User account events

### PR DESCRIPTION
**Pull request by jcalcaben**
## Description

Dispatches the following user account events:

* `USER_SIGN_IN` whenever a user signs into the app
* `USER_SIGN_OUT` whenever a user signs out of the app
* `USER_CREATE_ACCOUNT` whenever a new user signs up

## Related Issue

Closes PWA-2784

## Acceptance

Any core developer

@jimbo  (optional)

### Verification Stakeholders

Any core developer

## Verification Steps

See linked issue

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by michaelyu0123 — CHANGES_REQUESTED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
@jcalcaben Please check following - 
1. Guest User Order Confirmation Page >> Create Account
<a href="https://gyazo.com/eab44bfd3ee93bac1bd4169a99269e2d">Image from Gyazo</a>
2. Checkout Flow >> Create Account
<a href="https://gyazo.com/7dc7ce8845b3893b35e63c3296ddd787">Image from Gyazo</a>
3. Auth user > Account Information > `Change password` event not tracked.

Also need some help on checking `signout` payload, as soon as user signout, event created but page reloads so unable to check payload.

**Comment by dpatil-magento** [comment]
run cypress

**Review by michaelyu0123 — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved. Just waiting for confirmation on `Auth user > Account Information > Change password event not tracked.`

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Review by dpatil-magento — APPROVED** [review]

**Pull request merged**
