### PR TITLE
[Fix bug]: Clicking on Label should focus Input

### LINKED ISSUE #2773: [bug]: Clicking on Label should focus Input
**Describe the bug**
Add a product to the cart, head to checkout. Clicking on any label should put the focus on the associated input.

**To reproduce**
1. add product to cart
2. navigate to checkout
3. click on Email
image

**Expected behavior**
Keyboard focus on associated for input field

**Screenshots**
image

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version: develop
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by huykon**
## Description

Add a product to the cart, head to checkout. Clicking on any label should put the focus on the associated input.

## Related Issue

Closes #2773.

### Verification Steps

1. Add any product to cart.
2. Navigate to checkout page.
3. Make sure when you click to label in email, first name, last name, ... on form, the cursor mouse will be focused to refer.

## Checklist

- [x] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by schensley** [comment]
@huykon Very nice, things work well, EXCEPT in the Payment section if you un-check "Same as Shipping Address" to reveal the Billing Address form.  Please have a look at that. Otherwise, everything looks good.

**Comment by huykon** [comment]
@schensley please recheck again

**Comment by schensley** [comment]
@huykon Yes, it works. Great work! Thanks, UX approved.

**Review by sirugh — CHANGES_REQUESTED** [review]
`zip/postcode` is still problematic. I believe you need to provide an `id` within the `Postcode` component.

**Review by sirugh — DISMISSED** [review]

**Comment by dpatil-magento** [comment]
@huykon In Checkout First Step (before Review Order) Auth Shipping Edit overlay > cursor does not focus field`Country`, `Street Address 2`,  `City` `ZIP / Postal Code` on clicking respective labels. 

<a href="https://gyazo.com/f877adff26a010700a95aaf67c19a4c6">Image from Gyazo</a>

**Comment by dpatil-magento** [comment]
QA Approved.

**Review by sirugh — APPROVED** [review]
Using the classname as the id should solve the issues Dev identified, however we may run into a similar problem in the future if a form has two of these fields, but I think that was already a concern before this PR anyways, so not something to worry about here.

**Comment by supernova-at** [comment]
Crap, I'm too late. 

Since our pattern is to use the same classname ("root") in all of our components, this is going to end up giving the same `id` to multiple components in the same form.

For example, it is very common to have `Country`, `Region` and `Postcode` components in an address form. All of those inputs now have `id="root"`.

Best practice for accessibility and cross-browser consistency is not to have multiple elements with the same `id`.

**Comment by brendanfalkowski** [comment]
Just chiming in, the first modification we did to forms was requiring `Field` to have an `id` prop, which can be different than the `field` prop. This allows duplicate instances in the DOM from colliding. We created a `Label` component that `Field` always uses and associates based on `id` not `field`. This forces the developer to choose the ID deliberately to avoid conflicts.

**Comment by huykon** [comment]
@supernova-at @brendanfalkowski so will need to update anything?

**Comment by sirugh** [comment]
> @supernova-at @brendanfalkowski so will need to update anything?

No I don't think so, but if anyone wants to put more than one of these components in a single form we will have to update to allow a custom id as Brendan suggested.

**Pull request merged**
