### PR TITLE
AC-2790::No visual indication of focus on buttons.

### PR DESCRIPTION
**Pull request by glo82145**
## Description

Description
No visual indication of focus on buttons.

Environment
Adobe Magento - LUMA

Context
Windows 10; Chrome 88;

Reproduction Steps
Locations (representative sample):

Search Results
Sub-Category landing page
Mini Cart
Checkout - Shipping
Checkout - Review & Payments
My Account
1. Press Tab to move through the content.
For close button:
2. When keyboard focus is on "X" of one of the Compare Products, press Enter or Space to activate it.

Actual Behavior
There is no visual indication of keyboard focus when using TAB or SHIFT+TAB to navigate through controls of the website. Examples include:

Module 02 - Search Results:
Page selection buttons (which includes Next ">" and Previous "<")
Close button "X" on dialogs

Module 03 - Sub-Category landing page:
Page selection buttons (which includes Next ">" and Previous "<")
Close button "X" on dialogs

Module 05a - Mini Cart:
Close button "X" on dialog

Module 06a - Checkout - Shipping:
Close button "X" on "Sign In" dialog

Module 06b - Checkout - Review & Payments:
Close button "X" on "Sign In" dialog

Module 08 - My Account:
Close button "X" on dialog

Keyboard-only users can become disoriented when focus is not indicated.

Expected Behavior
Ensure that when actionable elements receive focus, that it appears on screen and that a visible focus indicator is present.

## Related Issue

Closes https://jira.corp.magento.com/browse/AC-2790
Closes https://jira.corp.adobe.com/browse/PWA-2972

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3939: AC-2790::No visual indication of focus on buttons.

### CODE REVIEW

**Comment by anthoula** [comment]
@magento create issue from PR

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run pr-deploy

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
@glo82145 Fix does focus Next Page (>), Previous Page (<), First Page (<<)and Last Page (>>) buttons but it still lacking to focus page numbers (1, 2)

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
QA Approved.

**Review by anthoula — APPROVED** [review]

**Pull request merged**
