### PR TITLE
BUG#PWA-3063 No proper screen reader announcements are for the option…

### PR DESCRIPTION
**Pull request by RaghavendraTirumalasetti**
…s related to size

## Description

Pre-Conditions:

Have Magento 2.4.6alpha2 EE setup with [Venia configured](https://wiki.corp.adobe.com/display/ACRQ/PWA+Studio+Set+Up+in+Local).
Make sure Venia has at least one customer login account to login into the Venia front end.
Make sure Screen reader installed and enabled.
Steps to Reproduce:

Open Venia front end in any browser 
Navigate by using tab button > go tops > select any product  like carina cardigan 
On pressing tab it should navigate to the fashion size using screen reader enabled 
click and select a particular size 
 

Expected result:
1. On pressing tab and selecting any size it should announce as Fashion size L button 
2. If we select the size, then the announcement should be as Fashion size L button selected

Actual result:
1. On pressing tab and selecting any size it is announcing as  L button
2. Even after selecting L size, it just says L button

## Related Issue

Closes #https://jira.corp.adobe.com/browse/PWA-3063.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by glo82145 — DISMISSED** [review]

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-mobile

**Comment by glo42707** [comment]
run lighthouse-desktop

**Review by glo42707 — DISMISSED** [review]
Proxing approval for @glo82145

**Pull request closed without merging**
