### PR TITLE
[PWA-653] React Refresh

### LINKED ISSUE #2391: [feature]: React-refresh to improve reloading components at development
**Is your feature request related to a problem? Please describe.**
PWA Studio currently uses `react-hot-loader` for reloading components, styles when developing.
React introduced `fast refresh` last year to improve browser reloading. We have to remove react-hot-loader and add react-refresh improving developer experience, also hot loader will be deprecated in favor of react-refresh

**Describe the solution you'd like**
Update dependencies to react-refresh 

**Additional Context**
I just came to know about it. This is new and many have not adopted to it, **may not be a requirement for PWA studio at this time**, opening this to watch for future improvements

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [ ] `venia-ui`
- [X] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [X] `create-pwa`

### PR DESCRIPTION
**Pull request by evan-burrell**
## Description

Implement React Refresh using [@pmmmwh/react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin)

## Related Issue

Closes #2391.

### Verification Stakeholders
@dani97 
@Jordaneisenburger 

### Verification Steps

1. Ensure that you have a valid custom origin setup
2. Run `yarn install`
3. Run `yarn watch:venia`
4. Open the browser and code editor in a side by side environment, edit a component such as `Main.js` in `venia-concept`, adding `<div>Hello</div>` above the header, save and see the changes applied.
5. Edit the component to say `<div>Hello there</div>` and see the changes applied without a full page refresh.
6. Generate an error by not closing the tag `<div>Hello there<div>`, see error message **displayed.**

## Screenshots / Screen Captures (if appropriate)
React Refresh

Error Messaging
image

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2609.pwa-venia.com : LH Performance Expected 0.85 Actual 0.34, LH Accessibility Expected 1 Actual 0.97, LH Best Practices Expected 1 Actual 0.92, WPT Cache Expected 90 Actual 39.333333333333
https://pr-2609.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.92
https://pr-2609.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.41, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92, WPT Cache Expected 65 Actual 50

**Comment by evan-burrell** [comment]
@jimbo Happy to help out, it's a great project. I believe we need to keep the `hot: true` in the PWADevServer. You can double check this by removing it and seeing that the full page reloads rather than just the component that you are targeting. I should have been more clear in my original repo steps. In order to trigger the error message, I was running `yarn watch:venia` without the custom origin setup, by visiting `0.0.0.0:10000` I was able to get the error for `window.caches`since chrome only supports window.caches over `https`. If you don't have a closing tag, then it should just be a white screen with an error message in the console.

**Comment by dpatil-magento** [comment]
@jimbo @evan-burrell Verification steps look good, but m seeing issue on running `yarn storybook:venia`, please take a look -

image

**Comment by jimbo** [comment]
> @jimbo @evan-burrell Verification steps look good, but m seeing issue on running `yarn storybook:venia`, please take a look

Ah, I overlooked that for sure. It looks like even the next major version of Storybook (`6.x`) doesn't support `react-refresh` yet, so we're going to have to figure out how to make it work. I'm not sure what that'll take, but some things to explore here:

- maybe restore `react-hot-loader` as an additional dependency?
- maybe exclude `ReactRefreshWebpackPlugin()` from our Storybook webpack config?
- maybe restore `module.hot.accept()` to `index.js`?

**Comment by evan-burrell** [comment]
@jimbo Looks like when storybook compiles it uses the `babel.config.js` that is in the root of the project. Since this includes the `react-refresh` plugin, just needed to require the webpack plugin in storybook webpack configuration.

Storybook React Refresh

**Comment by dpatil-magento** [comment]
@jimbo @evan-burrell Tried to scan through the project packages and found one more - `yarn workspace @magento/venia-styleguide run start`  loads blank page.

**Comment by evan-burrell** [comment]
> @jimbo @evan-burrell Tried to scan through the project packages and found one more - `yarn workspace @magento/venia-styleguide run start` loads blank page.

Should be good to go now as well.

**Comment by dpatil-magento** [comment]
@evan-burrell You are too fast ;) , thanks!....I suppose add one more observation :( -  The scaffolding `yarn watch` - console error exists on `develop` as well but app works fine and on this PR app throws same error on UI - 

Steps - 
1. `DEBUG_PROJECT_CREATION=true packages/pwa-buildpack/bin/buildpack create-project scaffold-test-1 --template "venia-concept" --name "scaffold-test-1" --author "test123 <tester@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "yarn"`
2. `cd scaffold-test-1`
3. `yarn watch`


image

**Comment by evan-burrell** [comment]
That's an interesting one, I'd like to see how you would want to progress on this one. There is an option to disable the overlay in the webpack plugin, however that would disable them across the entire development process, which I'm not sure is what you want to achieve.

Side note on the error itself. This is our number one error in production for the PWA studio application we are running. Believe this just stems from chrome not allowing `window.caches` if it is not `https`, is it worth opening an issue around it?

Happy to proceed however you'd like.

**Comment by jimbo** [comment]
> Side note on the error itself. This is our number one error in production for the PWA studio application we are running. Believe this just stems from chrome not allowing window.caches if it is not https, is it worth opening an issue around it?

Yeah, from everything I can see, it looks like this error is related only to `https` and unrelated to this PR. I think this is good.

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
