### PR TITLE
Track Carts Operations

### PR DESCRIPTION
**Pull request by fnhipster**
## Description

As a merchant, I want to be able to track add to cart, update cart item, and remove from cart events.

## Related Issue

Closes [PWA-2095](https://jira.corp.magento.com/browse/PWA-2095)

## Acceptance

1. Add to cart event is tracked whenever a user adds a product to their cart with the following attributes
2. Update cart item event is tracked whenever a user updates a product in their cart (changes options or quantity)
3. Remove from cart event s tracked whenever a user removes a product from their cart
4. Example extension subscribes to the events and has events available for processing 

Dispatch Schema
```
type: 'CART_ADD_ITEM' | 'CART_REMOVE_ITEM' | 'CART_UPDATE_ITEM', 
payload: { 
  cartId: string
  sku: string 
  name: string
  priceTotal: number
  currencyCode: string   
  selectedOption: { attribute: string; value: string; }[] | null
  quantity: number
} 
```

##### Add to Cart
1. Add an item to your cart
    1. PageBuilder Gallery (Simple Product Only, since other product types will be redirected to the Product Details page)
    2. Product List (Simple Product Only, since other product types will be redirected to the Product Details page)
    3. Product Details Page
    4. Wishlist (as a registered user)
2. Open browser console and verify that the sample extension logged the addToCart event (with its contextual data)

##### Update item in Cart
1. Update an existing item in your cart by changing its configurable options or its quantity
    2. Cart Page
2. Open browser console and verify that the sample extension logged the updateCartItem event (with its contextual data)

##### Remove from Cart
1. Remove an item from your cart
    1. Mini-cart
    2. Cart Page

###### New Guest Cart
1. Complete the checkout flow
2. Add an item to cart (receives a new cart id)
3. Open browser console and verify that the sample extension logged the addToCart event (with its contextual data) and has the correct (new) cart id

###### Authorized to Guest Cart
1. Sign in
2. Add some products to your cart and note your cart id (let's call this "Cart ID A")
3. Sign out
4. Add an item to cart (receives a new cart id. Let's call this "Cart ID B")
5. Open browser console and verify that the sample extension logged the addToCart event (with its contextual data) and that is has the correct cart id ("Cart ID B")

###### Merge Cart
1. Add item to cart as Guest
2. Open browser console and verify that the sample extension logged the addToCart event (with its contextual data)
3. Sign In to account
4. Add item to cart as signed in user
5. Open browser console and verify that the sample extension logged the addToCart event (with its contextual data)

## Checklist

- [x] I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by michaelyu0123 — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
@fnhipster  All flows looks good except removing an item from cart by entering qty as zero. In this case its triggering `Update Cart` instead of `Remove Cart`

<a href="https://gyazo.com/f0902949b0801c8a68836ca6623aed6c">Image from Gyazo</a>

**Comment by fnhipster** [comment]
@dpatil-magento, good catch! Fixed.

**Review by dpatil-magento — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
