### PR TITLE
PWA-2322: Update SelectedConfigurableOption GraphQL fields

### PR DESCRIPTION
**Pull request by DiegoBezerra89**
## Description

Update SelectedConfigurableOption GraphQL fields, and updated tests.

## Related Issue

[PWA-2322](https://jira.corp.magento.com/browse/PWA-2322)

## Verification Steps

Test Plan

- As a guest, include a product on your cart, go to checkout, create a new account, and proceed to checkout.
Find the "GetCartDetailsAfterCheckout" call to GraphQL in the browser network tab
In the "Payload" tab, click "view decoded":
 - this is bad: 
 `ConfigurableCartItem {
         configurable_options{
                 id
                 option_label 
                 value_id
                 value_label
         }
}`
- this is good:
`ConfigurableCartItem {
         configurable_options{
                 configurable_product_option_uid
                 option_label 
                 configurable_product_option_value_uid
                 value_label
         }
}`

- As a guest, include a product on your cart, sign in.
Find the "GetCartDetailsAfterSignIn" call to GraphQL in the browser network tab
In the "Payload" tab, click "view decoded":

- this is bad: 
 `ConfigurableCartItem {
         configurable_options{
                 id
                 option_label 
                 value_id
                 value_label
         }
}`

- this is good
`ConfigurableCartItem {
         configurable_options{
                 configurable_product_option_uid
                 option_label 
                 configurable_product_option_value_uid
                 value_label
         }
}`

So either on cloud or local hit all the changed area above in 12.1 (master) and then run staging server with this pr and check all areas in new tab of same browser. Details steps on upgrade test can be found here
https://jira.corp.magento.com/browse/PWA-1418

## Checklist

-   I have added tests to cover my changes, if necessary.
-   ~~I have added translations for new strings, if necessary.~~
-   ~~I have updated the documentation accordingly, if necessary.~~

### CODE REVIEW

**Review by mikhaelbois — DISMISSED** [review]
LGTM ✅

**Comment by dpatil-magento** [comment]
@DiegoBezerra89 Hope below area is not part of this PR - 

image

**Review by ericeoeur — APPROVED** [review]
LGTM

**Comment by ericeoeur** [comment]
Test plan and upgrade flow have both passed. Will be merging this ticket momentarilly.

**Pull request merged**
