### PR TITLE
Update markdown tree formatting within CREATE_RELEASE_NOTES.md

### PR DESCRIPTION
**Pull request by bdenham**
## Description

Fixed formatting of markdown trees in release notes process documentation.

## Related Issue

Closes #NAN

## Acceptance

@glo42707 

### Verification Stakeholders

@glo42707 

## Verification Steps

Make sure the markdown directory trees are formatted correctly.

### CODE REVIEW

**Review by glo82145 — APPROVED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Review by glo42707 — COMMENTED** [review]
Approved

**Review by glo42707 — DISMISSED** [review]
Approved

**Comment by dpatil-magento** [comment]
run lighthouse-desktop

**Comment by dpatil-magento** [comment]
run lighthouse-mobile

**Review by dpatil-magento — APPROVED** [review]
re-approving as base changed

**Pull request merged**
