### PR TITLE
Add typescript declaration files

### LINKED ISSUE #2171: [feature]:  Create an own @types package that contains type definitions
**Is your feature request related to a problem? Please describe.**

To support **TypeScript** it is necessary to have an own **types package** for `peregrine` and `venia-ui`.  React and other Libraries have an own **@types** package that holds the type definition.
 

**Describe the solution you'd like**
I want to use *TypeScript* for own components that based on `venia-ui` but then I also need to write my own *types*

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by paales**
## Description

To get a better grasp on how adding TypeScript would look like for pwa-studio and how to keep maintenance low, I've created this PR. I'm willing to make changes if needed and maybe move from a .sh file to some js based script.

## Related issue
Closes #2171

### Verification Stakeholders
Dunno

### Specification
Dunno

### Verification Steps
1. Use packages
2. Enjoy TypeScript auto completion

## Checklist

- [x] I have added tests to cover my changes, if necessary.
- [ ] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2471.pwa-venia.com : LH Performance Expected 0.85 Actual 0.57, LH Best Practices Expected 1 Actual 0.92
https://pr-2471.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.36, LH Best Practices Expected 1 Actual 0.92
https://pr-2471.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.49, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92

**Comment by paales** [comment]
Hi Jimbo, thanks for your reply!

The current definition files are _all_ auto generated. By rerunning the shell script, all the definitions get cleaned up and recreated.

_To improve the quality of the typescript definition files, the developers can improve the jsdoc stuff and it will automatically generate different definition files._

I've mainly created to PR to get the discussion rolling. The current implementation is based on a shell script, but if you guys rather have a javascript file, that would be fine as well, shouldn't be too difficult.

**Comment by larsroettig** [comment]
@paales I think we should publish an optional NPM packed for each what do you can install in your over yarn or NPM not 
maintain them in main repo

**Comment by larsroettig** [comment]
@paales I think we should create an external` @types` packaged as already mention original ticket.  The Core Team don't want overhead of TypeScript in main repository. It is hard learn curve from `jsx` to `tsx to get a benefit from TypeScript. Also, I see Problem who will generated new types for currently development Version. We need second  Regression Step what verify that our auto generated API works well. ln my Experience Auto generated Types don't have big benefit also TS 4 should understand JavaScript docs.     

I think we should **not** blow up  installed packaged size for my bee 5-10% what want to Build things based on TS. 

kind regards, 

Lars

**Pull request closed without merging**
