### PR TITLE
errorhandler is only used in non-production envs

### PR DESCRIPTION
**Pull request by fooman**
## Description

When bundling upward-js in production mode it will stumble across errorhandler which has absolute references to `public/style.css` and `public/error.html` which are not findable.

## Related Issue

Closes #ISSUE_NUMBER.

## Acceptance 
@zetlen 
### Verification Steps

1. Upward in dev mode yarn watch:all
2. Upward in prod mode yarn venia:stage

## Checklist

* I have updated the documentation accordingly, if necessary.
[ ] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by sirugh** [comment]
From `errorhandler`'s docs:

>This middleware is only intended to be used in a development environment

So this seems reasonable :) I'd be happy to approve it if you want to mark it ready for review. Wasn't sure if you had other things you wanted to do.

**Comment by fooman** [comment]
Thanks @sirugh. I was still trying to come up with verification steps to a show the issue in a minimal fashion but will make it generic for the moment.

**Comment by sirugh** [comment]
Oh yes, accurate verification steps showing the issue before/after would be helpful! Thanks :)

**Comment by fooman** [comment]
Unfortunately having trouble exposing this issue by itself. It manifested itself trying to bundle for a node target. I'll close this for now - it might come up as part of #2407

**Pull request closed without merging**
