### PR TITLE
Adding .gitignore to the files comming from @magento/pwa

### LINKED ISSUE #1931: [feature]: Provide .gitignore file when setting up new pwa using npm init @magento/pwa
Hi guys, 

I just set up a new pwa project using `npm init @magento/pwa` and noticed that the .gitignore file is missing.

It would be nice if this comes by default :) 

Thx in advance!

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by LucasCalazans**
## Description

Adding a negative rule into `.npmignore` to accept `.gitignore` when we're using the `npm init @magento/pwa`

## Related Issue
Closes #1931.

### Verification Steps
1. Clone this repo.
2. Go to the venia-concept folder
3. Run `npm pack` (https://docs.npmjs.com/misc/developers#testing-whether-your-npmignore-or-files-config-works)
4. Unpack the `tgz` file and see the `.gitignore` file in there

Please, see the npm documentation about the .npmignore to more details - https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

## Screenshots / Screen Captures

print

## Checklist
* I have updated the documentation accordingly, if necessary.
* I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by sirugh** [comment]
This works but @zetlen will need to jump in to say whether or not this is the approach we want going forward. In the scaffolding code, namely `createProject.js` I can see that we're trying to do _something_ with the gitignores automatically and it may be that the scaffolding code has a bug in it that isn't copying.

**Comment by LucasCalazans** [comment]
Hey @sirugh thanks for your answer.

Are you referring to this function? https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/Utilities/createProject.js#L25

If yes it's just getting the .gitignore content to ignore these files/folders.

There is another thing to say. If we use `./packages/create-pwa/bin/create-pwa` it will works because it will execute with its own instance, the error is just happening when using the `npm init @magento/pwa` because at this point `npm` will look for wich files should be downloaded when `https://registry.npmjs.org/@magento/venia-concept/-/venia-concept-4.1.0-dev.5.tgz` is called.

It is just a info that I forgot to say.

**Comment by zetlen** [comment]
@LucasCalazans Thank you, I think I see what you're saying. It sounds like you don't want the venia `.gitignore` file to be part of a scaffolded project based on Venia.

We need to understand why not. Your repro shows us that the `.gitignore` exists, but is there a specific bug that you're experiencing because the `.gitignore` file is there?

**Comment by LucasCalazans** [comment]
Hey @zetlen, actually it's the opposite, we need the `.gitignore` when we're using the `npm init @magento/pwa` because it comes with important rules to the new project.

Currently, it's not coming with the bundle. The rule that I've added is a negative for .gitignore (Forcing npm to add .gitignore to the bundle)

**Comment by zetlen** [comment]
Oh, sorry! I misread the ticket. I'll rebase this branch, add a version label and review.

**Pull request merged**
