### PR TITLE
update cypress

### PR DESCRIPTION
**Pull request by dpatil-magento**
## Description

Improve cypress build time on CI and separate Functional and Snapshot tests for more control.  

## Related Issue

Closes https://jira.corp.magento.com/browse/PWA-2578.

#### Test scenario(s) for direct fix/feature
1. `run cypress` should still work and overall build time to reduce from 20min to around 10mins.
NOTE -  In follow up ticket more changes to come where Functional and snapshot can be run together or separate. 
## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by ericeoeur — APPROVED** [review]
approved

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress

**Review by ericeoeur — APPROVED** [review]
✅  LGTM

**Pull request merged**
