### PR TITLE
BUG#3982 Add uid instead of id in noProductsFound.js

### LINKED ISSUE #3981: [bug]: Add uid instead of id in noProductsFound.js
**Describe the bug**

We have already deprecated id field and we will replace it with uid changes but there is still missing one place in category page if there is no products for category then below component is called that used category.id instead of category.uid. due to id is not there in object that gives console warning for key.

**@magento/venia-ui/lib/RootComponents/Category/NoProductsFound/noProductsFound.js
https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Category/NoProductsFound/noProductsFound.js#L31

Only changes of UID will automatically gets the latest changes as per unique identifier.

**To reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device <e.g. iPhone6, PC, Mac, Pixel3>:
-   Browser <e.g. Chrome, Safari>:
-   Browser Version <e.g. 22>:
-   Magento Version <e.g Adobe Commerce 2.4>:

< -->

**Please let us know what packages this bug is in regards to:**

-   < > `venia-concept`
-   <x> `venia-ui`
-   < > `pwa-buildpack`
-   < > `peregrine`
-   < > `pwa-devdocs`
-   < > `upward-js`
-   < > `upward-spec`
-   < > `create-pwa`

### Test Plan 
- Verify Category page loads with. products
- Create an empty category and navigate to it and verify UID is present instead of ID.
- On category apply filters and verify UID is present when filter results in products and also when filters results in no products.
- Verify same on Search pages for category filter with and without filters
- Verify existing cypress test CI job passes.
NOTE - No browser or device testing needed for this pr given no UI changes

### PR DESCRIPTION
**Pull request by dupadhyay3**
## Description

We have already deprecated id field and we will replace it with uid changes but there is still missing one place in category page if there is no products for category then below component is called that used category.id instead of category.uid.  Id is not there in object that gives console warning for key.
So we have updated from id to uid that gives unique value for each category and resolved the browser console warning.

## Related Issue

Closes #3981.

## Screenshots / Screen Captures (if appropriate)

Desktop-screenshot

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dupadhyay3** [comment]
[m2-community-project](https://github.com/apps/m2-community-project)

**Comment by dupadhyay3** [comment]
Hello @Jordaneisenburger ,

Can you please check this PR that have only one check left.

**Comment by dupadhyay3** [comment]
Hello @anthoula,

Can you please check this too?

**Review by anthoula — APPROVED** [review]

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
QA Aprroved

**Pull request merged**
