### PR TITLE
Support GIF files in Webpack config

### PR DESCRIPTION
**Pull request by brendanfalkowski**
## Description

Adds support for .gif files in Webpack config.

We imported a module that contains some GIF files, and buildpack threw on error about this.

### Verification Steps

1. Add a GIF file to your project.
2. Import it in any component.

## Screenshots / Screen Captures (if appropriate)

Screen Shot 2020-09-17 at 5 25 39 PM

## Checklist

- [ ] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by jimbo — APPROVED** [review]
Yeah, it's odd that all of the other regular expressions include `gif`, but this one doesn't. Approved.

Also, I see you alphabetizing things.

alphabetize

**Comment by brendanfalkowski** [comment]
^^^ How I see myself alphabetizing things.

And how I actually look alphabetizing things:

giphy

**Comment by tjwiebell** [comment]
Tracking internally with [PWA-954](https://jira.corp.magento.com/browse/PWA-954).

**Review by revanth0212 — APPROVED** [review]

**Comment by tjwiebell** [comment]
Added a gif to local `develop` branch to confirm bug and got the dreaded white screen of death; checking out this branch the asset now display without error.

QA Pass ✅

**Pull request merged**
