### PR TITLE
AC-2479::Visual text label does not match accessible name. (Global He…

### PR DESCRIPTION
**Pull request by glo82145**
…ader)

## Description

Reproduction Steps
[NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(2)]

1. With JAWS operating, press Tab to move through content.

Actual Behavior
The following buttons have visible text that does not match the button's accessible name:

Header - Visible label "Sign In"; Accessible name "Toggle My Account Menu"
Navigation Menu - Visible label "Sign In"; Accessible name "Account Sign In" (Note - this instance is advisory only since the accessible name contains the visible label text; however it is preferable for the accessible name to start with the visible text.)
When the accessible name of a control does not include the visible text label, users of speech input software may be unable to access the control directly.

Expected Behavior
Ensure the visible text label of a control is included in the control's accessible name. It is highly recommended that the accessible name start with the visible label text.

## Related Issue

Closes #https://jira.corp.adobe.com/browse/AC-2479

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3989: AC-2479::Visual text label does not match accessible name. (Global He…

### CODE REVIEW

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
@magento create issue from PR

**Comment by anthoula** [comment]
Hi @glo82145 - This looks good, thank you. Would you look at & resolve the conflicting files please?

**Review by anthoula — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress @snapshot

**Comment by dpatil-magento** [comment]
QA Approved.

**Pull request merged**
