### PR TITLE
[PWA-666]: Update Hastily image optimizer

### LINKED ISSUE #2448: [bug]: Upward crashes on Image Optimization
**Describe the bug**
When turning on the PWA Image optimization, the Upward Server crashes as soon as someone tries to load any image.

Error log shows:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: Input buffer contains unsupported image format
Emitted 'error' event at:
    at sharp.pipeline (/usr/src/app/node_modules/sharp/lib/output.js:707:18)
error Command failed with exit code 1.
```

**Expected behavior**
Image is shown to the customer and Optimized for the PWA.

**Please complete the following device information:**
 - PWA Studio Version: 6.0.1
 - NPM version `npm -v`: v6.13.4
 - Node Version `node -v`: v10.18.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

### PR DESCRIPTION
**Pull request by zetlen**
## Description

While reproducing #2448 we discovered that the image optimizer middleware fails when the underlying proxy that serves images:
- is experiencing SSL errors and not delivering valid responses
- was incorrectly configured to apply compression (gzip or brotli) to binary resources such as images

Both of these situations caused unhandled exceptions in the middleware, which logged untraceable errors.

### Fix upward-js ProxyResolver `ignoreSSLErrors` option

The ProxyResolver `ignoreSSLErrors` option should never be used in production, but it is an often useful workaround in development and staging, where SSL certificates are frequently invalid because of expiration dates, alternative names, or other small issues. The `upward-js` ProxyResolver `ignoreSSLErrors` implementation would ignore unrecognized certificate errors, but not any other kinds of SSL errors--such as a mismatched alt name due to proxied host headers. This PR fixes that by using a specially configured Node `httpsAgent`.

### Update Hastily to v0.4.6

Hastily would crash when trying to optimize a gzipped image stream. It's against best practices to configure a web server to gzip images, so rather than supporting it, Hastily now bypasses gzipped images and logs an informative error message. The real solution to #2448 is to reconfigure nginx (or whatever your web server uses) not to gzip images or other binary files:

From https://www.itworld.com/article/2693941/why-it-doesn-t-make-sense-to-gzip-all-content-from-your-web-server.html 
>You should not allow your web server to compress image files or PDF files. The reason being that these files are already compressed and by compressing them again you’re not only wasting CPU resources but you can actually make the resulting file larger by compressing them again.

From https://www.fastly.com/blog/new-gzip-settings-and-deciding-what-compress :
>When it comes to images, it’s generally assumed that content types starting with image/ should never be compressed.
 
From https://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/ :
>Most images, music and videos are already compressed. Don’t waste time compressing them again. In fact, you probably only need to compress the “big 3” (HTML, CSS and Javascript).

## Related Issue

Closes #2448.

### Verification Stakeholders
@dpatil-magento @Jordaneisenburger 
### Verification Steps

1. Check out and `yarn install`.
2. Configure a local Magento instance to gzip image responses:
    1. If using Apache, add instructions to `.htaccess` in the Magento root. If using valet-plus, [here are instructions for finding nginx.conf](https://github.com/laravel/valet/issues/284).
    1. Use [the directives described here](https://varvy.com/pagespeed/enable-compression.html), making sure to add all MIME types for images. 
3. Run `yarn build && yarn stage:venia` and watch the logs.
4. Attempt to load the home page. Observe that hastily is logging error messages about the gzipped images, and the images themselves are coming through un-optimized.

## Checklist

- [x] I have added tests to cover my changes, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by devops-pwa-codebuild** [comment]
**Performance Test Results**

The following fails have been reported by WebpageTest. These numbers indicates a possible performance issue with the PR which requires further manual testing to validate.

https://pr-2535.pwa-venia.com : LH Performance Expected 0.85 Actual 0.51, LH Best Practices Expected 1 Actual 0.92, WPT Cache Expected 90 Actual 83.333333333333
https://pr-2535.pwa-venia.com/venia-tops.html : LH Performance Expected 0.75 Actual 0.35, LH Best Practices Expected 1 Actual 0.92
https://pr-2535.pwa-venia.com/valeria-two-layer-tank.html : LH Performance Expected 0.8 Actual 0.4, LH Accessibility Expected 0.9 Actual 0.89, LH Best Practices Expected 1 Actual 0.92, WPT Cache Expected 65 Actual 50

**Comment by tjwiebell** [comment]
@zetlen - We merged a community PR which supports http backends that introduced a tiny conflict, if you could please resolve.

Was also curious if we should fix the logic in `packages/pwa-buildpack/lib/Utilities/graphQL.js`? At some point we just suppressed all SSL errors for build time GraphQL calls, which might not be the ideal solution anymore.

**Comment by zetlen** [comment]
@tjwiebell The `graphQL.js` module runs separately from UPWARD, so I don't think we can reproduce this logic in it. However, that module needs to be renamed so it's clearer what it's for: build-time autoconfiguration from Magento backend settings, over GraphQL.

Right now, that module correctly calls fetch in both HTTP and HTTPS contexts, and I don't believe it ever suffered from the same issue as the ProxyResolver, because it was always creating its own agent.

**Comment by zetlen** [comment]
Updated hastily to `v0.4.7` @sirugh I'll push a test suite

**Comment by sirugh** [comment]
Just to loop back, I finally got my local environment set up and was able to verify that hastily does indeed log errors and not serve gzipped images.

**Comment by dpatil-magento** [comment]
@zetlen When `IMAGE_OPTIMIZING_ORIGIN` set to `auto` and `onboard` errors are logged but `backend` does not, expected?

`IMAGE_OPTIMIZING_ORIGIN=backend`  request -

image

**Comment by dpatil-magento** [comment]
> @zetlen When `IMAGE_OPTIMIZING_ORIGIN` set to `auto` and `onboard` errors are logged but `backend` does not, expected?
> 
> `IMAGE_OPTIMIZING_ORIGIN=backend` request -
> 
> image

Confirmed with @zetlen and its expected.

**Pull request merged**
