### PR TITLE
Removes Now.sh pipeline

### LINKED ISSUE #1546: [CICD] - Retire now.sh for pwa-studio
As we have AWS instances running. We can retire now.sh deployments. 

AWS - 
`master` - https://prodtest.pwa-venia.com/
`develop` - https://develop.pwa-venia.com/
Individual PR's - https://PR-NUMBER.pwa-venia-staging.com/ example - https://pr-1536.pwa-venia-staging.com/

### PR DESCRIPTION
**Pull request by supernova-at**
## Description

We have AWS deploying on a per-PR basis, so we no longer need the Now.sh pipeline. Our https://veniapwa.com demo site has been redirected to the AWS deployment of `master`.

## Related Issue

Closes #1546.

## Verification Steps

1. Verify that `now.sh`-related code doesn't appear anywhere in the codebase
1. Verify that the `Now` GitHub integration no longer appears on PRs

## Checklist

* I have updated the documentation accordingly, if necessary.
* I have added tests to cover my changes, if necessary.

- [x] Remove the `Magento` team from `Now.sh` website
- [x] @mmansoor-magento to remove `Now` GitHub App from `magento` organization

### CODE REVIEW

**Comment by dpatil-magento** [comment]
`veniapwa.com`  equivalent AWS `magento.pwa-venia.com`
`magento-venia-develop.now.sh` equivalent AWS `develop.pwa-venia.com`

**Comment by supernova-at** [comment]
#1595 is in! This issue is unblocked and has been updated.

Good news and bad news though:

**Good News**:

The deployments are working. If you hit https://pwa-studio.supernova-at.now.sh/ you do see the Venia app shell.

**Bad News**:

Screen Shot 2019-09-03 at 2 21 08 PM

The app is repeatedly attempting to hit `/rest/V1/guest-carts` at the deployment URL (ex: `https://pwa-studio.supernova-at.now.sh/rest/V1/guest-carts`), not the `MAGENTO_BACKEND_URL`.

We have followed the documentation to provide environment variables at both [build](https://zeit.co/docs/v2/build-step/#providing-environment-variables) and [run](https://zeit.co/docs/v2/serverless-functions/env-and-secrets/#providing-environment-variables) time via our `now.json` file.

I'm stuck 😢

**Comment by zetlen** [comment]
That should work though. UPWARD ought to properly proxy that request to MAGENTO_BACKEND_URL. But you can also reproduce that proxying behavior before it hits upward-js. I think you might need to add the `routes` section of `now.json` back. Without that, I'm not sure how we're making every single request resolve to index.html!

**Comment by supernova-at** [comment]
Update: following a team meeting this PR has been repurposed back to removing Now.sh entirely.

If / when we want a deployment target other than the Magento Cloud we can add it back.

**Pull request merged**
