### PR TITLE
PWA-2295: Images to include dimensions

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Added shimmering effect for image content type
- Added test coverage for image shimmering effect

## Description

As a merchant I want to benefit from the freedom that Page Builder gives me in terms of authoring experience on the PWA storefront while having the best storefront performance so that page created with page builder loads with ~0 CLS in Google lighthouse

Acceptance Criteria

Images dimensions specific to the viewport
Image is loaded progressively into the space reserved according to this dimensions
Page created with content types that include images show increased performance and ~0 CLS

## Related Issue

Closes #PWA-2295

## Verification Steps

Verify pagebuilder content type images load progressively Example - Home page, Customer service, about-us
Verify Images load across venia app like Home, Category, Product, Search, Cart, Wishlist, Mini cart
Verify above on Chrome, Safari, FF and mobile device
Verify with different pwa-studio image configs - backend and onboard. (Also check fastly vs non-fastly env)
Run lighthouse and webpagetest
Verify existing cypress tests run with no issues

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by michaelyu0123** [comment]
yarn run tests

**Comment by michaelyu0123** [comment]
run cypress

**Comment by michaelyu0123** [comment]
run cypress

**Review by pedrochiossi — APPROVED** [review]
All good ✅

**Comment by mikhaelbois** [comment]
@michaelyu0123 

1. We do have the dimensions for the shimmer, but shouldn't we have them on the images too?

image

2. Should images use the dimensions to set a ratio to they keep their proportions when the window is resized?

Capture d’écran, le 2022-02-21 à 11 29 46
Capture d’écran, le 2022-02-21 à 11 29 54
Capture d’écran, le 2022-02-21 à 11 31 16
Capture d’écran, le 2022-02-21 à 11 32 15

**Comment by fooman** [comment]
I find it odd that PageBuilder is not using the Image component from venia https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Image/image.js

In an ideal world it would be easy to reason how images work in a PWA Studio project. Having multiple different ways to deal with a similar thing detracts from this.

**Comment by michaelyu0123** [comment]
@mikhaelbois we can't add width and height attribute due to using source for mobile image which cannot specify source which will break responsiveness (will need to refactor to use img for both if we want that).
As for the other issue I have resolved it but will need re-approval.

**Comment by michaelyu0123** [comment]
run all tests

**Review by pedrochiossi — DISMISSED** [review]

**Comment by mikhaelbois** [comment]
run all tests

**Comment by mikhaelbois** [comment]
run cypress

**Comment by mikhaelbois** [comment]
@michaelyu0123 
Cypress test `integrationTests/pageBuilder/image.spec.js` is currently failing.

**Comment by michaelyu0123** [comment]
run all tests

**Comment by michaelyu0123** [comment]
@mikhaelbois resolved image cypress test failure

**Review by mikhaelbois — APPROVED** [review]

**Pull request merged**
