### PR TITLE
AC-2493::Items within actions menu are not operable for keyboard-only…

### PR DESCRIPTION
**Pull request by glo71317**
## Description
Items within actions menu are not operable for keyboard-only users (Shopping Bag)

**Reproduction Steps**
select "Blouses & Shirts" > select "Susanna Draped Tank" > add product to cart > select bag > select "Edit Shopping Bag" - [NODE][body>div:nth-of-type(1)>*:nth-child(1)>*:nth-child(3)]

1. Press Tab to move through the content.
2. When keyboard focus is on options (3 dots/"kebab") menu for a cart item, press Enter or Space to activate it.
3. Tab through each item in the options menu and press Enter or Space to activate.

**Actual Behavior**
There are actionable elements that are not functional with the keyboard alone. Examples include:

**Within actions menu:**

"Move to favorites"
"Edit Item"
"Remove from cart"

Keyboard-only users cannot access this functionality. (Note that these controls can be activated when a screen reader is operating.)

**Expected Behavior**
Ensure that all functionality can be activated using keyboard alone.

## Related Issue
Closes https://jira.corp.magento.com/browse/AC-2493

## Verification Steps
**Pre-Conditions:**

1. Have Magento instance with sample data installed
2. Make sure to have pwa studio installed
3. Make sure to have a customer login for front end login

**Manual Steps executed:**

Login to venia > select any product and add it to cart > select bag > select "Edit Shopping Bag"
Press Tab to move through the content.
When keyboard focus is on options (3 dots/"kebab") menu for a cart item, press Enter or Space to activate it.
Tab through each item in the options menu and press Enter or Space to activate. 

**✖️ Behaviour Before The Fix :** There are actionable elements that are not functional with the keyboard alone. Examples include:

Within actions menu:
"Edit Item"
"Remove from cart"

**✔️Behaviour After The Fix:** All functionalities are activated using keyboard alone.
image
image

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### Resolved issues:
1. [x] resolves magento/pwa-studio#3832: AC-2493::Items within actions menu are not operable for keyboard-only…

### CODE REVIEW

**Comment by glo71317** [comment]
run all tests

**Comment by supernova-at** [comment]
@magento create issue from PR

**Review by jcalcaben — APPROVED** [review]

**Comment by dpatil-magento** [comment]
run pr-deploy

**Comment by dpatil-magento** [comment]
run pr-test

**Comment by dpatil-magento** [comment]
run cypress

**Comment by dpatil-magento** [comment]
Now scree reader announce list items but still there are things like Kebab menu just say button instead of informative text. But its not part of this ticket so merging it once CI jobs pass.

**Review by dpatil-magento — APPROVED** [review]

**Pull request merged**
