### PR TITLE
PWA-3208::getting error on address page Unable to proceed checkout as…

### PR DESCRIPTION
**Pull request by glo80771**
… guest/registered user with my local instance after pulling latest changes

## Description

Steps to Reproduce
1. Use local magento URL with prerequisites as backend server into .env of pwa
2. Checkout to devlop server and install checkmo using command "yarn venia add -D @magento/venia-sample-payments-checkmo"
3. now yarn install and yarn build and yarn stage:venia
4. pickup URL and try to checkout with one of product
5. observe if any error while clicking on shipping button from shipping address page

Expected Result
1. User should be able to complete checkout without any issue
2. User should be able to create user without any issues.

Actual Result
1. getting error while clicking on shipping here on shipping address and unable to move to next screen
2. Unable to create new user

## Related Issue

Closes https://jira.corp.adobe.com/browse/PWA-3208.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by glo82145 — APPROVED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by seyuf** [comment]
@glo05548 unfortunately this invalidates the previous commit fixing issues when a country region is not required https://github.com/magento/pwa-studio/commit/e3a97e2180115995985707ad034c9d1d6621f82b

**Comment by seyuf** [comment]
Also this merge doesn't make any sense. You say you have issues with address on logged user. But the code you're modifying should only impact guests. Why is this merge without secondary review, anyway? Smells fishy...

**Pull request merged**
