### PR TITLE
PWA-1712: [bug]: fix region showing as number on braintree summary

### LINKED ISSUE #3322: [bug]: France Region/State in billing form is displaying as integer value instead of Name
URL - https://develop.pwa-venia.com/

### JIRA

https://jira.corp.magento.com/browse/PWA-1712

### To Reproduce 
1. Add product to cart and go to checkout form
2. Enter shipping address with **France** as country and select shipping method
3. Enter payment method, uncheck billing is same as shipping and enter France country but different address
4. Click on Review order button
5. Now observe the region in billing address

### Expected 
Region/State name should be displayed

### Actual 
Region/State Numeric ID is displayed, which is not at all useful for customer.

### Screenshot

In the following screenshot, notice that the **Payment Information** billing address shows the number "8" instead of the proper region (ex: "Ardèche"), that displays accurately in **Shipping Information**.

Screen Shot 2021-08-05 at 12 06 30 PM

### PR DESCRIPTION
**Pull request by pedrochiossi**
## Root Cause
The BraintreeSummary component was using region.code as the string value for State, this was causing a bug on countries like France where region.code is shown as a number, which is not useful for the client, in this case the right value to be used is region.label from [CartAdressRegion](https://devdocs.magento.com/guides/v2.4/graphql/queries/cart.html#CartAddressRegion)  

## Description
This PR changes the string value used for the state field on BraintreeSummary address.

## Related Issue

Closes #3322 .

## Acceptance

On CheckoutPage the Payment Information should not show any region code. It should show the region name (ex: Ardèche) as it is on Shipping Information.

## Verification Steps

1. Add product to cart and go to checkout form
2. Enter shipping address with France as country and select shipping method
3. Enter payment method, uncheck billing is same as shipping and enter France country but different address
4. Click on Review order button
5. Now observe the region in billing address

#### Test scenario(s) for direct fix/feature

1. Verify that the region code is no longer showing on billing address, instead it should show region label (name).

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by larsroettig** [comment]
Looks like Germany don't work with these changes anymore 

Screenshot from 2021-08-12 14-25-50

**Comment by pedrochiossi** [comment]
@larsroettig I've tested here and it seems to be working for Germany, might be some other error.

25986EAB-F87A-44F1-B265-A907E302D9AC

**Comment by supernova-at** [comment]
@larsroettig any more information in your console when that occurs?

**Comment by larsroettig** [comment]
@supernova-at sorry looks like is used a wrong credit card

**Comment by mikhaelbois** [comment]
Having two issues:

**First issue**
Backend returns this error:
`Uncaught (in promise) Error: Invalid value of "182" provided for the regionId field.`

Here's how to replicate:
- Start a completely new session
- Complete the QA steps until the Review Order Steps
- Enter your Billing Address with France as your Country and clicked on "Review Order"
- Edit your Billing Address and update your Country to Germany and click on "Update"

You should have an error preventing the update. Check your console to see the above error.

**Second issue**
State input has previous Region ID.
Not really linked to this task. A new bug could be opened for this.

Here's how to replicate:
- Start a completely new session
- Complete the QA steps until the Review Order Steps
- Enter your Billing Address with France as your Country and clicked on "Review Order"
- Edit your Billing Address and update your Country to Egypt

You should now see the number of the previous Region in the "ZIP / Postal Code" input
On the Shipping Information form, we get the Region Label instead when we update the Country.

**Comment by pedrochiossi** [comment]
@mikhaelbois I checked your issues they are both related to the form storing the previous state ID on the edit form. This is not related to my changes since this is a bug on the form. I think we should solve this on another issue.

**Comment by mikhaelbois** [comment]
✅ QA 

@pedrochiossi I'll see if we already have issues opened for what I've reported and create them.

**Review by larsroettig — DISMISSED** [review]

**Comment by mikhaelbois** [comment]
@pedrochiossi 
@tjwiebell took a look and saw that the snapshot for `useBraintreeSummary.spec.js` returns `undefined` for "state".
It would require an update of the test so "state" takes the right data.

**Review by supernova-at — APPROVED** [review]

**Comment by mikhaelbois** [comment]
✅ QA on updated test

**Pull request merged**
