### PR TITLE
fix(create-pwa): Fix escaping in shell command create-pwa sends to buildpack

### LINKED ISSUE #2317: [bug]: create-pwa can't handle a space in the folder hierarchy
**Describe the bug**
If create-pwa is executed in a folder with a space it fails.

**To reproduce**

1. git clone git@github.com:magento/pwa-studio.git 'folder with space'
2. cd folder\ with\ space
3. git checkout release/6.0
4. yarn install
5. DEBUG_PROJECT_CREATION=1 packages/create-pwa/bin/create-pwa

```
Creating a PWA Studio project
? Project root directory (will be created if it does not exist) test-folder
? Short name of the project to put in the package.json "name" field test-folder
? Name of the author to put in the package.json "author" field Kristof Ringleff, Fooman <me@example.com>
? Magento instance to use as a backend (will be added to `.env` file) 2.3.3-venia-cloud
? Braintree API token to use to communicate with your Braintree instance (will be added to `.env` file) sandbox_8yrzsvtm_s2bg8fs563crhqzk
? NPM package management client to use npm
? Install package dependencies with npm after creating project Yes

Running command:

buildpack create-project test-folder --template "venia-concept" --name "test-folder" --author "Kristof Ringleff, Fooman <me@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"


/bin/sh: /Users/kristof/Downloads/folder: No such file or directory
(node:35929) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/sh -c /Users/kristof/Downloads/folder with space/packages/pwa-buildpack/bin/buildpack create-project test-folder --template "venia-concept" --name "test-folder" --author "Kristof Ringleff, Fooman <kristof@fooman.co.nz>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"
    at makeError (/Users/kristof/Downloads/folder with space/node_modules/execa/index.
```

**Expected behavior**
Command succeeds

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version: 2.3.3
 - PWA Studio Version: 6.0.0-beta.2
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: v10.18.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

### PR DESCRIPTION
**Pull request by zetlen**
## Description

- Add escaping of space and quote characters in command path to buildpack
- Fix Node > 14 bug in DEBUG_PROJECT_CREATION

## Related Issue

Closes #2317.

### Verification Stakeholders

@fooman 
### Verification Steps

Follow steps in #2317 by renaming your repo root folder something with spaces in it. Try both kinds of quotation marks as well!

## Checklist

* I have added tests to cover my changes, if necessary.
* I have added translations for new strings, if necessary.
* I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by fooman** [comment]
Just to confirm the fix works on my end. Thanks @zetlen for tackling this.

**Review by supernova-at — DISMISSED** [review]

**Review by sirugh — APPROVED** [review]

**Comment by dpatil-magento** [comment]
@zetlen Space part looks good. But when meant ` quotation`, should something like `folder "with" space` this also work?

bin/sh: /Users/sdr/Documents/PWA/folder with space/packages/pwa-buildpack/bin/buildpack: No such file or directory
(node:23411) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/sh -c /Users/sdr/Documents/PWA/folder\ "with"\ space/packages/pwa-buildpack/bin/buildpack create-project fawfg --template "venia-concept" --name "fawfg" --author "tester <test@test.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"

**Comment by dpatil-magento** [comment]
@zetlen project create part with say `folder "with' space`  works fine but once inside scaffolded project `folder "with' space/scaffold-project` then commands like `npm run build` `npm run watch` `npm run storybook` fails with errors.  I was thinking create separate bug for this as original bug `folder with space`  works fine for all commands.  Also, its very rare to have directory name with single/double quotation marks. Let me know if you are ok with this.

 There is small prettier fix you need to push though :)

**Comment by dpatil-magento** [comment]
Created https://jira.corp.magento.com/browse/PWA-1527 to handle single/double quotation marks.  This PR is good to merge after prettier fix.

**Review by sirugh — APPROVED** [review]

**Pull request merged**
