### PR TITLE
PWA-3071::Graphql Cart > Prices > Discounts array also including Gift…

### PR DESCRIPTION
**Pull request by glo82145**
… Cards in 2.4.6

## Description

URL - https://pr-4030.pwa-venia.com/

Steps -
1. Add One or 2 products to cart
2. Go to cart page and first add Coupon code pwa1423
3. Now also add gift card 02Y0LCHUNDRZ and check graphql response.

Issue - As per 2.4.5, Prices > Discounts array should not contain gift cards. But on 2.4.6, Prices > Discounts array contains gift cards as well. First check with PO whats the expected behavior.

NOTE. - We have cypress test which is failing

venia-integration-tests/src/tests/e2eTests/cart/userRemoveCartPromotions.spec.js

## Related Issue

Closes #https://jira.corp.adobe.com/browse/PWA-3071

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-mobile

**Review by glo42707 — APPROVED** [review]
Approving PR based on QA PASS on https://jira.corp.adobe.com/browse/PWA-3071

**Comment by glo42707** [comment]
QA PASS on https://jira.corp.adobe.com/browse/PWA-3071

**Comment by glo42707** [comment]
run cypress

**Comment by fooman** [comment]
just fyi checking for the label of something will fail the moment the language is not English and/or the term was translated by the back-end.

**Pull request merged**
