### PR TITLE
Test latest build

### PR DESCRIPTION
**Pull request by DanielRuf**
Please do not close. Used for testing the current latest version on develop and the PWA-Studio bot.

### CODE REVIEW

**Comment by sirugh** [comment]
@DanielRuf what is this for exactly?

**Comment by DanielRuf** [comment]
As described in the issue:

> Please do not close. Used for testing the current latest version on develop and the PWA-Studio bot.

An empty commit can trigger CI - needed this also for a demo for a colleague and will likely use it for the local React meetup group.

**Comment by sirugh** [comment]
We deploy a version of `develop` whenever a PR is merged. You can access that here: https://develop.pwa-venia.com. Or did you specifically need a PR deployment or to view something with our CI process?

**Comment by DanielRuf** [comment]
It's for demonstration purposes (the bot / CI process and testing) and for a talk at a React meetup.

**Comment by DanielRuf** [comment]
But what does `now` do in this context?

**Comment by sirugh** [comment]
> But what does `now` do in this context?

`now` deploys our app. It's like a container. Sort of like netlify or heroku. This is their homepage http://now.sh

That said, we are actually deploying via AWS Codebuild. `now` is being deprecated and will eventually be removed as a "check" in our CI. You can see the Danger comment with a link to a deployment of the PR.

**Comment by jimbo** [comment]
@DanielRuf This isn't what PRs are for. 😅

If there's something you need from us, please open an issue. Otherwise, let's discuss further in the Community Engineering Slack. 🙂

**Comment by DanielRuf** [comment]
Well, other members also test like this, I am not the only one ;-) And an empty commit is a valid PR as you can see.

**Pull request closed without merging**
