### PR TITLE
Tailwind v3 Update

### LINKED ISSUE #4081: [feature]: Tailwind v3 support
**Is your feature request related to a problem? Please describe.**
Not a problem necessarily. Tailwind v3 comes with some additional utilities which are helpful for development.

**Describe the solution you'd like**
Update to Tailwind v3. At the same time it would be good to address some of the issues with the current tailwind implementation in venia components (direct css use, priority issues, `@TODO` tailwind comments, hardcoded values in tokens.module.css/index.module.css files)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`
- [x] `pwa-theme-venia`

### PR DESCRIPTION
**Pull request by justinconabree**
## Description

- Updating Tailwind dependency to v3 (latest). Some required fixes documented [here](https://tailwindcss.com/docs/upgrade-guide)
- Fixing priority issues caused by Tailwind update. These were already described as B6 issues, but the update exacerbated the problem. The fix for this was using `@apply` when using composes from another class and overriding values.
  - Note styles may change from this as some styling isn't currently applied due to the B6 issue in current Venia (small bugs throughout the site previous to this change). In some cases I've removed the overrides so existing styles stay consistent.
- Changing tokens and index css files to use tailwind configurations
- Exposing key colors as css variables for use in legacy tokens
- Adding new values to theme config and replacing usage in css files
- Using new button and input border roundness for better configurability
- Changing media queries to tailwind variants
- Fixing many `@TODO tailwind` comments

Styles that have changed due to B6 being corrected
- Footer where the columns are spaced evenly
- Checkout form area when editing no longer has border

## Related Issue

Closes #4081

### Specification

Changes to theme must be reviewed

#### Test scenario(s) for direct fix/feature

Full pass through site to verify no major style changes across all screen sizes

#### Test scenario(s) for any Magento Backend Supported Configurations

None

#### Is Browser/Device testing needed?

Yes, device testing is required as styles may vary based through all breakpoints

#### Any ad-hoc/edge case scenarios that need to be considered?

All features (states) must be tested

## Breaking Changes (if any)

Updating PWA Studio (Venia) from Tailwind V2 to V3 has required some changes.

For starters, developers should look over [Tailwind's Upgrade Guide](https://tailwindcss.com/docs/upgrade-guide) to see what the general implications of Tailwind V3 are for their project.

Some additional configurations have been made available in the theme and implemented in Venia. These include
- New border radiuses for component types
  - input, button, box, badge
- Border colors
  - input
  - swatch
  - base
  - current color (fix for TW3)
- Line heights attached to font size
- Additional media queries (max screen sizes, min/max height)
- Shimmer
  - Background color
  - Animation
- Spacing utils for screen widths and header spacing
- Width utils
- Screen sizes necessary to convert venia-ui to use Tailwind config in all instances (pagebuilder excluded)
  - Change xl screen size to 1024px (unused previous to this update)

Some key colors are also now exposed through CSS variables using the root plugin. These variables are then used in the base tokens file so legacy use now runs off of tailwind configuration.

## Checklist

- ~[ ] I have added tests to cover my changes, if necessary.~
- ~[ ] I have added translations for new strings, if necessary.~
- [x] I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by justinconabree** [comment]
Hi @anthoula, @glo82145,  can you please follow up with PWA Studio team to see if I should continue to work on this.

Thanks!

**Comment by glo82145** [comment]
@justinconabree Please feel free to proceed on this PR.  Please assign this issue to yourself. 

Thanks

**Comment by justinconabree** [comment]
Hi @glo42707 ,

Work is done on my end. I've added some notes to the PR description that should be added to release notes eventually. There will be some implications for projects (major version bump necessary).

I'm seeing some issues in the [deployed PR instance](https://pr-4082.pwa-venia.com/) though. It isn't compiling `@apply` rules properly. They're coming out raw instead of compiled (eg `@apply box-border` VS `box-sizing: border-box`). This works locally with both yarn watch:venia and yarn build && yarn stage:venia. Any idea what might be happening?

Also there are some cypress tests failing, but they're also failing on develop so I haven't updated any of the snapshots.

**Comment by glo42707** [comment]
hey @justinconabree 

thanks for work on PR, now regarding your issue regarding size etc. that a knows issue due to one of active cypress comatibility. so it will be resolved in future, once after we will have fix available.

**Review by glo82145 — DISMISSED** [review]

**Comment by justinconabree** [comment]
Hi @glo42707, @glo82145 

Is there progress for getting this merged in?

Thanks!

**Comment by glo42707** [comment]
hey @justinconabree 

Thanks for reaching out.
we have planned release by 23 October 2023 but it will be merge with develop on or before 29 Spetamber while release cut.

**Comment by justinconabree** [comment]
Great @glo42707 ! Thanks for the update!

**Comment by fooman** [comment]
@glo42707 this still on track to get merged?

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
run lighthouse-mobile

**Comment by glo82145** [comment]
@justinconabree Lighthouse tests are failing in this PR. Can you please look into that

**Comment by justinconabree** [comment]
@glo82145 looking into it! Will provide updates early next week

**Comment by justinconabree** [comment]
Hi @glo82145 ,

I'm seeing some weird behaviour. Locally with this branch the site looks okay compared to develop, but on the PR instance there's a lot of visual bugs. I've attached some screenshots.

local_instance
PR_instance

Any idea why this might be happening? I have a feeling at least some of these issues are behind the lower lighthouse scores

**Comment by glo42707** [comment]
hey @justinconabree 

those are default UI implamntation on PWA studio which is already in place since past few release as per my knowledge and it is not impacting in any other current PR pr PWA but only facing issue only with this PR 4082.
hence request to please check and fix for furthure step to merege.

**Comment by justinconabree** [comment]
Hi @glo42707 ,

Is it possible the deployed PR instance is out of date with the branch? I made the PR when the work was incomplete. Does it get redeployed for each commit?

Thanks

**Comment by justinconabree** [comment]
Hi @glo42707,

Just following up to see if you'd know why the PR instance doesn't reflect the up-to-date branch code. Is it possible to redeploy the code to the PR instance?

Thanks

**Comment by glo42707** [comment]
hey @anthoula and @supernova-at 

could you please help on query asked by @justinconabree if that is possible case.

Thanks

**Comment by anthoula** [comment]
It should redeploy after each new commit, and closing and opening a new PR as well.

**Comment by justinconabree** [comment]
I'll try closing PR and opening a new one. `pr-deploy` task is marked as success but I'm still seeing major differences between local and PR instance. Hopefully new PR helps🤞

**Pull request closed without merging**
