### PR TITLE
Bug#pwa 3055 Homepage slider creates unexpected GET-requests

### PR DESCRIPTION
**Pull request by RaghavendraTirumalasetti**
## Description

To reproduce

Go to [venia.](https://venia.magento.com/) with dev console open
Open "Network" tab and filter by "null"
Review "Network" tab results
Expected behavior

No requests with "/null"

## Related Issue

Closes #https://jira.corp.adobe.com/browse/PWA-3055

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by glo82145 — APPROVED** [review]

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run cypress

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run lighthouse-mobile

**Pull request closed without merging**
