### PR TITLE
PWA-1961: [PB] Parallax video background is broken on Safari

### PR DESCRIPTION
**Pull request by michaelyu0123**
- Resolve parallax video background video overflow issue on safari

## Description

Safari has a quirk in which when using translation3d which contains z translation, it interacts poorly with z-index which Jarallax library utilizes to create the parallax. And thus to resolve it I overwrote the z-index default from -1 to auto. 
https://stackoverflow.com/questions/40895387/z-index-not-working-on-safari-fine-on-firefox-and-chrome

Setting video background for row with enabled parallax looks broken in Venia for Safari browser. Video stretches to full screen (see screenshots)

Steps to Reproduce

1. Create cms page containing row with video background and parrallax setting enabled in PageBuilder (video test content from PWA-1156 maybe used)
2. Using Safari browser, visit created cms page

 Expected: video stays in row boundary and parallax effect is applied when scrolling the page
 Video is stretched to the full screen

* Safari Version 14.1.2 (16611.3.10.1.3)

## Related Issue

Closes #PWA-1961

#### Test scenario(s) for any Magento Backend Supported Configurations
Verify video background with various parallax settings - PWA-1156
Verify in various desktop & mobile browsers

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Review by pedrochiossi — APPROVED** [review]

**Comment by ericeoeur** [comment]
After several attempts to create a cms page containing row with video background and parrallax setting enabled and using content from PWA-1156, I am unable to replicate the video issue in Safari and I receive the following error in Chrome DevTools

Screen Shot 2022-02-04 at 2 43 10 PM

**Comment by michaelyu0123** [comment]
@ericeoeur  what video source were you using for testing?

**Comment by ericeoeur** [comment]
@michaelyu0123 , I was using the content found in [PWA-1156](https://jira.corp.magento.com/browse/PWA-1156), specifically, I used the [video contents ](https://www.youtube.com/embed/slOtnjsbff0)found in [row-video-background1.txt](https://jira.corp.magento.com/secure/attachment/435236/row-video-background1-v2.txt). Additionally, I tried other YouTube embed videos and set up the background builder in page builder with parallax as prescribed with the same result as the screenshot above.

**Comment by ericeoeur** [comment]
QA ✅
Need https://github.com/magento/pwa-studio/pull/3694 to be finished to make sure Cypress tests are up to date. Otherwise, will merge soon. Thanks!

**Pull request merged**
