### PR TITLE
VULN-25329: Update devdocs-theme dependency

### PR DESCRIPTION
**Pull request by jeff-matthews**
## Description

~This pull request (PR) deletes the `pwa-devdocs/` directory from the project.~

~Documentation was migrated to the https://github.com/AdobeDocs/commerce-pwa-studio repo and that's where it is actively maintained. That's also the source that we deploy to [production](https://developer.adobe.com/commerce/pwa-studio).~

Reverting deletion of `pwa-devdocs/` directory and limiting scope to addressing the devdocs-theme dependency for legacy deployments to devdocs.magento.com. We no longer deploy the contents of the `pwa-devdocs` directory to devdocs.magento.com.

## Related Issue

VULN-25329

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by glo42707** [comment]
run lighthouse-desktop

**Comment by glo42707** [comment]
run cypress

**Comment by jeff-matthews** [comment]
Reverting deletion of `pwa-devdocs/` directory and limiting scope to addressing the devdocs-theme dependency for legacy deployments to devdocs.magento.com.

**Comment by glo42707** [comment]
tested and working fine.
QA approved

**Review by glo82145 — APPROVED** [review]

**Comment by glo82145** [comment]
run lighthouse-desktop

**Comment by glo82145** [comment]
run lighthouse-mobile

**Pull request merged**
