### PR TITLE
change workbox-build version to match workbox-webpack-plugin

### PR DESCRIPTION
**Pull request by sharkySharks**
## Description

There is an error in scaffolding after PR #3348 was merged. Running `yarn run build` would produce the following error:
Screen Shot 2021-09-29 at 2 03 38 PM

Fixing the workbox-build plugin version to match the workbox-webpack-plugin version resolved this issue in the QA CI environment ([build output here](https://us-east-1.console.aws.amazon.com/codesuite/codebuild/613317577116/projects/pwa-scaffold-build/build/pwa-scaffold-build%3Ad9f747b1-6b75-4109-a1d2-0b0e49963c38/?region=us-east-1)).

https://jira.corp.magento.com/browse/PWA-2177

## Related Issue

Related PR in the CICD repo: https://github.com/magento-commerce/pwa-studio-cicd/pull/91

## Acceptance
Watch the scaffold build job pass after this is merged to the develop branch. This is the job that is run on merge to develop to test that scaffolding is not broken.

## Verification Steps

This would be easiest to check in the QA ci environment, where all jobs are mirrored.

### CODE REVIEW

**Comment by fooman** [comment]
I believe the resolution block was added to temporarily pin to an older version. Now that the workbox issue is resolved the complete entry could be deleted.

**Comment by tjwiebell** [comment]
Those resolution blocks were removed in https://github.com/magento/pwa-studio/pull/3378/files#diff-8649efa8b7512568089ed247cc1159250817bd705d275198461e93d793d084f8L108:L110, somehow they snuck back in with #3348.

**Comment by sharkySharks** [comment]
okay I can run some more tests removing the entire resolution block

**Comment by sharkySharks** [comment]
tested out removing the block entirely and the build succeeded in our qa environment. 👍

**Comment by zetlen** [comment]
@tjwiebell OK, that one's my bad. I thought about kicking #3348 back because of that workbox update, but then I saw it in other PRs and I got confused. Should have noticed it was a merge error.

**Review by zetlen — APPROVED** [review]
After adding the **version: Patch** label, this is all passing clean. Thanks for getting to the bottom of it!

**Pull request merged**
