### PR TITLE
[Do Not Merge] Arcticfoxes CI PR

### PR DESCRIPTION
**Pull request by dhaecker**
## Description

TODO: Describe your changes in detail here.

## Related Issue

Closes #ISSUE_NUMBER.

## Checklist

-   I have added tests to cover my changes, if necessary.
-   I have added translations for new strings, if necessary.
-   I have updated the documentation accordingly, if necessary.

### CODE REVIEW

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress

**Comment by dpatil-magento** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5-alpha2 w/ session feature toggle disabled

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5-alpha6 w/ session feature toggle disabled

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5-alpha9 w/ session feature toggle disabled

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5 + B2B-2379

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5 + B2B-2331

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
run cypress @e2e

**Comment by dhaecker** [comment]
running tests for 2.4.5 + B2B-2404

**Comment by dhaecker** [comment]
run cypress @e2e

**Pull request closed without merging**
